"""
==========
V2_MDCR_PRVDR_ENRLMT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT

Table Type: VIEW
Columns: 41
Source Pattern: %prvdr_enrlmt%
Table Comment: THE PARENT HEADER RECORD OF THE ENROLLMENT INFORMATION. THIS ENTITY STORES THE CURRENT RECORDS ONLY.  PECOS: EACH INSTANCE CONTAINS THE BASE DATA REQUIRED FOR AN INDIVIDUAL OR ORGANIZATION TO APPLY FOR THE AUTHORITY TO BILL MEDICARE FOR SERVICES RENDERED. AN ENROLLMENT IS THE PROCESS OF A PROVIDER ACCEPTING ASSIGNMENT OF AN AGREEMENT WITH CMS THAT QUALIFIES THE PROVIDER TO BILL MEDICARE FOR SERVICES IT RENDERS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrEnrlmtExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrEnrlmtExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_ENRLMT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT (VIEW)
    Columns: 41
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_enrlmt_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_ENRLMT export.
        
        Includes all 41 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_ENRLMT_ID, -- TEXT(15) | NOT NULL | PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
                PRVDR_PAC_ID, -- TEXT(10) | NOT NULL | THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
                PRVDR_ENRLMT_LGL_BUSNS_NAME, -- TEXT(70) | NOT NULL | PROVIDER LEGAL BUSINESS NAME
                PRVDR_ENRLMT_TIN_NUM, -- TEXT(9) | NOT NULL | TAX IDENTIFICATION NUMBER, SUCH AS AN EMPLOYER IDENTIFICATION NUMBER (EIN) OR SOCIAL SECURITY NUMBER (SSN).
                PRVDR_ENRLMT_TIN_TYPE_CD, -- TEXT(1) | NOT NULL | IDENTIFIES THE TYPE OF TIN, SUCH AS EMPOYER IDENTIFICATION NUMBER OR SOCIAL SECURITY NUMBER.
                PRVDR_ENRLMT_MLG_LINE_1_ADR, -- TEXT(55) | NOT NULL | FIRST LINE OF THE PROVIDER CORRESPONDENCE ADDRESS.
                PRVDR_ENRLMT_MLG_LINE_2_ADR, -- TEXT(55) | NULL | LINE 2 OF PECOS ASSOCIATE MAILING ADDRESS.
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_ENRLMT_INVLD_PLC_NAME, -- TEXT(30) | NULL | PLACE NAME OF MAILING ADDRESS. POPULATED ONLY WHEN THE PLACE NAME SUPPLIED BY THE PECOS SYSTEM DIFFERS FROM THE PLACE NAME ASSOCIATED WITH THE CORRESPONDING ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA. PECOS IS NOT THE AUTHORITATIVE SOURCE OF
                PRVDR_ENRLMT_INVLD_STATE_CD, -- TEXT(2) | NULL | UNIQUE VALUE THAT IDENTIFIES A STATE. STATE CODE OF MAILING ADDRESS. POPULATED ONLY WHEN THE STATE CODE SUPPLIED BY THE PECOS SYSTEM DIFFERS FROM THE PLACE NAME ASSOCIATED WITH THE CORRESPONDING ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA. PECOS IS NOT THE AUTHORITATIVE SOURCE OF ZIP CODE DATA.
                PRVDR_ENRLMT_INVLD_ZIP_CD, -- TEXT(9) | NULL | ZIP CODE FOR ENROLLMENT ADDRESS. INVALID ZIP CODE ON ENROLLMENT RECORD. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_ENRLMT_FRGN_STATE_NAME, -- TEXT(30) | NULL | NAME OF STATE USED WITH FOREIGN ADDRESS.
                PRVDR_ENRLMT_FRGN_PSTL_CD, -- TEXT(15) | NULL | POSTAL CODE ASSOCIATED WITH FOREIGN CORRESPONDENCE ADDRESSES.
                PRVDR_ENRLMT_CNTRY_NAME, -- TEXT(30) | NULL | OFFICIAL SHORT NAME OF A COUNTRY IN ENGLISH.
                PRVDR_ENRLMT_ADR_BGN_DT, -- DATE | NOT NULL | DATE THE CORRESPONDENCE ADDRESS BECAME VALID.
                PRVDR_ENRLMT_PHNE_NUM, -- TEXT(20) | NOT NULL | TELEPHONE NUMBER OF THE CORRESPONDENCE ADDRESS.
                PRVDR_ENRLMT_FAX_NUM, -- TEXT(20) | NULL | THE FAX NUMBER OF THE CORRESPONDENCE ADDRESS.
                PRVDR_ENRLMT_EMAIL_ADR, -- TEXT(80) | NULL | PROVIDER EMAIL ADDRESS
                PRVDR_ENRLMT_NATL_SUPLR_IND_CD, -- TEXT(1) | NOT NULL | NATIONAL SUPPLIER INDICATOR CODE. INITIALLY, THIS IS SET TO N, FOR NO.
                PRVDR_ENRLMT_RGN_A_IND_CD, -- TEXT(1) | NULL | WHEN TRUE, INDICATES THAT A SUPPLIER IS PERMITTED TO SUBMIT CLAIMS TO JURISDICTION A.
                PRVDR_ENRLMT_RGN_B_IND_CD, -- TEXT(1) | NULL | WHEN TRUE, INDICATES THAT A SUPPLIER IS PERMITTED TO SUBMIT CLAIMS TO JURISDICTION A.
                PRVDR_ENRLMT_RGN_C_IND_CD, -- TEXT(1) | NULL | WHEN TRUE, INDICATES THAT A SUPPLIER IS PERMITTED TO SUBMIT CLAIMS TO JURISDICTION C.
                PRVDR_ENRLMT_RGN_D_IND_CD, -- TEXT(1) | NULL | WHEN TRUE, INDICATES THAT A SUPPLIER IS PERMITTED TO SUBMIT CLAIMS TO JURISDICTION D.
                PRVDR_ENRLMT_1ST_NAME, -- TEXT(25) | NULL | PROVIDER FIRST NAME
                PRVDR_ENRLMT_LAST_NAME, -- TEXT(35) | NULL | PROVIDER LAST NAME
                META_SK, -- NUMBER(38) | NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_ENRLMT_CNTRCTR_ID, -- TEXT(5) | NOT NULL | UNIQUE NUMBER THAT IDENTIFIES A MEDICARE CONTRACTOR.
                PRVDR_ENRLMT_CREAT_DT, -- DATE | NOT NULL | DATE THE RECORD WAS CREATED (MM/DD/YYYY)
                PRVDR_ENRLMT_SPCLTY_CD, -- TEXT(2) | NOT NULL | A CODE IDENTIFYING THE CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) SPECIALTY OF A PROVIDER OR SUPPLIER. FOR EXAMPLE: 11 = INTERNAL MEDICINE 49 = AMBULATORY SURGICAL CENTER REFERENCE TABLE: CLM_PRVDR_SPCLTY_CD
                PRVDR_ENRLMT_DEATH_DT, -- DATE | NULL | PECOS ASSOCIATES DATE OF DEATH. THIS DATA ELEMENT IS NOT CAPTURED ON ANY 855 FORM. ITS CAPTURES FROM THE APPROVED PENDING UPIN PROCESS.
                PRVDR_ENRLMT_FORM_TYPE_CD, -- TEXT(2) | NULL | UNIQUE VALUE THAT IDENTIFIES THE TYPE OF ENROLLMENT FORM. THE TYPES MAY BE A 855R, 855C, ETC.
                PRVDR_ENRLMT_FRGN_ADR_IND, -- TEXT(1) | NOT NULL | INDICATES WHETHER THE ADDRESS IS A FOREIGN ADDRESS.
                PRVDR_ENRLMT_GRDTN_YR_NUM, -- NUMBER(4) | NULL | THE YEAR THE INDIVIDUAL PRACTITIONER GRADUATED FROM MEDICAL SCHOOL.
                PRVDR_ENRLMT_MDCL_SCHL_ID, -- TEXT(5) | NULL | UNIQUE MEDICAL SCHOOL CODE. EXHIBIT 3A OF THE PHYSICIAN IDENTIFICATION AND REGISTRATION DOCUMENT LISTS THE MEDICAL SCHOOL CODES.
                PRVDR_ENRLMT_MDL_NAME, -- TEXT(25) | NULL | MIDDLE NAME OF PECOS ASSOCIATE.
                PRVDR_ENRLMT_PRVDR_TYPE_CD, -- TEXT(2) | NOT NULL | UNIQUE VALUE THAT IDENTIFIES A FACILITY TYPE.
                PRVDR_ENRLMT_SPCLTY_EFCTV_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN AN ENROLLMENT RECORD BECAME EFFECTIVE.
                PRVDR_ENRLMT_STATE_CD, -- TEXT(2) | NOT NULL | UNIQUE VALUE THAT IDENTIFIES A STATE.
                PRVDR_ENRLMT_SUPLR_TYPE_CD -- TEXT(2) | NULL | UNIQUE VALUE THAT IDENTIFIES THE TYPE OF SERVICE THE SUPPLIER WILL PROVIDE. E.G., AMBULANCE SERVICE , DIAGNOSTIC RADIOLOGY PRACTICE, MASS IMMUNIZATION. ETC..
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrEnrlmtExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
