"""
==========
V2_MDCD_PRVDR_ENRLMT_CRNT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCD_PRD.V2_MDCD_PRVDR_ENRLMT_CRNT

Table Type: VIEW
Columns: 22
Source Pattern: %prvdr_enrlmt%
Table Comment: A RECORD TO CAPTURE THE PROVIDER’S PERIODS OF PARTICIPATION IN THE STATES MEDICAID/CHILDRENS HEALTH INSURANCE PROGRAM (CHIP) PROGRAMS, AND THE REASON FOR A CHANGE IN ENROLLMENT STATUS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcdPrvdrEnrlmtCrntExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcdPrvdrEnrlmtCrntExporter(IDROutputter):
    """
    Exports V2_MDCD_PRVDR_ENRLMT_CRNT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCD_PRD.V2_MDCD_PRVDR_ENRLMT_CRNT (VIEW)
    Columns: 22
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcd_prvdr_enrlmt_crnt_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCD_PRVDR_ENRLMT_CRNT export.
        
        Includes all 22 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                SUBMTG_MDCD_LCL_STATE_CD, -- TEXT(2) | NOT NULL | THE MEDICAID STATE SPECIFIC LOCAL STATE CODE VALUE FOR A GIVEN RECORD
                PRVDR_STATE_MDCD_ID, -- TEXT(30) | NOT NULL | THE STATE-ASSIGNED UNIQUE IDENTIFIER FOR THE PROVIDER ENTITY. NOTE THAT ALL INDIVIDUALS, PRACTICE GROUPS, FACILITIES, AND OTHER ENTITIES THAT PROVIDE MEDICAID/CHIP GOODS OR SERVICES TO THE STATEÒ² MEDICAID/CHIP ENROLLEES SHOULD BE REFLECTED IN THE TRANSFORMED MEDICAID STATISTICAL INFORMATION SYSTEM (T-MSIS) PROVIDER DATA SET.
                IDR_PRVDR_MDCD_ENRLMT_PLAN_CD, -- TEXT(1) | NOT NULL | A CODE DERIVED BY THE IDR FROM THE SOURCE SYSTEM VALUE THAT IDENTIFIES THAT THE PROVIDER IS ENROLLED IN MEDICAID OR CHILDRENS HEALTH INSURANCE PROGRAM (CHIP).
                IDR_TRANS_EFCTV_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) IDENTIFYING WHEN A RECORD IS LOADED.
                PRVDR_SRC_EFCTV_DT, -- DATE | NOT NULL | A DATE FOR THE FIRST DAY OF THE TIME SPAN ASSOCIATED WITH THE STATUS OF THE PROVIDERS ENROLLMENT IN THE MEDICAID OR CHILDRENS HEALTH INSURANCE PROGRAM (CHIP) PLAN (AS MAPPED FROM THE STATE-SUBMITTED-SEGMENT-EFFECTIVE-PERIOD-START).
                PRVDR_MDCD_ENRLMT_STUS_CD, -- TEXT(2) | NOT NULL | A CODE REPRESENTING THE PROVIDERÒ² ENROLLMENT STATUS IN THE MEDICAID/MEDICAID EXPANSION CHILDRENS HEALTH INSURANCE PROGRAM (CHIP) OR SEPARATE CHIP PLAN.
                PRVDR_MDCD_ENRLMT_MTHD_CD, -- TEXT(1) | NOT NULL | A CODE ASSIGNED TO IDENTIFY THE PROCESS BY WHICH A PROVIDER WAS ENROLLED IN THE MEDICAID OR CHILDRENS HEALTH INSURANCE PROGRAM (CHIP) PLAN.
                PRVDR_MDCD_ENRLMT_PLAN_CD, -- TEXT(1) | NULL | A CODE ASSIGNED BY THE SOURCE SYSTEM TO IDENTIFY THE MEDICAID OR CHILDRENS HEALTH INSURANCE PROGRAM (CHIP) PLAN THAT THE PROVIDER IS ENROLLED.
                IDR_PRVDR_MDCD_ENRLMT_PLAN_SW, -- TEXT(1) | NULL | YES/NO SWITCH THAT THE IDR HAS DERIVED A NEW VALUE FOR THE STATE PLAN ENROLLMENT YES = IDR HAS DERIVED THE PLAN CODE = 3 (BOTH MEDICIAID AND CHIP) INTO TWO RECORDS ONE WITH A 1 AND THE OTHER WITH A 2. NO = PLAN CODE IS WHAT WAS SUBMITTED BY THE SOURCE.
                PRVDR_SRC_END_DT, -- DATE | NULL | THE END DATE ASSOCIATED WITH THE STATUS OF THE PROVIDERS ENROLLMENT IN THE MEDICAID OR CHILDRENS HEALTH INSURANCE PROGRAM (CHIP) PLAN.
                PRVDR_APLD_DT, -- DATE | NULL | THE DATE THE PROVIDER APPLIED FOR ENROLLMENT INTO THE STATEÒ² MEDICAID AND/OR CHILDRENS HEALTH INSURANCE PROGRAM (CHIP) PROGRAM.
                PRVDR_STATE_NOTN_TXT, -- TEXT(500) | NULL | A FREE TEXT FIELD FOR THE SUBMITTING STATE TO ENTER WHATEVER INFORMATION IT CHOOSES.
                IDR_PRVDR_END_DT_SW, -- TEXT(1) | NULL | A YES/NO SWITCH SIGNIFYING A NON-OVERLAPPING END DATE HAS BEEN DERIVED BY THE IDR
                IDR_PRVDR_END_DT, -- DATE | NULL | THE NON-OVERLAPPING END DATE DERIVED BY THE IDR
                IDR_TRANS_OBSLT_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN A RECORD WAS LAST KNOWN TO BE PRESENT IN THE SOURCE. THE CURRENT VERSION OF A RECORD WILL BE SET TO 12/31/9999 00:00:00.
                IDR_LTST_TRANS_FLG, -- TEXT(1) | NOT NULL | AN INDICATOR ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) THAT IDENTIFIES WHICH TRANSACTION RECORD, BASED ON PRIMARY KEY, IS CONSIDERED TO REPRESENT THE MOST RECENT RECORD RECEIVED FROM THE SOURCE. Y = LATEST VERSION OF THE RECORD N = PREVIOUS VERSION OF THE RECORD
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                TMSIS_RPTG_PRD_TXT, -- TEXT(20) | NOT NULL | THE REPORTING PERIOD OF THE TRANSFORMED MEDICAID STATISTICAL INFORMATION SYSTEM (T-MSIS) DATA
                META_SRC_PRCSG_ID, -- NUMBER(38) | NOT NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS INSERTED.
                META_LTST_SRC_PRCSG_ID, -- NUMBER(38) | NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS SUBSEQUENTLY UPDATED.
                IDR_INSRT_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHILE PERFORMING AN INSERT OPERATION.
                IDR_UPDT_TS -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN UPDATES ARE MADE TO ANY NON-PRIMARY KEY COLUMN.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCD_PRD.V2_MDCD_PRVDR_ENRLMT_CRNT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcdPrvdrEnrlmtCrntExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
