SELECT
    'CLM_FAC_PRVDR_CPO_ORG_NPI_ID' AS column_name,
    COUNT(*) AS npi_present_count
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
WHERE CLM_THRU_DT >= DATE '2025-01-01'
    AND CLM_THRU_DT < DATE '2026-01-01'
    AND CLM_FAC_PRVDR_CPO_ORG_NPI_ID IS NOT NULL
    AND CLM_FAC_PRVDR_CPO_ORG_NPI_ID <> '~'
UNION ALL
SELECT
    'CLM_FAC_PRVDR_NPI_NUM' AS column_name,
    COUNT(*) AS npi_present_count
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
WHERE CLM_THRU_DT >= DATE '2025-01-01'
    AND CLM_THRU_DT < DATE '2026-01-01'
    AND CLM_FAC_PRVDR_NPI_NUM IS NOT NULL
    AND CLM_FAC_PRVDR_NPI_NUM <> '~'
UNION ALL
SELECT
    'PRVDR_CPO_FAC_NPI_NUM' AS column_name,
    COUNT(*) AS npi_present_count
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
WHERE CLM_THRU_DT >= DATE '2025-01-01'
    AND CLM_THRU_DT < DATE '2026-01-01'
    AND PRVDR_CPO_FAC_NPI_NUM IS NOT NULL
    AND PRVDR_CPO_FAC_NPI_NUM <> '~'
UNION ALL
SELECT
    'PRVDR_RNDRNG_PRVDR_NPI_NUM' AS column_name,
    COUNT(*) AS npi_present_count
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
WHERE CLM_THRU_DT >= DATE '2025-01-01'
    AND CLM_THRU_DT < DATE '2026-01-01'
    AND PRVDR_RNDRNG_PRVDR_NPI_NUM IS NOT NULL
    AND PRVDR_RNDRNG_PRVDR_NPI_NUM <> '~'
UNION ALL
SELECT
    'CLM_ALTRNT_SRVC_PRVDR_NPI_NUM' AS column_name,
    COUNT(*) AS npi_present_count
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
WHERE CLM_THRU_DT >= DATE '2025-01-01'
    AND CLM_THRU_DT < DATE '2026-01-01'
    AND CLM_ALTRNT_SRVC_PRVDR_NPI_NUM IS NOT NULL
    AND CLM_ALTRNT_SRVC_PRVDR_NPI_NUM <> '~'
UNION ALL
SELECT
    'CLM_PRSCRBNG_PRVDR_NPI_NUM' AS column_name,
    COUNT(*) AS npi_present_count
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
WHERE CLM_THRU_DT >= DATE '2025-01-01'
    AND CLM_THRU_DT < DATE '2026-01-01'
    AND CLM_PRSCRBNG_PRVDR_NPI_NUM IS NOT NULL
    AND CLM_PRSCRBNG_PRVDR_NPI_NUM <> '~'
UNION ALL
SELECT
    'CLM_PCP_NPI_NUM' AS column_name,
    COUNT(*) AS npi_present_count
FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
WHERE CLM_THRU_DT >= DATE '2025-01-01'
    AND CLM_THRU_DT < DATE '2026-01-01'
    AND CLM_PCP_NPI_NUM IS NOT NULL
    AND CLM_PCP_NPI_NUM <> '~'
ORDER BY column_name;

-- results
-- CLM_ALTRNT_SRVC_PRVDR_NPI_NUM	0
-- CLM_FAC_PRVDR_CPO_ORG_NPI_ID	0
-- CLM_FAC_PRVDR_NPI_NUM	0
-- CLM_PCP_NPI_NUM	0
-- CLM_PRSCRBNG_PRVDR_NPI_NUM	0
-- PRVDR_CPO_FAC_NPI_NUM	0
-- PRVDR_RNDRNG_PRVDR_NPI_NUM	1793961