WITH sampled_claims AS (
    SELECT
        CLM_ATNDG_PRVDR_NPI_NUM,
        CLM_BLG_PRVDR_NPI_NUM,
        CLM_FAC_PRVDR_CPO_ORG_NPI_ID,
        CLM_FAC_PRVDR_NPI_NUM,
        CLM_OPRTG_PRVDR_NPI_NUM,
        CLM_OTHR_PRVDR_NPI_NUM,
        CLM_RFRG_PRVDR_NPI_NUM,
        CLM_RNDRG_PRVDR_NPI_NUM,
        PRVDR_RFRG_PRVDR_NPI_NUM,
        PRVDR_CPO_FAC_NPI_NUM,
        PRVDR_BLG_PRVDR_NPI_NUM,
        PRVDR_ATNDG_PRVDR_NPI_NUM,
        PRVDR_OPRTG_PRVDR_NPI_NUM,
        PRVDR_OTHR_PRVDR_NPI_NUM,
        PRVDR_RNDRNG_PRVDR_NPI_NUM,
        PRVDR_PRSCRBNG_PRVDR_NPI_NUM,
        PRVDR_SRVC_PRVDR_NPI_NUM,
        CLM_SRVC_PRVDR_NPI_NUM,
        CLM_ALTRNT_SRVC_PRVDR_NPI_NUM,
        CLM_PRSCRBNG_PRVDR_NPI_NUM,
        CLM_PCP_NPI_NUM
    FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM
    LIMIT 1000000
)
SELECT
    COUNT_IF(CLM_ATNDG_PRVDR_NPI_NUM IS NOT NULL AND CLM_ATNDG_PRVDR_NPI_NUM <> '~') AS count_CLM_ATNDG_PRVDR_NPI_NUM,
    COUNT_IF(CLM_BLG_PRVDR_NPI_NUM IS NOT NULL AND CLM_BLG_PRVDR_NPI_NUM <> '~') AS count_CLM_BLG_PRVDR_NPI_NUM,
    COUNT_IF(CLM_FAC_PRVDR_CPO_ORG_NPI_ID IS NOT NULL AND CLM_FAC_PRVDR_CPO_ORG_NPI_ID <> '~') AS count_CLM_FAC_PRVDR_CPO_ORG_NPI_ID,
    COUNT_IF(CLM_FAC_PRVDR_NPI_NUM IS NOT NULL AND CLM_FAC_PRVDR_NPI_NUM <> '~') AS count_CLM_FAC_PRVDR_NPI_NUM,
    COUNT_IF(CLM_OPRTG_PRVDR_NPI_NUM IS NOT NULL AND CLM_OPRTG_PRVDR_NPI_NUM <> '~') AS count_CLM_OPRTG_PRVDR_NPI_NUM,
    COUNT_IF(CLM_OTHR_PRVDR_NPI_NUM IS NOT NULL AND CLM_OTHR_PRVDR_NPI_NUM <> '~') AS count_CLM_OTHR_PRVDR_NPI_NUM,
    COUNT_IF(CLM_RFRG_PRVDR_NPI_NUM IS NOT NULL AND CLM_RFRG_PRVDR_NPI_NUM <> '~') AS count_CLM_RFRG_PRVDR_NPI_NUM,
    COUNT_IF(CLM_RNDRG_PRVDR_NPI_NUM IS NOT NULL AND CLM_RNDRG_PRVDR_NPI_NUM <> '~') AS count_CLM_RNDRG_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_RFRG_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_RFRG_PRVDR_NPI_NUM <> '~') AS count_PRVDR_RFRG_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_CPO_FAC_NPI_NUM IS NOT NULL AND PRVDR_CPO_FAC_NPI_NUM <> '~') AS count_PRVDR_CPO_FAC_NPI_NUM,
    COUNT_IF(PRVDR_BLG_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_BLG_PRVDR_NPI_NUM <> '~') AS count_PRVDR_BLG_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_ATNDG_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_ATNDG_PRVDR_NPI_NUM <> '~') AS count_PRVDR_ATNDG_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_OPRTG_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_OPRTG_PRVDR_NPI_NUM <> '~') AS count_PRVDR_OPRTG_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_OTHR_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_OTHR_PRVDR_NPI_NUM <> '~') AS count_PRVDR_OTHR_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_RNDRNG_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_RNDRNG_PRVDR_NPI_NUM <> '~') AS count_PRVDR_RNDRNG_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_PRSCRBNG_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_PRSCRBNG_PRVDR_NPI_NUM <> '~') AS count_PRVDR_PRSCRBNG_PRVDR_NPI_NUM,
    COUNT_IF(PRVDR_SRVC_PRVDR_NPI_NUM IS NOT NULL AND PRVDR_SRVC_PRVDR_NPI_NUM <> '~') AS count_PRVDR_SRVC_PRVDR_NPI_NUM,
    COUNT_IF(CLM_SRVC_PRVDR_NPI_NUM IS NOT NULL AND CLM_SRVC_PRVDR_NPI_NUM <> '~') AS count_CLM_SRVC_PRVDR_NPI_NUM,
    COUNT_IF(CLM_ALTRNT_SRVC_PRVDR_NPI_NUM IS NOT NULL AND CLM_ALTRNT_SRVC_PRVDR_NPI_NUM <> '~') AS count_CLM_ALTRNT_SRVC_PRVDR_NPI_NUM,
    COUNT_IF(CLM_PRSCRBNG_PRVDR_NPI_NUM IS NOT NULL AND CLM_PRSCRBNG_PRVDR_NPI_NUM <> '~') AS count_CLM_PRSCRBNG_PRVDR_NPI_NUM,
    COUNT_IF(CLM_PCP_NPI_NUM IS NOT NULL AND CLM_PCP_NPI_NUM <> '~') AS count_CLM_PCP_NPI_NUM
FROM sampled_claims;
