"""
==========
V2_PRVDR_ENMRT_TXNMY_CRNT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_TXNMY_CRNT

Table Type: VIEW
Columns: 8
Source Pattern: %prvdr_enmrt%
Table Comment: A TAXONOMY IDENTIFYING AN AREA OF SPECIALTY FOR A NATIONAL PROVIDER IDENTIFIER (NPI) ENUMERATED BY THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES).

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2PrvdrEnmrtTxnmyCrntExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2PrvdrEnmrtTxnmyCrntExporter(IDROutputter):
    """
    Exports V2_PRVDR_ENMRT_TXNMY_CRNT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_TXNMY_CRNT (VIEW)
    Columns: 8
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_prvdr_enmrt_txnmy_crnt_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_PRVDR_ENMRT_TXNMY_CRNT export.
        
        Includes all 8 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NPI_NUM, -- TEXT(10) | NOT NULL | A NATIONAL PROVIDER IDENTIFIER (NPI) UNIQUELY ASSIGNED FOR COVERED HEALTH CARE PROVIDERS.
                PRVDR_TXNMY_CD, -- TEXT(10) | NOT NULL | A UNIQUE IDENTIFIER FOR A CLASSIFICATION OF HEALTH CARE SPECIALTY AT A SPECIALIZED LEVEL OF DEFINED MEDICAL ACTIVITY WITHIN A MEDICAL FIELD AS CREATED BY THE NATIONAL UNIFORM CLAIM COMMITTEE (NUCC). THIS CLASSIFICATION CONCEPTUALLY DEVOLVES INTO THE FOLLOWING HIERARCHY: 1. A TOP LEVEL THAT INDICATES IF THE CLASSIFICATION IS INDIVIDUAL GROUP OF INDIVIDUALS OR NON-INDIVIDUAL 2. A MANDATORY SECOND LEVEL THAT SHOWS A BROAD BUT DEFINED MEDICAL FIELD. EXAMPLES FOR INDIVIDUALS INCLUDE: DENTAL PROVIDERS, ALLOPATHIC & OSTEOPATHIC PHYSICIANS EXAMPLES FOR NON-INDIVIDUALS INCLUDE: AGENCIES, HOSPITALS 3. A THIRD LEVEL THAT IS AT A MORE SPECIFIC LEVEL OF DEFINED MEDICAL ACTIVITY WITHIN A MEDICAL FIELD. EXAMPLES FOR INDIVIDUALS INCLUDE: DENTAL PROVIDERSDENTAL HYGIENIST, ALLOPATHIC & OSTEOPATHIC, PHYSICIANSANESTHESIOLOGY EXAMPLES FOR NON-INDIVIDUALS INCLUDE: AGENCIESHOME HEALTH AGENCY, HOSPITALSGENERAL ACUTE CARE HOSPITAL 4. A FOURTH SPECIALIZED LEVEL OF DEFINED MEDICAL ACTIVITY WITHIN A MEDICAL FIELD. EXAMPLES FOR INDIVIDUALS INCLUDE: ALLOPATHIC & OSTEOPATHIC PHYSICIANSANESTHESIOLOGYPAIN MEDICINE EXAMPLES FOR NON-INDIVIDUALS INCLUDE: HOSPITALSGENERAL ACUTE CARE HOSPITAL, ACUTE CARE HOSPITAL/CRITICAL ACCESS [ELDM] REFERENCE TABLE: V1_PRVDR_NCPDP_TXNMY_CD
                PRVDR_PRMRY_TXNMY_DSGNTN_CD, -- TEXT(1) | NOT NULL | A CODE INDICATING IF A TAXONOMY CODE IS THE PRIMARY TAXONOMY CODE. VALID VALUES: Y = YES, THE TAXONOMY IS THE PRIMARY TAXONOMY (THERE CAN BE ONLY ONE PER NPI RECORD) N = NO, THE TAXONOMY IS NOT THE PRIMARY TAXONOMY X = NOT ANSWERED
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                META_SRC_PRCSG_ID, -- NUMBER(38) | NOT NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS INSERTED.
                META_LTST_SRC_PRCSG_ID, -- NUMBER(38) | NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS SUBSEQUENTLY UPDATED.
                IDR_INSRT_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHILE PERFORMING AN INSERT OPERATION.
                IDR_UPDT_TS -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN UPDATES ARE MADE TO ANY NON-PRIMARY KEY COLUMN.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_TXNMY_CRNT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2PrvdrEnmrtTxnmyCrntExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
