"""
==========
V2_PRVDR_ENMRT_HSTRY IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_HSTRY

Table Type: VIEW
Columns: 30
Source Pattern: %prvdr_enmrt%
Table Comment: A LISTING OF HEALTH CARE PROVIDERS WHO HAVE BEEN ENUMERATED WITH AN NATIONAL PROVIDER IDENTIFIER (NPI) BY THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES).

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2PrvdrEnmrtHstryExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2PrvdrEnmrtHstryExporter(IDROutputter):
    """
    Exports V2_PRVDR_ENMRT_HSTRY data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_HSTRY (VIEW)
    Columns: 30
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_prvdr_enmrt_hstry_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_PRVDR_ENMRT_HSTRY export.
        
        Includes all 30 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NPI_NUM, -- TEXT(10) | NOT NULL | A NATIONAL PROVIDER IDENTIFIER (NPI) UNIQUELY ASSIGNED FOR COVERED HEALTH CARE PROVIDERS.
                IDR_TRANS_EFCTV_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) IDENTIFYING WHEN A RECORD IS LOADED.
                IDR_TRANS_OBSLT_TS, -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN A RECORD WAS LAST KNOWN TO BE PRESENT IN THE SOURCE. THE CURRENT VERSION OF A RECORD WILL BE SET TO 12/31/9999 00:00:00.
                IDR_LTST_TRANS_FLG, -- TEXT(1) | NOT NULL | AN INDICATOR ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) THAT IDENTIFIES WHICH TRANSACTION RECORD, BASED ON PRIMARY KEY, IS CONSIDERED TO REPRESENT THE MOST RECENT RECORD RECEIVED FROM THE SOURCE. Y = LATEST VERSION OF THE RECORD N = PREVIOUS VERSION OF THE RECORD
                PRVDR_CRTFCTN_DT, -- DATE | NULL | THE DATE THE PROVIDER CERTIFIED THAT ALL INFORMATION RELATED TO THE NATIONAL PROVIDER IDENTIFIER (NPI) RECORD IS ACCURATE AND UP-TO-DATE.
                PRVDR_ENT_TYPE_CD, -- TEXT(1) | NOT NULL | A CODE THAT IDENTIFIES THE PROVIDER'S BUSINESS STRUCTURE. VALID VALUES: '1' = INDIVIDUAL '2' = ORGANIZATION
                PRVDR_ENT_TYPE_DESC, -- TEXT(12) | NULL | DESCRIPTION OF THE ENTITY TYPE CODE. THE PROVIDER'S BUSINESS STRUCTURE IS EITHER AN INDIVIDUAL OR AN ORGANIZATION.
                PRVDR_RPLCMT_NPI_NUM, -- TEXT(10) | NULL | A REPLACEMENT NATIONAL PROVIDER IDENTIFIER (NPI) UNIQUELY ASSIGNED FOR A COVERED HEALTH CARE PROVIDER. THIS IS THE PROVIDER’S NPI IF THE PROVIDER HAS BEEN ASSIGNED A REPLACEMENT NPI. IF THE PROVIDER HAS NEVER BEEN ASSIGNED A REPLACEMENT NPI, THIS DATA ELEMENT WILL NOT BE POPULATED.
                PRVDR_SSN_NUM, -- TEXT(9) | NULL | A NUMBER ASSIGNED BY THE SOCIAL SECURITY ADMINISTRATION (SSA) USED TO IDENTIFY AN INDIVIDUAL.
                PRVDR_TIN_NUM, -- TEXT(9) | NULL | AN IDENTIFYING NUMBER USED FOR TAX PURPOSES IN THE UNITED STATES AND ASSIGNED BY THE INTERNAL REVENUE SERVICE (IRS). THE IRS ASSIGNS A TAX IDENTIFICATION NUMBER (TIN) TO INDIVIDUALS OR AN EMPLOYER IDENTIFICATION NUMBER (EIN) TO EMPLOYERS.
                PRVDR_EIN_NUM, -- TEXT(9) | NULL | AN IDENTIFYING NUMBER USED FOR TAX PURPOSES IN THE UNITED STATES AND ASSIGNED BY THE INTERNAL REVENUE SERVICE (IRS). THE IRS ASSIGNS A TAX IDENTIFICATION NUMBER (TIN) TO INDIVIDUALS OR AN EMPLOYER IDENTIFICATION NUMBER (EIN) TO EMPLOYERS.
                PRVDR_ENMRTN_DT, -- DATE | NOT NULL | THE DATE THE NATIONAL PROVIDER IDENTIFIER (NPI) WAS ASSIGNED.
                PRVDR_LAST_UPDT_DT, -- DATE | NOT NULL | A DATE INDICATING THE LAST TIME THE PROVIDER RECORD WAS UPDATED IN THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES).
                PRVDR_DEACTVTN_RSN_CD, -- TEXT(2) | NOT NULL | A CODE REPRESENTING THE REASON THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES) DEACTIVATED A PROVIDER RECORD. REFERENCE TABLE: PRVDR_DEACTVTN_RSN_CD
                PRVDR_DEACTVTN_RSN_DESC, -- TEXT(500) | NULL | A DESCRIPTION OF A CODE IDENTIFYING THE REASON THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES) DEACTIVATED A PROVIDER ENUMERATION RECORD.
                PRVDR_DEACTVTN_DT, -- DATE | NULL | A DATE INDICATING WHEN THE PROVIDER WAS DEACTIVATED.
                PRVDR_REACTVTN_DT, -- DATE | NULL | A DATE INDICATING WHEN THE PROVIDER WAS REACTIVATE.
                PRVDR_GNDR_CD, -- TEXT(1) | NOT NULL | AN IDENTIFIER DESCRIBING THE SEX OF THE PROVIDER. VALID VALUES: 'M' = MALE 'F' = FEMALE
                PRVDR_BIRTH_DT, -- DATE | NULL | A DATE OF BIRTH OF A PROVIDER.
                PRVDR_BIRTH_USPS_STATE_CD, -- TEXT(2) | NOT NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE STATE THE PROVIDER WAS BORN IN. REFERENCE TABLE: GEO_USPS_STATE_CD
                PRVDR_BIRTH_CNTRY_CD, -- TEXT(2) | NOT NULL | A TWO-CHARACTER ALPHABETIC ABBREVIATION OF THE COUNTRY WHERE THE HEALTH CARE PROVIDER WAS BORN. IT WILL ONLY BE POPULATED FOR INDIVIDUAL PROVIDERS (PROVIDER ENTITY TYPE CODE = 1). REFERENCE TABLE: GEO_CNTRY_CD
                PRVDR_SOLE_PRPRTR_CD, -- TEXT(1) | NOT NULL | A CODE INDICATING IF A TYPE 1 PROVIDER (INDIVIDUAL) IS THE SOLE PROPRIETOR. VALID VALUES: Y = YES, ENTITY TYPE 1 PROVIDER (INDIVIDUAL) IS A SOLE PROPRIETOR N = NO, ENTITY TYPE 1 PROVIDER (INDIVIDUAL) IS NOT A SOLE PROPRIETOR X = NOT ANSWERED
                PRVDR_ORG_SUBRDNT_CD, -- TEXT(1) | NOT NULL | A CODE IDENTIFYING IF A PROVIDER IS A SUBPART OF A HEALTH CARE ORGANIZATION (I.E., ENTITY TYPE 2). VALID VALUES: Y = YES, ENTITY TYPE 2 PROVIDER (ORGANIZATION) IS A SUBPART N = NO, ENTITY TYPE 2 PROVIDER (ORGANIZATION) IS NOT A SUBPART X = NOT ANSWERED
                PRVDR_PRNT_ORG_TIN_NUM, -- TEXT(9) | NULL | A UNIQUE TAX IDENTIFIER ASSIGNED TO A HEALTH CARE PROVIDER BY SOCIAL SECURITY ADMINISTRATION (SSA) OR THE INTERNAL REVENUE SERVICE (IRS).
                PRVDR_PRMRY_LANG_TXT, -- TEXT(100) | NULL | THE PRIMARY LANGUAGE OF AN ENUMERATED HEALTH CARE PROVIDER.
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                META_SRC_PRCSG_ID, -- NUMBER(38) | NOT NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS INSERTED.
                META_LTST_SRC_PRCSG_ID, -- NUMBER(38) | NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS SUBSEQUENTLY UPDATED.
                IDR_INSRT_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHILE PERFORMING AN INSERT OPERATION.
                IDR_UPDT_TS -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN UPDATES ARE MADE TO ANY NON-PRIMARY KEY COLUMN.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_HSTRY"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2PrvdrEnmrtHstryExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
