"""
==========
V2_PRVDR_ENMRT_ADR_HSTRY IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_ADR_HSTRY

Table Type: VIEW
Columns: 22
Source Pattern: %prvdr_enmrt%
Table Comment: A COMPILATION OF CONTACT INFORMATION USED TO LINK A NATIONAL PROVIDER IDENTIFIER (NPI) WITH THE ADDRESS LOCATION OF THE ENUMERATED PROVIDER.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2PrvdrEnmrtAdrHstryExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2PrvdrEnmrtAdrHstryExporter(IDROutputter):
    """
    Exports V2_PRVDR_ENMRT_ADR_HSTRY data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_ADR_HSTRY (VIEW)
    Columns: 22
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_prvdr_enmrt_adr_hstry_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_PRVDR_ENMRT_ADR_HSTRY export.
        
        Includes all 22 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NPI_NUM, -- TEXT(10) | NOT NULL | A NATIONAL PROVIDER IDENTIFIER (NPI) UNIQUELY ASSIGNED FOR COVERED HEALTH CARE PROVIDERS.
                ADR_TYPE_CD, -- TEXT(2) | NOT NULL | AN INTEGRATED DATA REPOSITORY (IDR) DERIVED CODE TO IDENTIFY THE PROVIDERS ADDRESS TYPE. REFERENCE TABLE: ADR_TYPE_CD
                ADR_TYPE_DESC, -- TEXT(500) | NULL | A DESCRIPTION OF A CODE IDENTIFYING AN ADDRESS TYPE.
                IDR_TRANS_EFCTV_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) IDENTIFYING WHEN A RECORD IS LOADED.
                IDR_TRANS_OBSLT_TS, -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN A RECORD WAS LAST KNOWN TO BE PRESENT IN THE SOURCE. THE CURRENT VERSION OF A RECORD WILL BE SET TO 12/31/9999 00:00:00.
                IDR_LTST_TRANS_FLG, -- TEXT(1) | NOT NULL | AN INDICATOR ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) THAT IDENTIFIES WHICH TRANSACTION RECORD, BASED ON PRIMARY KEY, IS CONSIDERED TO REPRESENT THE MOST RECENT RECORD RECEIVED FROM THE SOURCE. Y = LATEST VERSION OF THE RECORD N = PREVIOUS VERSION OF THE RECORD
                LINE_1_ADR, -- TEXT(55) | NULL | A FIRST LINE OF AN ADDRESS ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM.
                LINE_2_ADR, -- TEXT(55) | NULL | A SECOND LINE OF AN ADDRESS ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM. THIS ADDRESS LINE IS OPTIONAL AND USED TO INDICATE THE POST OFFICE BOX, SUITE NUMBER, APARTMENT NUMBER, ETC.
                ADR_CITY_NAME, -- TEXT(40) | NULL | A NAME OF THE CITY ASSOCIATED WITH A FIVE-DIGIT ZIP CODE DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS).
                GEO_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING A TWO-CHARACTER ALPHABETIC ABBREVIATION FOR A STATE DEFINED BY THE FEDERAL INFORMATION PROCESSING STANDARD (FIPS). REFERENCE TABLE: GEO_FIPS_STATE_CD
                ZIP5_CD, -- TEXT(5) | NULL
                ZIP4_CD, -- TEXT(4) | NULL
                GEO_SK, -- NUMBER(38) | NULL | A NUMERIC SURROGATE KEY THAT IS INDICATIVE OF A PARTICULAR GEOGRAPHICAL LOCATION.
                CNTRY_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING A COUNTRY ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AS ASSIGNED BY THE INTERNATIONAL ORGANIZATION FOR STANDARDIZATION (ISO). REFERENCE TABLE: GEO_CNTRY_CD
                PHNE_NUM, -- TEXT(20) | NULL | A NUMBER THAT REPRESENTS THE TELEPHONE NUMBER OF THE ENTITY OR PERSON.
                PHNE_EXTNSN_NUM, -- TEXT(5) | NULL | A 5 DIGIT NUMBER IN ADDITION TO THE TELEPHONE NUMBER OF THE ENTITY OR PERSON.
                FAX_NUM, -- TEXT(20) | NULL | A NUMBER THAT REPRESENTS THE FAX NUMBER OF THE ENTITY OR PERSON.
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                META_SRC_PRCSG_ID, -- NUMBER(38) | NOT NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS INSERTED.
                META_LTST_SRC_PRCSG_ID, -- NUMBER(38) | NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS SUBSEQUENTLY UPDATED.
                IDR_INSRT_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHILE PERFORMING AN INSERT OPERATION.
                IDR_UPDT_TS -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN UPDATES ARE MADE TO ANY NON-PRIMARY KEY COLUMN.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_ADR_HSTRY"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2PrvdrEnmrtAdrHstryExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
