"""
==========
V2_PRVDR_ENMRT_LCNS_MTRLZD_CRNT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_LCNS_MTRLZD_CRNT

Table Type: VIEW
Columns: 32
Source Pattern: %prvdr_enmrt%
Table Comment: A COMPILATION OF STATE LICENSE INFORMATION LINKED TO A NATIONAL PROVIDER IDENTIFIER (NPI), IDENTIFYING LICENSE NUMBER AND ISSUING STATE DATA.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2PrvdrEnmrtLcnsMtrlzdCrntExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2PrvdrEnmrtLcnsMtrlzdCrntExporter(IDROutputter):
    """
    Exports V2_PRVDR_ENMRT_LCNS_MTRLZD_CRNT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_LCNS_MTRLZD_CRNT (VIEW)
    Columns: 32
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_prvdr_enmrt_lcns_mtrlzd_crnt_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_PRVDR_ENMRT_LCNS_MTRLZD_CRNT export.
        
        Includes all 32 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NPI_NUM, -- TEXT(10) | NOT NULL | A NATIONAL PROVIDER IDENTIFIER (NPI) UNIQUELY ASSIGNED FOR COVERED HEALTH CARE PROVIDERS.
                PRVDR_LCNS_1_NUM, -- TEXT(16777216) | NULL | A NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_1_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE LICENSE NUMBER.
                PRVDR_LCNS_2_NUM, -- TEXT(16777216) | NULL | A SECOND NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_2_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE SECOND LICENSE NUMBER.
                PRVDR_LCNS_3_NUM, -- TEXT(16777216) | NULL | A THIRD NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_3_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE THIRD LICENSE NUMBER.
                PRVDR_LCNS_4_NUM, -- TEXT(16777216) | NULL | A FOURTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_4_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE FOURTH LICENSE NUMBER.
                PRVDR_LCNS_5_NUM, -- TEXT(16777216) | NULL | A FIFTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_5_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE FIFTH LICENSE NUMBER.
                PRVDR_LCNS_6_NUM, -- TEXT(16777216) | NULL | A SIXTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_6_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE SIXTH LICENSE NUMBER.
                PRVDR_LCNS_7_NUM, -- TEXT(16777216) | NULL | A SEVENTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_7_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE SEVENTH LICENSE NUMBER.
                PRVDR_LCNS_8_NUM, -- TEXT(16777216) | NULL | AN EIGTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_8_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE EIGTH LICENSE NUMBER.
                PRVDR_LCNS_9_NUM, -- TEXT(16777216) | NULL | A NINTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_9_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE NINTH LICENSE NUMBER.
                PRVDR_LCNS_10_NUM, -- TEXT(16777216) | NULL | A TENTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_10_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE TENTH LICENSE NUMBER.
                PRVDR_LCNS_11_NUM, -- TEXT(16777216) | NULL | AN EVELENTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_11_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE EVELENTH LICENSE NUMBER.
                PRVDR_LCNS_12_NUM, -- TEXT(16777216) | NULL | A TWELFTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_12_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE TWELFTH LICENSE NUMBER.
                PRVDR_LCNS_13_NUM, -- TEXT(16777216) | NULL | A THIRTEENTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_13_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE THIRTEENTH LICENSE NUMBER.
                PRVDR_LCNS_14_NUM, -- TEXT(16777216) | NULL | A FOURTEENTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_14_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE FOURTEENTH LICENSE NUMBER.
                PRVDR_LCNS_15_NUM, -- TEXT(16777216) | NULL | A FIFTEENTH NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZ
                PRVDR_LCNS_15_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE ISSUING STATE OF THE FIFTEENTH LICENSE NUMBER.
                META_SRC_SK -- NUMBER(38) | NOT NULL
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_LCNS_MTRLZD_CRNT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2PrvdrEnmrtLcnsMtrlzdCrntExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
