"""
==========
V2_PRVDR_ENMRT_DMGRPHCS_CRNT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_DMGRPHCS_CRNT

Table Type: VIEW
Columns: 51
Source Pattern: %prvdr_enmrt%
Table Comment: A COMPILATION OF VARIOUS INFORMATION ABOUT THE ENUMERATED PROVIDER.  INCLUDES TAX ID'S, ADDRESS AND PHONE INFO,  AND OTHER DEMOGRAPHIC INFO SUCH AS BIRTH DATE, SEX. ALSO INCLUDES DEACTIVATION/REACTIVATION DATES AND REASONS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2PrvdrEnmrtDmgrphcsCrntExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2PrvdrEnmrtDmgrphcsCrntExporter(IDROutputter):
    """
    Exports V2_PRVDR_ENMRT_DMGRPHCS_CRNT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_DMGRPHCS_CRNT (VIEW)
    Columns: 51
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_prvdr_enmrt_dmgrphcs_crnt_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_PRVDR_ENMRT_DMGRPHCS_CRNT export.
        
        Includes all 51 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NPI_NUM, -- TEXT(10) | NOT NULL | A NATIONAL PROVIDER IDENTIFIER (NPI) UNIQUELY ASSIGNED FOR COVERED HEALTH CARE PROVIDERS.
                PRVDR_ENT_TYPE_CD, -- TEXT(1) | NOT NULL | A CODE THAT IDENTIFIES THE PROVIDER'S BUSINESS STRUCTURE. VALID VALUES: '1' = INDIVIDUAL '2' = ORGANIZATION
                PRVDR_ENT_TYPE_DESC, -- TEXT(12) | NULL | DESCRIPTION OF THE ENTITY TYPE CODE. THE PROVIDER'S BUSINESS STRUCTURE IS EITHER AN INDIVIDUAL OR AN ORGANIZATION.
                PRVDR_CRTFCTN_DT, -- DATE | NULL | THE DATE THE PROVIDER CERTIFIED THAT ALL INFORMATION RELATED TO THE NATIONAL PROVIDER IDENTIFIER (NPI) RECORD IS ACCURATE AND UP-TO-DATE.
                PRVDR_RPLCMT_NPI_NUM, -- TEXT(10) | NULL | A REPLACEMENT NATIONAL PROVIDER IDENTIFIER (NPI) UNIQUELY ASSIGNED FOR A COVERED HEALTH CARE PROVIDER. THIS IS THE PROVIDER’S NPI IF THE PROVIDER HAS BEEN ASSIGNED A REPLACEMENT NPI. IF THE PROVIDER HAS NEVER BEEN ASSIGNED A REPLACEMENT NPI, THIS DATA ELEMENT WILL NOT BE POPULATED.
                PRVDR_SSN_NUM, -- TEXT(9) | NULL | A NUMBER ASSIGNED BY THE SOCIAL SECURITY ADMINISTRATION (SSA) USED TO IDENTIFY AN INDIVIDUAL.
                PRVDR_TIN_NUM, -- TEXT(9) | NULL | AN IDENTIFYING NUMBER USED FOR TAX PURPOSES IN THE UNITED STATES AND ASSIGNED BY THE INTERNAL REVENUE SERVICE (IRS). THE IRS ASSIGNS A TAX IDENTIFICATION NUMBER (TIN) TO INDIVIDUALS OR AN EMPLOYER IDENTIFICATION NUMBER (EIN) TO EMPLOYERS.
                PRVDR_EIN_NUM, -- TEXT(9) | NULL | AN IDENTIFYING NUMBER USED FOR TAX PURPOSES IN THE UNITED STATES AND ASSIGNED BY THE INTERNAL REVENUE SERVICE (IRS). THE IRS ASSIGNS A TAX IDENTIFICATION NUMBER (TIN) TO INDIVIDUALS OR AN EMPLOYER IDENTIFICATION NUMBER (EIN) TO EMPLOYERS.
                PRVDR_ENMRTN_DT, -- DATE | NOT NULL | THE DATE THE NATIONAL PROVIDER IDENTIFIER (NPI) WAS ASSIGNED.
                PRVDR_LAST_UPDT_DT, -- DATE | NOT NULL | A DATE INDICATING THE LAST TIME THE PROVIDER RECORD WAS UPDATED IN THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES).
                PRVDR_DEACTVTN_RSN_CD, -- TEXT(2) | NOT NULL | A CODE REPRESENTING THE REASON THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES) DEACTIVATED A PROVIDER RECORD. REFERENCE TABLE: PRVDR_DEACTVTN_RSN_CD
                PRVDR_DEACTVTN_RSN_DESC, -- TEXT(500) | NULL | A DESCRIPTION OF A CODE IDENTIFYING THE REASON THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES) DEACTIVATED A PROVIDER ENUMERATION RECORD.
                PRVDR_DEACTVTN_DT, -- DATE | NULL | A DATE INDICATING WHEN THE PROVIDER WAS DEACTIVATED.
                PRVDR_REACTVTN_DT, -- DATE | NULL | A DATE INDICATING WHEN THE PROVIDER WAS REACTIVATE.
                PRVDR_GNDR_CD, -- TEXT(1) | NOT NULL | AN IDENTIFIER DESCRIBING THE SEX OF THE PROVIDER. VALID VALUES: 'M' = MALE 'F' = FEMALE
                PRVDR_BIRTH_DT, -- DATE | NULL | A DATE OF BIRTH OF A PROVIDER.
                PRVDR_BIRTH_USPS_STATE_CD, -- TEXT(2) | NOT NULL | A CODE IDENTIFYING THE TWO-CHARACTER UNITED STATES POSTAL SERVICE (USPS) ALPHABETIC ABBREVIATION FOR THE STATE THE PROVIDER WAS BORN IN. REFERENCE TABLE: GEO_USPS_STATE_CD
                PRVDR_BIRTH_CNTRY_CD, -- TEXT(2) | NOT NULL | A TWO-CHARACTER ALPHABETIC ABBREVIATION OF THE COUNTRY WHERE THE HEALTH CARE PROVIDER WAS BORN. IT WILL ONLY BE POPULATED FOR INDIVIDUAL PROVIDERS (PROVIDER ENTITY TYPE CODE = 1). REFERENCE TABLE: GEO_CNTRY_CD
                PRVDR_SOLE_PRPRTR_CD, -- TEXT(1) | NOT NULL | A CODE INDICATING IF A TYPE 1 PROVIDER (INDIVIDUAL) IS THE SOLE PROPRIETOR. VALID VALUES: Y = YES, ENTITY TYPE 1 PROVIDER (INDIVIDUAL) IS A SOLE PROPRIETOR N = NO, ENTITY TYPE 1 PROVIDER (INDIVIDUAL) IS NOT A SOLE PROPRIETOR X = NOT ANSWERED
                PRVDR_ORG_SUBRDNT_CD, -- TEXT(1) | NOT NULL | A CODE IDENTIFYING IF A PROVIDER IS A SUBPART OF A HEALTH CARE ORGANIZATION (I.E., ENTITY TYPE 2). VALID VALUES: Y = YES, ENTITY TYPE 2 PROVIDER (ORGANIZATION) IS A SUBPART N = NO, ENTITY TYPE 2 PROVIDER (ORGANIZATION) IS NOT A SUBPART X = NOT ANSWERED
                PRVDR_PRNT_ORG_TIN_NUM, -- TEXT(9) | NULL | A UNIQUE TAX IDENTIFIER ASSIGNED TO A HEALTH CARE PROVIDER BY SOCIAL SECURITY ADMINISTRATION (SSA) OR THE INTERNAL REVENUE SERVICE (IRS).
                PRVDR_PRMRY_LANG_TXT, -- TEXT(100) | NULL | THE PRIMARY LANGUAGE OF AN ENUMERATED HEALTH CARE PROVIDER.
                PRVDR_PREX_NAME, -- TEXT(20) | NULL | PROVIDER NAME PREFIX TEXT;PROVIDER OTHER NAME PREFIX TEXT;AUTHORIZED OFFICIAL NAME PREFIX TEXT;CONTACT PERSON NAME PREFIX TEXT
                PRVDR_1ST_NAME, -- TEXT(35) | NULL | A FIRST NAME OF A PROVIDER.
                PRVDR_MDL_NAME, -- TEXT(20) | NULL | AN OFFICIAL NAME UNDER WHICH A BUSINESS OPERATES AND HOLDS ITSELF OUT TO THE PUBLIC.
                PRVDR_LAST_NAME, -- TEXT(35) | NULL | A SURNAME OF THE INDIVIDUAL.
                PRVDR_SFX_NAME, -- TEXT(20) | NULL | AN IDENTIFIER OF A PHRASE AT THE END OF A NAME THAT FURTHER DESCRIBES AN INDIVIDUAL, E.G.'JR', 'SR', ETC.
                ORG_NAME, -- TEXT(100) | NULL | AN OFFICIAL NAME UNDER WHICH A BUSINESS OPERATES AND HOLDS ITSELF OUT TO THE PUBLIC.
                MLG_LINE_1_ADR, -- TEXT(55) | NULL | A FIRST LINE OF AN ADDRESS ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM.
                MLG_LINE_2_ADR, -- TEXT(55) | NULL | A SECOND LINE OF AN ADDRESS ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM. THIS ADDRESS LINE IS OPTIONAL AND USED TO INDICATE THE POST OFFICE BOX, SUITE NUMBER, APARTMENT NUMBER, ETC.
                MLG_ADR_CITY_NAME, -- TEXT(40) | NULL | A NAME OF THE CITY ASSOCIATED WITH A FIVE-DIGIT ZIP CODE DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS).
                MLG_GEO_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING A TWO-CHARACTER ALPHABETIC ABBREVIATION FOR A STATE IN THE UNITED STATES AS DEFINED BY UNITED STATES POSTAL SERVICE (USPS) ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS. REFERENCE TABLE: GEO_USPS_STATE_CD
                MLG_GEO_ZIP5_CD, -- TEXT(5) | NULL | A FIVE-DIGIT ZIP CODE DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT IDENTIFIES A DESTINATION POST OFFICE OR DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS. REFERENCE TABLE: GEO_ZIP5_CD
                MLG_GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS. REFERENCE TABLE: GEO_ZIP9_CD
                GEO_MLG_SK, -- NUMBER(38) | NULL | A NUMERIC SURROGATE KEY THAT IS INDICATIVE OF A PARTICULAR GEOGRAPHICAL LOCATION.
                MLG_CNTRY_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING A COUNTRY ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AS ASSIGNED BY THE INTERNATIONAL ORGANIZATION FOR STANDARDIZATION (ISO). REFERENCE TABLE: GEO_CNTRY_CD
                MLG_PHNE_NUM, -- TEXT(16777216) | NULL | A NUMBER THAT REPRESENTS THE TELEPHONE NUMBER OF THE ENTITY OR PERSON.
                MLG_PHNE_EXTNSN_NUM, -- TEXT(16777216) | NULL | A NUMBER IN ADDITION TO THE TELEPHONE NUMBER OF THE ENTITY OR PERSON.
                MLG_FAX_NUM, -- TEXT(16777216) | NULL | THE FACSIMILE MACHINE TELEPHONE LINE NUMBER.
                PRCTC_LINE_1_ADR, -- TEXT(55) | NULL | A NUMBER AND STREET NAME IDENTIFYING WHERE THE ORGANIZATION IS LOCATED.
                PRCTC_LINE_2_ADR, -- TEXT(55) | NULL | AN ADDITIONAL ADDRESS LINE IDENTIFYING WHERE THE ORGANIZATION IS LOCATED. THIS ADDRESS LINE IS OPTIONAL AND USED TO INDICATE THE POST OFFICE BOX, SUITE NUMBER, APARTMENT NUMBER, ETC.
                PRCTC_ADR_CITY_NAME, -- TEXT(40) | NULL | A NAME OF THE CITY ASSOCIATED WITH A FIVE-DIGIT ZIP CODE DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS).
                PRCTC_GEO_USPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING A TWO-CHARACTER ALPHABETIC ABBREVIATION FOR A STATE IN THE UNITED STATES AS DEFINED BY UNITED STATES POSTAL SERVICE (USPS) ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS. REFERENCE TABLE: GEO_USPS_STATE_CD
                PRCTC_GEO_ZIP5_CD, -- TEXT(5) | NULL | A FIVE-DIGIT ZIP CODE DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT IDENTIFIES THE DESTINATION POST OFFICE OR DELIVERY AREA.
                PRCTC_GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                GEO_PRCTC_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                PRCTC_CNTRY_CD, -- TEXT(2) | NULL | A TWO-CHARACTER ALPHABETIC ABBREVIATION OF THE COUNTRY ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS. REFERENCE TABLE: TBD
                PRCTC_PHNE_NUM, -- TEXT(16777216) | NULL | A NUMBER THAT REPRESENTS THE TELEPHONE NUMBER OF THE ENTITY OR PERSON.
                PRCTC_PHNE_EXTNSN_NUM, -- TEXT(16777216) | NULL | A NUMBER IN ADDITION TO THE TELEPHONE NUMBER OF THE ENTITY OR PERSON.
                PRCTC_FAX_NUM, -- TEXT(16777216) | NULL | THE FACSIMILE MACHINE TELEPHONE LINE NUMBER.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_PRVDR_ENMRT_DMGRPHCS_CRNT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2PrvdrEnmrtDmgrphcsCrntExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
