#!/usr/bin/env python3
"""
IDR Extract Scripts Generator
=============================

This CLI script reads a JSON metadata file (generated by make_json_from_table_match.py)
and creates individual .py files containing IDROutputter subclasses for each table/view.

Each generated script contains:
- A complete IDROutputter subclass implementation
- SELECT query with all columns in Snowflake order
- Proper class and file naming conventions
- Ready-to-run or customizable implementation

Usage:
    python make_extract_scripts_from_json.py metadata.json output_directory/
    
Requirements:
    - JSON metadata file from make_json_from_table_match.py
    - Output directory (will be created if it doesn't exist)
    
Generated Files:
    - One .py file per table/view
    - File names: {table_name_lower}_export.py
    - Class names: {TableNameCamelCase}Exporter
"""

import json
import argparse
import os
from typing import Dict, List, Any
from datetime import datetime
from asset_template import generate_idr_outputter_script


def convert_to_camel_case(snake_str: str) -> str:
    """Convert snake_case or UPPER_CASE to CamelCase for class names."""
    if not snake_str:
        return ""
    components = snake_str.lower().split('_')
    return ''.join(word.capitalize() for word in components if word)


def convert_to_snake_case(input_str: str) -> str:
    """Convert string to snake_case for file naming."""
    return input_str.lower()


def generate_select_query(*, table_info: Dict[str, Any]) -> str:
    """Generate SELECT query string with all columns in Snowflake order."""
    database = table_info["database"]
    schema = table_info["schema"] 
    table_name = table_info["table_name"]
    columns = table_info["columns"]
    
    # Sort columns by ordinal_position to maintain Snowflake order
    sorted_columns = sorted(columns, key=lambda x: x["ordinal_position"])
    
    # Create column list with proper indentation and comments
    column_lines = []
    for i, col in enumerate(sorted_columns):
        column_name = col["column_name"]
        comma = "," if i < len(sorted_columns) - 1 else ""
        
        # Build the comment with type and description
        comment_parts = []
        
        if col.get("type_description"):
            comment_parts.append(col["type_description"])
        elif col.get("data_type"):
            comment_parts.append(col["data_type"])
        
        # Add nullable information
        if col.get("is_nullable"):
            nullable_str = "NULL" if col["is_nullable"] == "YES" else "NOT NULL"
            comment_parts.append(nullable_str)
        
        # Add default value if present
        if col.get("column_default") is not None:
            default_val = col["column_default"]
            comment_parts.append(f"DEFAULT: {default_val}")
        
        if col.get("comment"):
            sanitized_comment = col["comment"].replace('\n', ' ').replace('\r', ' ')
            sanitized_comment = ' '.join(sanitized_comment.split())
            if sanitized_comment:
                comment_parts.append(sanitized_comment)
        
        comment = " -- " + " | ".join(comment_parts) if comment_parts else ""
        column_lines.append(f"                {column_name}{comma}{comment}")
    
    columns_str = "\n".join(column_lines)
    
    return f"""SELECT
{columns_str}
            FROM {database}.{schema}.{table_name}"""


def generate_script_content(*, table_info: Dict[str, Any], metadata_info: Dict[str, Any], table_comment: str = None) -> str:
    """Generate complete .py script content using the asset template."""
    # Build template values dictionary
    template_values = {
        'table_name': table_info["table_name"],
        'database': table_info["database"],
        'schema': table_info["schema"],
        'table_type': table_info["table_type"],
        'column_count': len(table_info["columns"]),
        'original_pattern': metadata_info.get("search_pattern", "Unknown"),
        'class_name': convert_to_camel_case(table_info["table_name"]) + "Exporter",
        'file_name_stub': convert_to_snake_case(table_info["table_name"]) + "_idr_export",
        'select_query': generate_select_query(table_info=table_info),
    }
    
    # Add table comment if provided
    if table_comment:
        template_values['table_comment'] = table_comment
    
    # Use the template to generate the script
    return generate_idr_outputter_script(template_values)


def load_metadata_json(*, json_file_path: str) -> Dict[str, Any]:
    """Load and validate JSON metadata file."""
    try:
        with open(json_file_path, 'r') as f:
            metadata = json.load(f)
        
        if "metadata" not in metadata:
            raise ValueError("JSON file missing 'metadata' section")
        if "tables" not in metadata:
            raise ValueError("JSON file missing 'tables' section")
        
        print(f"Loaded metadata for {len(metadata['tables'])} tables/views")
        return metadata
        
    except FileNotFoundError:
        print(f"Error: JSON file not found: {json_file_path}")
        raise
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON format: {str(e)}")
        raise


def create_output_directory(*, output_dir: str) -> None:
    """Create output directory if it doesn't exist."""
    os.makedirs(output_dir, exist_ok=True)
    print(f"Output directory ready: {output_dir}")


def generate_all_scripts(*, metadata: Dict[str, Any], output_dir: str) -> None:
    """Generate all IDROutputter scripts from metadata."""
    tables = metadata["tables"]
    metadata_info = metadata["metadata"]
    table_comments = metadata.get("table_comments", {})
    
    if not tables:
        print("No tables found in metadata - no scripts to generate")
        return
    
    print(f"Generating {len(tables)} IDROutputter scripts...")
    if table_comments:
        print(f"Found {len(table_comments)} table comments")
    
    generated_files = []
    
    for table_info in tables:
        table_name = table_info["table_name"]
        database = table_info["database"]
        schema = table_info["schema"]
        
        # Get table comment if available
        full_table_name = f"{database}.{schema}.{table_name}"
        table_comment = table_comments.get(full_table_name)
        
        # Generate file name
        file_name = convert_to_snake_case(table_name) + "_export.py"
        file_path = os.path.join(output_dir, file_name)
        
        # Generate script content
        try:
            script_content = generate_script_content(
                table_info=table_info, 
                metadata_info=metadata_info,
                table_comment=table_comment
            )
            
            # Write script file
            with open(file_path, 'w') as f:
                f.write(script_content)
            
            generated_files.append({
                "file_name": file_name,
                "file_path": file_path,
                "table_name": table_name,
                "database": database,
                "schema": schema,
                "column_count": len(table_info["columns"])
            })
            
            print(f"Generated: {file_name} ({len(table_info['columns'])} columns)")
            
        except Exception as e:
            print(f"Error: Failed to generate script for {table_name}: {str(e)}")
            continue
    
    # Print summary
    print(f"\nGENERATION COMPLETE")
    print(f"==================")
    print(f"Scripts generated: {len(generated_files)}")
    print(f"Output directory: {output_dir}")
    print(f"Source metadata: {metadata_info.get('search_pattern', 'Unknown pattern')}")
    print(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    if generated_files:
        print(f"\nGenerated Files:")
        total_columns = 0
        for file_info in generated_files:
            print(f"  - {file_info['file_name']} ({file_info['column_count']} columns)")
            print(f"    Source: {file_info['database']}.{file_info['schema']}.{file_info['table_name']}")
            total_columns += file_info['column_count']
        
        print(f"\nTotal columns across all tables: {total_columns}")


def main():
    """Main function for CLI usage"""
    parser = argparse.ArgumentParser(
        description="Generate IDROutputter scripts from JSON metadata",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python make_extract_scripts_from_json.py provider_metadata.json ./generated_scripts/
    python make_extract_scripts_from_json.py medicaid_tables.json ~/idr_exports/
        """
    )
    
    parser.add_argument('json_file', help="Path to JSON metadata file")
    parser.add_argument('output_directory', help="Directory to write generated .py scripts")
    
    args = parser.parse_args()
    
    print("IDR Extract Scripts Generator")
    print("=============================")
    print(f"JSON File: {args.json_file}")
    print(f"Output Directory: {args.output_directory}")
    print("")
    
    try:
        metadata = load_metadata_json(json_file_path=args.json_file)
        create_output_directory(output_dir=args.output_directory)
        generate_all_scripts(metadata=metadata, output_dir=args.output_directory)
        print(f"\nSuccess! All scripts generated successfully.")
        
    except Exception as e:
        print(f"\nFailed to generate scripts: {str(e)}")
        exit(1)


if __name__ == '__main__':
    main()
