Reading metadata from: /Users/tgda/gitgov/DSACMS/npd_etl/dw_notebook_integrations/misc_scripts/gen_extract_scripts/json_documentation_cache/mdcr_prvdr_columns.json
Found 157 tables in metadata
Found 157 table comments
Analyzing for entity-related columns...

✓ V2_MDCR_PRVDR: 2 relevant columns
⊘ V2_MDCR_PRVDR_ACRDTN: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_ACRDTN_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_ADVRS_ACTN: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_ADVRS_ACTN_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_AMBLNC: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_AMBLNC_AUDT: 2 relevant columns (skipping - only link columns)
✓ V2_MDCR_PRVDR_BLG_AGNCY: 3 relevant columns
✓ V2_MDCR_PRVDR_BLG_AGNCY_AUDT: 3 relevant columns
✓ V2_MDCR_PRVDR_CHAIN: 3 relevant columns
✓ V2_MDCR_PRVDR_CHAIN_AUDT: 3 relevant columns
⊘ V2_MDCR_PRVDR_CRDNTL: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_CRDNTL_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_CRTFCTN_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_CRTFCTN_STMT: 2 relevant columns (skipping - only link columns)
✓ V2_MDCR_PRVDR_DMEPOS_INDVDL: 1 relevant columns
✓ V2_MDCR_PRVDR_EMPLR: 3 relevant columns
✓ V2_MDCR_PRVDR_EMPLR_AUDT: 3 relevant columns
✓ V2_MDCR_PRVDR_ENRLMT: 3 relevant columns
✓ V2_MDCR_PRVDR_ENRLMT_AUDT: 3 relevant columns
✓ V2_MDCR_PRVDR_ENRLMT_HSTRY: 3 relevant columns
✓ V2_MDCR_PRVDR_ENRLMT_STUS: 1 relevant columns
✓ V2_MDCR_PRVDR_ENRLMT_STUS_AUDT: 1 relevant columns
✓ V2_MDCR_PRVDR_HCIDEA_NPI: 1 relevant columns
✓ V2_MDCR_PRVDR_HHA: 3 relevant columns
✓ V2_MDCR_PRVDR_HHA_AUDT: 3 relevant columns
⊘ V2_MDCR_PRVDR_HOSP: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_HOSP_AUDT: 2 relevant columns (skipping - only link columns)
✓ V2_MDCR_PRVDR_HSTRY: 2 relevant columns
⊘ V2_MDCR_PRVDR_IDTF_ATSTTN: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_IDTF_ATSTTN_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_IDTF_EQUIP: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_IDTF_EQUIP_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_IDTF_HCPCS: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_IDTF_HCPCS_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_IDTF_TCHNCN: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_IDTF_TCHNCN_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_INTRPTNG_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_INTRPTNG_PHYSN: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_LCNS: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_LCNS_AUDT: 2 relevant columns (skipping - only link columns)
✓ V2_MDCR_PRVDR_MDCR_ID: 3 relevant columns
✓ V2_MDCR_PRVDR_MDCR_ID_AUDT: 3 relevant columns
✓ V2_MDCR_PRVDR_MMBR: 4 relevant columns
✓ V2_MDCR_PRVDR_MMBR_AUDT: 4 relevant columns
✓ V2_MDCR_PRVDR_NCPDP: 1 relevant columns
✓ V2_MDCR_PRVDR_NCPDP_HSTRY: 1 relevant columns
✓ V2_MDCR_PRVDR_NCPDP_PRNT_ORG: 1 relevant columns
✓ V2_MDCR_PRVDR_NCPDP_PYMT_CNTR: 1 relevant columns
✓ V2_MDCR_PRVDR_NCPDP_REMIT: 1 relevant columns
✓ V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC: 1 relevant columns
✓ V2_MDCR_PRVDR_NON_DLVRBL_AUDT: 1 relevant columns
✓ V2_MDCR_PRVDR_NPI_DMEPOS_GRP: 1 relevant columns
✓ V2_MDCR_PRVDR_NPI_PIN_GRP: 1 relevant columns
✓ V2_MDCR_PRVDR_NPI_PIN_INDVDL: 1 relevant columns
✓ V2_MDCR_PRVDR_OWNRSHP: 3 relevant columns
✓ V2_MDCR_PRVDR_OWNRSHP_AUDT: 3 relevant columns
✓ V2_MDCR_PRVDR_PBX: 2 relevant columns
✓ V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK: 2 relevant columns
✓ V2_MDCR_PRVDR_PRCTC_LCTN: 3 relevant columns
✓ V2_MDCR_PRVDR_PRCTC_LCTN_AUDT: 3 relevant columns
⊘ V2_MDCR_PRVDR_PRTCPNT_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_PRTCPNT_STUS: 2 relevant columns (skipping - only link columns)
✓ V2_MDCR_PRVDR_PSF: 1 relevant columns
✓ V2_MDCR_PRVDR_REASGNMT: 5 relevant columns
✓ V2_MDCR_PRVDR_REASGNMT_AUDT: 5 relevant columns
⊘ V2_MDCR_PRVDR_REC_LCTN: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_REC_LCTN_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SBUNIT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SBUNIT_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SPCLTY_TYPE: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SPCLTY_TYPE_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SPCL_PMT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SPCL_PMT_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SPRVSNG_AUDT: 2 relevant columns (skipping - only link columns)
⊘ V2_MDCR_PRVDR_SPRVSNG_PHYSN: 2 relevant columns (skipping - only link columns)

============================================================
ANALYSIS SUMMARY
============================================================
Total tables analyzed:           157
Tables with relevant columns:    40
Total relevant columns found:    92

Columns by Category:
  enrollment          :   28
  pac_id              :   25
  tin                 :   21
  npi                 :   18
============================================================

-- ========================================
-- Entity Column Extraction
-- ========================================
-- Generated from Medicare Provider metadata
-- Source: /Users/tgda/gitgov/DSACMS/npd_etl/dw_notebook_integrations/misc_scripts/gen_extract_scripts/json_documentation_cache/mdcr_prvdr_columns.json
-- 
-- Focus Areas:
--   * TINs (EIN, SSN, ITIN)
--   * PECOS Associate Control ID (PAC ID)
--   * Enrollment Numbers
--   * NPIs (National Provider Identifier)
--   * Part B Assignment
-- ========================================


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR
-- Type: VIEW
-- Relevant Columns: 2 of 42
-- Table Comment: BUSINESS PARTIES ENGAGED IN ACTIVITIES RELATED TO CMS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR (
    PRVDR_NPI_NUM TEXT(10),
    -- PRVDR_NPI_NUM: THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER. [NPS]
    -- Categories: npi
    PRVDR_EMPLR_ID_NUM TEXT(10)
    -- PRVDR_EMPLR_ID_NUM: THE PROVIDERS EMPLOYER ID NUMBER (EMPLOYER IDENTIFICATION NUMBER  (EIN), SOCIAL SECURITY NUMBER (SSN...
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR.PRVDR_NPI_NUM IS 'THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER. [NPS]';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR.PRVDR_EMPLR_ID_NUM IS 'THE PROVIDERS EMPLOYER ID NUMBER (EMPLOYER IDENTIFICATION NUMBER  (EIN), SOCIAL SECURITY NUMBER (SSN) OR INDIVIDUAL TAX IDENTIFICATION NUMBER (ITIN))';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY
-- Type: VIEW
-- Relevant Columns: 3 of 28
-- Table Comment: THE BILLING AGENCY CHILD RECORD IS CREATED TO COLLECT INFORMATION ABOUT AN ORGANIZATION OR AN INDIVIDUAL THAT ACTS AS A BILLING AGENCY FOR THE ENTITY IDENTIFIED IN THE ENROLLMENT BASE RECORD. ALL OF THE INFORMATION IN THE RECORD CAN APPLY TO EITHER AN ORGANIZATION OR AN INDIVIDUAL, EXCEPT FOR THE ORGANIZATION/INDIVIDUAL SPECIFIC FIELDS AT THE BEGINNING OF THE RECORD.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY (
    PRVDR_BLG_TIN_NUM TEXT(9),
    -- PRVDR_BLG_TIN_NUM: TAX ID NUMBER
    -- Categories: tin
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY.PRVDR_BLG_TIN_NUM IS 'TAX ID NUMBER';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 30
-- Table Comment: AN AUDIT OF THE PROVIDER BILLING AGENCY INFORMATION
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
    PRVDR_BLG_TIN_NUM TEXT(9)
    -- PRVDR_BLG_TIN_NUM: TAX ID NUMBER
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_BLG_AGNCY_AUDT.PRVDR_BLG_TIN_NUM IS 'TAX ID NUMBER';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN
-- Type: VIEW
-- Relevant Columns: 3 of 26
-- Table Comment: THE CHAIN HOME OFFICE CHILD RECORD IS CREATED WHEN THE END USER ENTERS INFORMATION IN SECTION 7 OF AN 855A ENROLLMENT RECORD. FOR A CHAIN THAT IS NOT ASSOCIATED TO AN ENROLLMENT, THE ENROLLMENT BASE RECORD WILL NOT BE POPULATED EXCEPT FOR THE CODE INDICATING TYPE OF CHILD.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN (
    PRVDR_CHAIN_TIN_NUM TEXT(9),
    -- PRVDR_CHAIN_TIN_NUM: IRS TAX IDENTIFICATION NUMBER OF A PECOS ASSOCIATE.
    -- Categories: tin
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN.PRVDR_CHAIN_TIN_NUM IS 'IRS TAX IDENTIFICATION NUMBER OF A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 28
-- Table Comment: AN AUDIT OF THE PROVIDER CHAIN INFORMATION
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
    PRVDR_CHAIN_TIN_NUM TEXT(9)
    -- PRVDR_CHAIN_TIN_NUM: TAX ID NUMBER
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_CHAIN_AUDT.PRVDR_CHAIN_TIN_NUM IS 'TAX ID NUMBER';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_DMEPOS_INDVDL
-- Type: VIEW
-- Relevant Columns: 1 of 21
-- Table Comment: A CROSS WALK OF AN INDIVIDUAL PROVIDERS NATIONAL PROVIDER IDENTIFIER TO THE LEGACY SYSTEMS DURABLE MEDICAL EQUIPMENT, PROSTHETICS, AND ORTHOTICS SUPPLIES NUMBER BY THE TYPE OF PROVIDER ADDRESS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_DMEPOS_INDVDL (
    PRVDR_NPI_NUM TEXT(10) NOT NULL
    -- PRVDR_NPI_NUM: THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT (HIPAA) ADMINISTRATIVE SIMPLIFICATION STANDA...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_DMEPOS_INDVDL.PRVDR_NPI_NUM IS 'THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT (HIPAA) ADMINISTRATIVE SIMPLIFICATION STANDARD UNIQUE HEALTH IDENTIFIER FOR A HEALTH CARE PROVIDER.  (NPI - NATIONAL PROVIDER IDENTIFIER)';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR
-- Type: VIEW
-- Relevant Columns: 3 of 14
-- Table Comment: THE EMPLOYER CHILD RECORD IS CREATED FOR A PHYSICIAN ASSISTANT, AND IS POPULATED FROM EMPLOYER INFORMATION IN SECTION 2J OF THE 855I ENROLLMENT RECORD.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR (
    PRVDR_EMPLR_TIN_NUM TEXT(9) NOT NULL,
    -- PRVDR_EMPLR_TIN_NUM: TIN OF THE EMPLOYER
    -- Categories: tin
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR.PRVDR_EMPLR_TIN_NUM IS 'TIN OF THE EMPLOYER';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 16
-- Table Comment: AN AUDIT OF THE PROVIDER EMPLOYER INFORMATION
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
    PRVDR_EMPLR_TIN_NUM TEXT(9) NOT NULL
    -- PRVDR_EMPLR_TIN_NUM: TIN OF THE EMPLOYER
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_EMPLR_AUDT.PRVDR_EMPLR_TIN_NUM IS 'TIN OF THE EMPLOYER';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT
-- Type: VIEW
-- Relevant Columns: 3 of 41
-- Table Comment: THE PARENT HEADER RECORD OF THE ENROLLMENT INFORMATION. THIS ENTITY STORES THE CURRENT RECORDS ONLY.  PECOS: EACH INSTANCE CONTAINS THE BASE DATA REQUIRED FOR AN INDIVIDUAL OR ORGANIZATION TO APPLY FOR THE AUTHORITY TO BILL MEDICARE FOR SERVICES RENDERED. AN ENROLLMENT IS THE PROCESS OF A PROVIDER ACCEPTING ASSIGNMENT OF AN AGREEMENT WITH CMS THAT QUALIFIES THE PROVIDER TO BILL MEDICARE FOR SERVICES IT RENDERS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
    PRVDR_ENRLMT_TIN_NUM TEXT(9) NOT NULL
    -- PRVDR_ENRLMT_TIN_NUM: TAX IDENTIFICATION NUMBER, SUCH AS AN EMPLOYER IDENTIFICATION NUMBER (EIN) OR SOCIAL SECURITY NUMBER...
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT.PRVDR_ENRLMT_TIN_NUM IS 'TAX IDENTIFICATION NUMBER, SUCH AS AN EMPLOYER IDENTIFICATION NUMBER (EIN) OR SOCIAL SECURITY NUMBER (SSN).';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 45
-- Table Comment: THE AUDIT TABLE WILL STORE CHANGES THAT OCCUR IN THE TABLE OVER TIME.  THESE CHANGES WILL NOT BE STORED IN THE TARGET TABLE SINCE IT WILL BE TRUNCATED AND RELOADED WEEKLY.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_AUDT (
    PRVDR_ENRLMT_TIN_NUM TEXT(9) NOT NULL,
    -- PRVDR_ENRLMT_TIN_NUM: TAX IDENTIFICATION NUMBER, SUCH AS AN EMPLOYER IDENTIFICATION NUMBER (EIN) OR SOCIAL SECURITY NUMBER...
    -- Categories: tin
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10)
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_AUDT.PRVDR_ENRLMT_TIN_NUM IS 'TAX IDENTIFICATION NUMBER, SUCH AS AN EMPLOYER IDENTIFICATION NUMBER (EIN) OR SOCIAL SECURITY NUMBER (SSN).';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_AUDT.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_HSTRY
-- Type: VIEW
-- Relevant Columns: 3 of 43
-- Table Comment: THE PARENT HEADER RECORD OF THE ENROLLMENT INFORMATION. THIS ENTITY STORES ALL HISTORICAL CHANGES.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_HSTRY (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10),
    PRVDR_ENRLMT_TIN_NUM TEXT(9) NOT NULL
    -- PRVDR_ENRLMT_TIN_NUM: TAX IDENTIFICATION NUMBER, SUCH AS AN EMPLOYER IDENTIFICATION NUMBER (EIN) OR SOCIAL SECURITY NUMBER...
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_HSTRY.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_HSTRY.PRVDR_ENRLMT_TIN_NUM IS 'TAX IDENTIFICATION NUMBER, SUCH AS AN EMPLOYER IDENTIFICATION NUMBER (EIN) OR SOCIAL SECURITY NUMBER (SSN).';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_STUS
-- Type: VIEW
-- Relevant Columns: 1 of 10
-- Table Comment: THE ENROLLMENT STATUS CHILD RECORD IS CREATED FOR SPECIFIC STATUS CODE AND REASON CODE COMBINATIONS. PECOS WILL SEND BOTH HISTORIC AND CURRENT ENROLLMENT STATUS INFORMATION. THE COMBINATION OF STATUS CODE AND REASON CODE CRITERIA MUST BE MET FOR THE CHILD RECORD TO BE SENT.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_STUS (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_STUS.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_STUS_AUDT
-- Type: VIEW
-- Relevant Columns: 1 of 12
-- Table Comment: AN AUDIT OF THE PROVIDER ENROLLMENT STATUS INFORMATION.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_STUS_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_ENRLMT_STUS_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HCIDEA_NPI
-- Type: VIEW
-- Relevant Columns: 1 of 11
-- Table Comment: A LINK BETWEEN THE NATIONAL PROVIDER IDENTIFIER (NPI) TO THE HCIDEA PROVIDER ID.     HCIDEA UTILIZES THE PRIMARY SOURCE, NPPES, FOR ITS NPI NUMBERS.    HCIDEA IS THE HEALTH CARE IDENTIFIER DRUG ENFORCEMENT AGENCY DATABASE FILE STANDARD GOVERNED BY NCPDP.  NOTE: THIS TABLE IS NO LONGER BEING UPDATED BY THE SOURCE.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HCIDEA_NPI (
    PRVDR_HCIDEA_NPI_NUM TEXT(10) NOT NULL
    -- PRVDR_HCIDEA_NPI_NUM: NATIONAL PROVIDER IDENTIFIER OF THE INDIVIDUAL PROVIDER
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HCIDEA_NPI.PRVDR_HCIDEA_NPI_NUM IS 'NATIONAL PROVIDER IDENTIFIER OF THE INDIVIDUAL PROVIDER';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA
-- Type: VIEW
-- Relevant Columns: 3 of 22
-- Table Comment: THE HHA CHILD RECORD IS CREATED WHEN A MEDICARE CONTRACTOR SELECTS HHA AS THE PROVIDER TYPE ON THE CMS 855A FORM.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA (
    PRVDR_HHA_TIN_NUM TEXT(9),
    -- PRVDR_HHA_TIN_NUM: IRS TAX IDENTIFICATION NUMBER OF A PECOS ASSOCIATE.
    -- Categories: tin
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA.PRVDR_HHA_TIN_NUM IS 'IRS TAX IDENTIFICATION NUMBER OF A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 24
-- Table Comment: AN AUDIT OF THE PROVIDER HOME HEALTH AIDE INFORMATION
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
    PRVDR_HHA_TIN_NUM TEXT(9)
    -- PRVDR_HHA_TIN_NUM: TAX ID NUMBER
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HHA_AUDT.PRVDR_HHA_TIN_NUM IS 'TAX ID NUMBER';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HSTRY
-- Type: VIEW
-- Relevant Columns: 2 of 45
-- Table Comment: A COMPILATION OF HISTORICAL PROVIDER DATA, SUCH AS NAME, ADDRESS, AND PROVIDER IDENTIFIER, FOR SERVICES RENDERED TO MEDICARE BENEFICIARIES, AND USED TO SUPPORT
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HSTRY (
    PRVDR_NPI_NUM TEXT(10),
    -- PRVDR_NPI_NUM: NPI NUMBER FOR MEDICAID PROVIDERS.
    -- Categories: npi
    PRVDR_EMPLR_ID_NUM TEXT(10)
    -- PRVDR_EMPLR_ID_NUM: THE PROVIDERS EMPLOYER ID NUMBER (EMPLOYER IDENTIFICATION NUMBER  (EIN), SOCIAL SECURITY NUMBER (SSN...
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HSTRY.PRVDR_NPI_NUM IS 'NPI NUMBER FOR MEDICAID PROVIDERS.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HSTRY.PRVDR_EMPLR_ID_NUM IS 'THE PROVIDERS EMPLOYER ID NUMBER (EMPLOYER IDENTIFICATION NUMBER  (EIN), SOCIAL SECURITY NUMBER (SSN) OR INDIVIDUAL TAX IDENTIFICATION NUMBER (ITIN))';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID
-- Type: VIEW
-- Relevant Columns: 3 of 15
-- Table Comment: THE MEDICARE ID CHILD RECORD CONTAINS THE SUPPLIERS NSC BILLING NUMBER WHICH IS ENTERED IN SECTION 1 OF THE CMS-855S FORM. THE MEDICARE ID CHILD RECORD WILL INCLUDE THE NSC BILLING NUMBER AND THE NATIONAL PROVIDER IDENTIFIER (NPI). (SEE DA COMMENT #1) PECOS WILL SEND THE CURRENT AND HISTORIC MEDICARE IDS  PECOS: EACH INSTANCE CONTAINS THE  PECOS ASSOCIATES MEDICARE IDENTIFICATION NUMBER.  THIS NUMBER UNIQUELY IDENTIFIES THE APPLICANT AS A MEDICARE PROVIDER AND/OR SUPPLIER AND IS THE NUMBER USED ON CLAIM FORMS.  EXAMPLES OF MEDICARE NUMBERS ARE  OSCAR AND NSC.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID (
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_INVLD_NPI_NUM TEXT(15)
    -- PRVDR_INVLD_NPI_NUM: AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID.PRVDR_INVLD_NPI_NUM IS 'AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 17
-- Table Comment: AN AUDIT OF THE PROVIDER MEDICARE IDENTIFER INFORMATION.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID_AUDT (
    PRVDR_PAC_ID TEXT(10),
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_INVLD_NPI_NUM TEXT(15)
    -- PRVDR_INVLD_NPI_NUM: AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID_AUDT.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MDCR_ID_AUDT.PRVDR_INVLD_NPI_NUM IS 'AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR
-- Type: VIEW
-- Relevant Columns: 4 of 14
-- Table Comment: THE MEMBERS CHILD RECORD IS CREATED FOR MEMBERS REASSIGNED TO AN ORGANIZATION. IF THE GROUP HAS THREE MEMBERS, EXACTLY THREE MEMBER CHILD RECORDS WILL BE CREATED. ONLY CURRENT MEMBERS ARE SENT.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR (
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_INDVDL_ENRLMT_ID TEXT(15),
    -- PRVDR_INDVDL_ENRLMT_ID: ENROLLMENT ID OF INDIVIDUAL ENROLLMENT
    -- Categories: enrollment
    PRVDR_GRP_MMBR_PAC_ID TEXT(10)
    -- PRVDR_GRP_MMBR_PAC_ID: PAC ID OF GROUP MEMBER
    -- Categories: pac_id
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR.PRVDR_INDVDL_ENRLMT_ID IS 'ENROLLMENT ID OF INDIVIDUAL ENROLLMENT';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR.PRVDR_GRP_MMBR_PAC_ID IS 'PAC ID OF GROUP MEMBER';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR_AUDT
-- Type: VIEW
-- Relevant Columns: 4 of 16
-- Table Comment: AN AUDIT OF THE PROVIDER MEMBER INFORMATION
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
    PRVDR_INDVDL_ENRLMT_ID TEXT(15),
    -- PRVDR_INDVDL_ENRLMT_ID: ENROLLMENT ID OF INDIVIDUAL ENROLLMENT
    -- Categories: enrollment
    PRVDR_GRP_MMBR_PAC_ID TEXT(10)
    -- PRVDR_GRP_MMBR_PAC_ID: PAC ID OF GROUP MEMBER
    -- Categories: pac_id
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR_AUDT.PRVDR_INDVDL_ENRLMT_ID IS 'ENROLLMENT ID OF INDIVIDUAL ENROLLMENT';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_MMBR_AUDT.PRVDR_GRP_MMBR_PAC_ID IS 'PAC ID OF GROUP MEMBER';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP
-- Type: VIEW
-- Relevant Columns: 1 of 99
-- Table Comment: NCPDP MAINTAINED INFORMATION ASSIGNED TO EVERY LICENSED PHARMACY IN THE UNITED STATES AND TERRITORIES.  THIS TABLE ALLOWS A LINK TO THE VERSIONED INFORMATION.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP (
    PRVDR_NCPDP_NPI TEXT(10)
    -- PRVDR_NCPDP_NPI: THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEAL...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP.PRVDR_NCPDP_NPI IS 'THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS. AT THE PHARMACY OR ALTERNATE DISPENSING SITE LEVEL.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_HSTRY
-- Type: VIEW
-- Relevant Columns: 1 of 101
-- Table Comment: NCPDP MAINTAINED INFORMATION ASSIGNED TO EVERY LICENSED PHARMACY IN THE UNITED STATES AND TERRITORIES.  THIS TABLE HOLDS THE VERSIONED INFORMATION.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_HSTRY (
    PRVDR_NCPDP_NPI TEXT(10)
    -- PRVDR_NCPDP_NPI: THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEAL...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_HSTRY.PRVDR_NCPDP_NPI IS 'THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS. AT THE PHARMACY OR ALTERNATE DISPENSING SITE LEVEL.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PRNT_ORG
-- Type: VIEW
-- Relevant Columns: 1 of 20
-- Table Comment: THE NATIONAL COUNCIL FOR PRESCRIPTION DRUG PROGRAMS (NCPDP) MAINTAINED INFORMATION FOR HEADQUARTER ADDRESS INFORMATION FOR CHAINS, BUYING GROUPS OR THIRD PARTY CONTRACTING ORGANIZATIONS WHERE MULTIPLE RELATIONSHIP ENTITIES EXIST AND NEED TO BE LINKED TO A COMMON ORGANIZATION SUCH AS COMMON OWNERSHIP FOR SEVERAL CHAINS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PRNT_ORG (
    PRVDR_NCPDP_PRNT_NPI TEXT(10)
    -- PRVDR_NCPDP_PRNT_NPI: NPI OF PARENT ORGANIZATION. THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE I...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PRNT_ORG.PRVDR_NCPDP_PRNT_NPI IS 'NPI OF PARENT ORGANIZATION. THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PYMT_CNTR
-- Type: VIEW
-- Relevant Columns: 1 of 20
-- Table Comment: THE NATIONAL COUNCIL FOR PRESCRIPTION DRUG PROGRAMS (NCPDP) MAINTAINED INFORMATION IDENTIFYING THE ENTITY ACCEPTING PAYMENTS ON BEHALF OF A PROVIDER.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PYMT_CNTR (
    PRVDR_NPI_NUM TEXT(10)
    -- PRVDR_NPI_NUM: THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER. (NPS 03/30/...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PYMT_CNTR.PRVDR_NPI_NUM IS 'THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER. (NPS 03/30/02) NPI OF THE PAYMENT CENTER LOCATION. THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_REMIT
-- Type: VIEW
-- Relevant Columns: 1 of 20
-- Table Comment: ADDRESS RECORDS FOR MAILING REMIT AND RECONCILIATION, IF DIFFERENT FROM THE PAYMENT CENTER ADDRESS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_REMIT (
    PRVDR_NPI_NUM TEXT(10) NOT NULL
    -- PRVDR_NPI_NUM: NPI OF THE REMIT AND RECONCILIATION LOCATION. THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE ...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_REMIT.PRVDR_NPI_NUM IS 'NPI OF THE REMIT AND RECONCILIATION LOCATION. THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC
-- Type: VIEW
-- Relevant Columns: 1 of 35
-- Table Comment: THE NATIONAL COUNCIL FOR PRESCRIPTION DRUG PROGRAMS (NCPDP)  MAINTAINED INFORMATION CLASSIFYING THE TYPE OF ENTITY.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC (
    PRVDR_NCPDP_RLTNSHP_NPI_NUM TEXT(10)
    -- PRVDR_NCPDP_RLTNSHP_NPI_NUM: THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER. (NPS 03/30/...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC.PRVDR_NCPDP_RLTNSHP_NPI_NUM IS 'THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER. (NPS 03/30/02)  THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS. AN ORGANIZATIONAL, TYPE 2, NPI ASSIGNED TO THE RELATIONSHIP ENTITY.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NON_DLVRBL_AUDT
-- Type: VIEW
-- Relevant Columns: 1 of 12
-- Table Comment: AN AUDIT OF THE PROVIDER  NON DELIVERABLE INFORMATION.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NON_DLVRBL_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NON_DLVRBL_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_DMEPOS_GRP
-- Type: VIEW
-- Relevant Columns: 1 of 19
-- Table Comment: A CROSS WALK OF A GROUP PROVIDERS NATIONAL PROVIDER IDENTIFIER TO THE LEGACY SYSTEMS DURABLE MEDICAL EQUIPMENT, PROSTHETICS, AND ORTHOTICS SUPPLIES NUMBER BY THE TYPE OF PROVIDER ADDRESS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_DMEPOS_GRP (
    PRVDR_NPI_NUM TEXT(10) NOT NULL
    -- PRVDR_NPI_NUM: THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT (HIPAA) ADMINISTRATIVE SIMPLIFICATION STANDA...
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_DMEPOS_GRP.PRVDR_NPI_NUM IS 'THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT (HIPAA) ADMINISTRATIVE SIMPLIFICATION STANDARD UNIQUE HEALTH IDENTIFIER FOR A HEALTH CARE PROVIDER.  (NPI - NATIONAL PROVIDER IDENTIFIER)';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_GRP
-- Type: VIEW
-- Relevant Columns: 1 of 24
-- Table Comment: A CROSSWALK OF A NATIONAL PROVIDER IDENTIFIER (NPI) TO A LEGACY GROUP PROVIDER IDENTIFICATION NUMBER (PIN) BY THE TYPE OF ADDRESS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_GRP (
    PRVDR_NPI_PIN_TIN_NUM TEXT(9) NOT NULL
    -- PRVDR_NPI_PIN_TIN_NUM: A UNIQUE  TAX IDENTIFIER ASSIGNED TO A HEALTH CARE PROVIDER BY SOCIAL SECURITY ADMINISTRATION (SSA) ...
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_GRP.PRVDR_NPI_PIN_TIN_NUM IS 'A UNIQUE  TAX IDENTIFIER ASSIGNED TO A HEALTH CARE PROVIDER BY SOCIAL SECURITY ADMINISTRATION (SSA) OR THE INTERNAL';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_INDVDL
-- Type: VIEW
-- Relevant Columns: 1 of 31
-- Table Comment: A CROSSWALK OF A NATIONAL PROVIDER IDENTIFIER TO A LEGACY INDIVIDUAL PROVIDER IDENTIFICATION NUMBER (PIN) BY THE TYPE OF ADDRESS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_INDVDL (
    PRVDR_NPI_PIN_TIN_NUM TEXT(9) NOT NULL
);



-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP
-- Type: VIEW
-- Relevant Columns: 3 of 28
-- Table Comment: THE OWNERSHIP INTEREST/MANAGING CONTROL CHILD RECORD IS CREATED TO COLLECT INFORMATION ON OWNERSHIP/CONTROL FOR BOTH INDIVIDUALS AND ORGANIZATIONS.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP (
    PRVDR_OWNRSHP_TIN_NUM TEXT(9) NOT NULL,
    -- PRVDR_OWNRSHP_TIN_NUM: TAX ID NUMBER
    -- Categories: tin
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP.PRVDR_OWNRSHP_TIN_NUM IS 'TAX ID NUMBER';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 30
-- Table Comment: AN AUDIT OF THE PROVIDER OWNERSHIP INFORMATION
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_OWNRSHP_TIN_NUM TEXT(9) NOT NULL,
    -- PRVDR_OWNRSHP_TIN_NUM: TAX ID NUMBER
    -- Categories: tin
    PRVDR_PAC_ID TEXT(10) NOT NULL
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP_AUDT.PRVDR_OWNRSHP_TIN_NUM IS 'TAX ID NUMBER';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OWNRSHP_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX
-- Type: VIEW
-- Relevant Columns: 2 of 65
-- Table Comment: A PBX (PROVIDER PART B EXTRACT) FILE THAT CONTAINS ENROLLMENT, DEMOGRAPHIC, CREDENTIAL, AND PAYEE INFORMATION FOR HEALTHCARE PROVIDERS THAT BILL MEDICARE PART B.   (PART B IS MEDICAL INSURANCE. IT HELPS PAY FOR DOCTORS FEES, OUTPATIENT HOSPITAL VISITS, A
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX (
    PRVDR_NPI_NUM TEXT(10),
    -- PRVDR_NPI_NUM: THE PROVIDERÒ² 10-DIGIT NATIONAL PROVIDER IDENTIFIER (NPI). ASSIGNED BY THE NATIONAL PLAN AND PROVID...
    -- Categories: npi
    PRVDR_TIN_NUM TEXT(9)
    -- PRVDR_TIN_NUM: TAX IDENTIFICATION NUMBER FOR THIS PROVIDER (I.E., THE TIN THAT IS USED FOR PAYMENT/TAX PURPOSES FOR...
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX.PRVDR_NPI_NUM IS 'THE PROVIDERÒ² 10-DIGIT NATIONAL PROVIDER IDENTIFIER (NPI). ASSIGNED BY THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES), THE NPI IS BEING PHASED IN AS THE STANDARD IDENTIFIER USED BY PROVIDERS WHEN SUBMITTING MEDICARE CLAIMS.   EFFECTIVE MARCH 1, 2008, PART B PROVIDERS MUST USE NPIS IN THE PERFORMING/RENDERING PROVIDER FIELD, THE PAY-TO PROVIDER FIELD, AND THE BILLING PROVIDER FIELD WHEN SUBMITTING CLAIMS TO MEDICARE FOR PAYMENT.   EFFECTIVE MAY 23, 2008, NPIS WILL ALSO BE REQUIRED AS THE IDENTIFIERS FOR THE FOLLOWING Ó²ECONDARYÔ PROVIDER FIELDS ON PART B, DMEPOS, AND PART A CLAIMS: ORDERING PHYSICIAN, REFERRING PHYSICIAN, ATTENDING PHYSICIAN, OPERATING PHYSICIAN, OTHER PHYSICIAN, PURCHASED SERVICE PROVIDER, OR SERVICE FACILITY PROVIDER.    DATA PROFILING SHOWS THAT DATA SEEMS TO MATCH IDR.     SELECT  *  FROM   CMS_VIEW_PRVDR_CDEV.V1_PRVDR   WHERE     PRVDR_NPI_NUM   IN (   SELECT   DISTINCT  PBX_PROV_NPI  FROM     CMS_WORK_COMM_CDEV.PROV_EXTRACT_EXTERNAL_OUT_SM)';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX.PRVDR_TIN_NUM IS 'TAX IDENTIFICATION NUMBER FOR THIS PROVIDER (I.E., THE TIN THAT IS USED FOR PAYMENT/TAX PURPOSES FOR THE PROVIDER IDENTIFIED BY THE PROV-NBR-KEY ON THIS RECORD). MORE THAN ANY OTHER FIELD, THE TIN GIVES A GENERALLY RELIABLE METHOD OF LINKING TOGETHER ALL OF THE PROVIDERS WHO ARE MEMBERS OF A GROUP, SINCE THEY WILL ALL SHARE THE SAME TIN. THE TIN FIELD CONTAINS AN IRS-ISSUED NUMBER THAT IDENTIFIES TO WHOM MEDICARE PAYMENT IS MADE. EVERY PART B NCH CLAIM CONTAINS A TIN, EVEN THOUGH THE NCH CLAIM RECORDS DO NOT CARRY PAY-TO OR BILLING PROVIDER IDS.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK
-- Type: VIEW
-- Relevant Columns: 2 of 62
-- Table Comment: A PBX (PROVIDER PART B EXTRACT) FILE THAT CONTAINS ENROLLMENT, DEMOGRAPHIC, CREDENTIAL, AND PAYEE INFORMATION FOR HEALTHCARE PROVIDERS THAT BILL MEDICARE PART B.   (PART B IS MEDICAL INSURANCE. IT HELPS PAY FOR DOCTORS FEES, OUTPATIENT HOSPITAL VISITS, AND OTHER MEDICAL SERVICES AND SUPPLIES THAT ARE NOT COVERED BY PART A.)   THESE PROVIDERS ARE GENERALLY CLASSIFIED AS “INDIVIDUAL PRACTITIONERS” (SUCH AS DOCTORS, CHIROPRACTORS, PHYSICAL THERAPISTS, PSYCHOLOGISTS, OSTEOPATHS, AND PATHOLOGISTS) OR AS “ORGANIZATIONAL PROVIDERS” (SUCH AS GROUP PRACTICES, MULTI-SPECIALTY CLINICS, AMBULANCE COMPANIES, CLINICAL LABORATORIES, MEDICAL SUPPLY COMPANIES, PUBLIC HEALTH AGENCIES, AND PORTABLE X-RAY SUPPLIERS)… TO NAME A FEW. PROVIDERS ARE REPRESENTED ON MEDICARE CLAIMS BY UP TO FOUR (4) DIFFERENT IDENTIFIERS, EACH OF WHICH (WHEN AVAILABLE) IS CARRIED ON THE PROVBX FILE.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK (
    PRVDR_NPI_NUM TEXT(10),
    -- PRVDR_NPI_NUM: THE PROVIDERÒ² 10-DIGIT NATIONAL PROVIDER IDENTIFIER (NPI). ASSIGNED BY THE NATIONAL PLAN AND PROVID...
    -- Categories: npi
    PRVDR_TIN_NUM TEXT(9)
    -- PRVDR_TIN_NUM: TAX IDENTIFICATION NUMBER FOR THIS PROVIDER (I.E., THE TIN THAT IS USED FOR PAYMENT/TAX PURPOSES FOR...
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK.PRVDR_NPI_NUM IS 'THE PROVIDERÒ² 10-DIGIT NATIONAL PROVIDER IDENTIFIER (NPI). ASSIGNED BY THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES), THE NPI IS BEING PHASED IN AS THE STANDARD IDENTIFIER USED BY PROVIDERS WHEN SUBMITTING MEDICARE CLAIMS.   EFFECTIVE MARCH 1, 2008, PART B PROVIDERS MUST USE NPIS IN THE PERFORMING/RENDERING PROVIDER FIELD, THE PAY-TO PROVIDER FIELD, AND THE BILLING PROVIDER FIELD WHEN SUBMITTING CLAIMS TO MEDICARE FOR PAYMENT.   EFFECTIVE MAY 23, 2008, NPIS WILL ALSO BE REQUIRED AS THE IDENTIFIERS FOR THE FOLLOWING Ó²ECONDARYÔ PROVIDER FIELDS ON PART B, DMEPOS, AND PART A CLAIMS: ORDERING PHYSICIAN, REFERRING PHYSICIAN, ATTENDING PHYSICIAN, OPERATING PHYSICIAN, OTHER PHYSICIAN, PURCHASED SERVICE PROVIDER, OR SERVICE FACILITY PROVIDER.    DATA PROFILING SHOWS THAT DATA SEEMS TO MATCH IDR.     SELECT  *  FROM   CMS_VIEW_PRVDR_CDEV.V1_PRVDR   WHERE     PRVDR_NPI_NUM   IN (   SELECT   DISTINCT  PBX_PROV_NPI  FROM     CMS_WORK_COMM_CDEV.PROV_EXTRACT_EXTERNAL_OUT_SM)';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK.PRVDR_TIN_NUM IS 'TAX IDENTIFICATION NUMBER FOR THIS PROVIDER (I.E., THE TIN THAT IS USED FOR PAYMENT/TAX PURPOSES FOR THE PROVIDER IDENTIFIED BY THE PROV-NBR-KEY ON THIS RECORD). MORE THAN ANY OTHER FIELD, THE TIN GIVES A GENERALLY RELIABLE METHOD OF LINKING TOGETHER ALL OF THE PROVIDERS WHO ARE MEMBERS OF A GROUP, SINCE THEY WILL ALL SHARE THE SAME TIN. THE TIN FIELD CONTAINS AN IRS-ISSUED NUMBER THAT IDENTIFIES TO WHOM MEDICARE PAYMENT IS MADE. EVERY PART B NCH CLAIM CONTAINS A TIN, EVEN THOUGH THE NCH CLAIM RECORDS DO NOT CARRY PAY-TO OR BILLING PROVIDER IDS.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN
-- Type: VIEW
-- Relevant Columns: 3 of 40
-- Table Comment: THE PRACTICE LOCATION CHILD RECORD IS CREATED TO INCLUDE THE PROVIDERS PRACTICE LOCATION INFORMATION. PECOS WILL SEND BOTH HISTORIC AND CURRENT PRACTICE LOCATION INFORMATION. THE PRACTICE LOCATION INFORMATION IS LINKED TO THE SPECIAL PAYMENT INFORMATION.  PECOS: EACH INSTANCE CONTAINS INFORMATION ABOUT THE PHYSICAL  LOCATION WHERE THIS PROVIDER CURRENTLY RENDERS HEALTH CARE SERVICES.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN (
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_INVLD_NPI_NUM TEXT(15)
    -- PRVDR_INVLD_NPI_NUM: AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN.PRVDR_INVLD_NPI_NUM IS 'AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT
-- Type: VIEW
-- Relevant Columns: 3 of 42
-- Table Comment: AN AUDIT OF THE PROVIDER PRACTION LOCATION INFORMATION.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(20),
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
    PRVDR_INVLD_NPI_NUM TEXT(15)
    -- PRVDR_INVLD_NPI_NUM: AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT.PRVDR_INVLD_NPI_NUM IS 'AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PSF
-- Type: VIEW
-- Relevant Columns: 1 of 73
-- Table Comment: AN INSTITUTIONAL PROVIDER AT A POINT IN TIME AS DOCUMENTED IN THE PROVIDER SPECIFIC FILE.  NOTE: THE PROV FILE CONTAINS NEEDED INFORMATION ABOUT EACH PROVIDER TO ENABLE THE PRICING SOFTWARE TO CALCULATE THE PAYMENT AMOUNT.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PSF (
    PRVDR_NPI_NUM TEXT(10)
    -- PRVDR_NPI_NUM: THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER.
    -- Categories: npi
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PSF.PRVDR_NPI_NUM IS 'THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT
-- Type: VIEW
-- Relevant Columns: 5 of 16
-- Table Comment: THE REASSIGNMENT CHILD RECORD IS CREATED WHEN AN INDIVIDUAL REASSIGNS HIS/HER BENEFITS TO AN ORGANIZATION OR ANOTHER INDIVIDUAL. A RECORD WILL BE CREATED FOR EACH ENTITY THAT BENEFITS ARE BEING REASSIGNED TO.
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT (
    PRVDR_REASGNMT_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_REASGNMT_ENRLMT_ID: ENROLLMENT ID
    -- Categories: enrollment
    PRVDR_REASGNMT_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_REASGNMT_PAC_ID: PAC ID
    -- Categories: pac_id
    PRVDR_REASGNMT_TIN_NUM TEXT(9),
    -- PRVDR_REASGNMT_TIN_NUM: IRS TAX IDENTIFICATION NUMBER OF A PECOS ASSOCIATE.
    -- Categories: tin
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
    -- Categories: pac_id
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT.PRVDR_REASGNMT_ENRLMT_ID IS 'ENROLLMENT ID';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT.PRVDR_REASGNMT_PAC_ID IS 'PAC ID';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT.PRVDR_REASGNMT_TIN_NUM IS 'IRS TAX IDENTIFICATION NUMBER OF A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT.PRVDR_PAC_ID IS 'THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';


-- ========================================
-- Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT_AUDT
-- Type: VIEW
-- Relevant Columns: 5 of 18
-- Table Comment: AN AUDIT OF THE PROVIDER REASSIGNMENT INFORMATION
-- ========================================

CREATE TABLE IF NOT EXISTS IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT_AUDT (
    PRVDR_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_ENRLMT_ID: PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
    -- Categories: enrollment
    PRVDR_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_PAC_ID: UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
    -- Categories: pac_id
    PRVDR_REASGNMT_ENRLMT_ID TEXT(15) NOT NULL,
    -- PRVDR_REASGNMT_ENRLMT_ID: ENROLLMENT ID
    -- Categories: enrollment
    PRVDR_REASGNMT_PAC_ID TEXT(10) NOT NULL,
    -- PRVDR_REASGNMT_PAC_ID: PAC ID
    -- Categories: pac_id
    PRVDR_REASGNMT_TIN_NUM TEXT(9)
    -- PRVDR_REASGNMT_TIN_NUM: TAX ID NUMBER
    -- Categories: tin
);

COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT_AUDT.PRVDR_ENRLMT_ID IS 'PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT_AUDT.PRVDR_PAC_ID IS 'UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT_AUDT.PRVDR_REASGNMT_ENRLMT_ID IS 'ENROLLMENT ID';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT_AUDT.PRVDR_REASGNMT_PAC_ID IS 'PAC ID';
COMMENT ON COLUMN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_REASGNMT_AUDT.PRVDR_REASGNMT_TIN_NUM IS 'TAX ID NUMBER';


