"""
==========
V2_MDCR_PRVDR_NPI_DMEPOS_GRP IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_DMEPOS_GRP

Table Type: VIEW
Columns: 19
Source Pattern: %prvdr_npi%
Table Comment: A CROSS WALK OF A GROUP PROVIDERS NATIONAL PROVIDER IDENTIFIER TO THE LEGACY SYSTEMS DURABLE MEDICAL EQUIPMENT, PROSTHETICS, AND ORTHOTICS SUPPLIES NUMBER BY THE TYPE OF PROVIDER ADDRESS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrNpiDmeposGrpExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrNpiDmeposGrpExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_NPI_DMEPOS_GRP data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_DMEPOS_GRP (VIEW)
    Columns: 19
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_npi_dmepos_grp_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_NPI_DMEPOS_GRP export.
        
        Includes all 19 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_SK, -- NUMBER(18) | NOT NULL | AN IDR ASSIGNED SURROGATE KEY USED TO IDENTIFY A PARTY ENGAGED IN ACTIVITY RELATED TO CMS.
                PRVDR_DMEPOS_GRP_NUM, -- TEXT(13) | NOT NULL | THE IDENTIFIER OF A DURABLE MEDICAL EQUIPMENT, PROSTHETICS, ORTHOTICS, AND SUPPLIES (DMEPOS) PROVIDER ASSIGNED BY THE NATIONAL SUPPLIER CLEARINGHOUSE AND REFERRED TO AS A PTAN (PROVIDER TRANSACTION ACCESS NUMBER).
                PRVDR_LGCY_ADR_TYPE_CD, -- TEXT(1) | NOT NULL | INDICATES THE TYPE OF ADDRESS FROM THE LEGACY SYSTEM: 1 = MASTER 2 = REMITTANCE 3 = CHECK 4 = MSP 5 = MR 6 = OTHER 7 = PAYEE B = BILLING M = MAILING P = PRACTICE
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_DMEPOS_GRP_BGN_DT, -- DATE | NOT NULL | THE DATE THAT THE PROVIDER ID/NPI CROSSWALK MATCH WAS MADE BASED ON THE ADDRESS TYPE CODE.
                PRVDR_DMEPOS_GRP_END_DT, -- DATE | NOT NULL | THE DATE THAT THE PROVIDER ID/NPI CROSSWALK MATCH WAS TERMINATED. IF THE MATCH HAS NOT BEEN TERMINATED, THE COLUMN WILL CONTAIN 12/31/9999.
                PRVDR_DMEPOS_GRP_MDCR_BGN_DT, -- DATE | NOT NULL | MEDICARE COVERAGE START DATE BASED ON THE ADDRESS TYPE CODE.
                PRVDR_DMEPOS_GRP_MDCR_END_DT, -- DATE | NOT NULL | MEDICARE COVERAGE END DATE BASED ON THE ADDRESS TYPE CODE.
                PRVDR_NPI_NUM, -- TEXT(10) | NOT NULL | THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT (HIPAA) ADMINISTRATIVE SIMPLIFICATION STANDARD UNIQUE HEALTH IDENTIFIER FOR A HEALTH CARE PROVIDER. (NPI - NATIONAL PROVIDER IDENTIFIER)
                PRVDR_DMEPOS_GRP_NAME, -- TEXT(35) | NULL | THE GROUP NAME OF THE PROVIDER.
                PRVDR_DMEPOS_GRP_EIN_NUM, -- TEXT(9) | NULL | THE EMPLOYER IDENTIFICATION NUMBER (EIN) OF THE PROVIDER. THE EIN IS ASSIGNED BY THE INTERNAL REVENUE SERVICE (IRS).
                PRVDR_DMEPOS_LINE_1_ADR, -- TEXT(55) | NULL | THE FIRST LINE OF A PARTY ADDRESS.
                PRVDR_DMEPOS_LINE_2_ADR, -- TEXT(55) | NULL | THE SECOND LINE OF A PARTY ADDRESS.
                PRVDR_DMEPOS_PLC_NAME, -- TEXT(30) | NULL | PLACE NAME. POPULATED FROM THE SOURCE AND MAY BE INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP (ZONE IMPROVEMENT POSTAL) CODE.
                PRVDR_DMEPOS_ZIP_CD, -- TEXT(9) | NULL | ZIP (ZONE IMPROVEMENT POSTAL) CODE. POPULATED FROM THE SOURCE AND MAY BE INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_DMEPOS_ST_CD, -- TEXT(2) | NULL | STATE CODE. POPULATED FROM THE SOURCE AND MAY BE INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP (ZONE IMPROVEMENT POSTAL) CODE.
                META_SK, -- NUMBER(38) | NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_DMEPOS_GRP"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrNpiDmeposGrpExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
