"""
==========
V2_MDCR_PRVDR_NPI_OSCAR IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_OSCAR

Table Type: VIEW
Columns: 21
Source Pattern: %prvdr_npi%
Table Comment: A CROSSWALK OF A NATIONAL PROVIDER IDENTIFIER (NPI) TO A ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER BY THE TYPE OF ADDRESS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrNpiOscarExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrNpiOscarExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_NPI_OSCAR data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_OSCAR (VIEW)
    Columns: 21
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_npi_oscar_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_NPI_OSCAR export.
        
        Includes all 21 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_SK, -- NUMBER(18) | NOT NULL | AN IDR ASSIGNED SURROGATE KEY USED TO IDENTIFY A PARTY ENGAGED IN ACTIVITY RELATED TO CMS.
                PRVDR_OSCAR_NUM, -- TEXT(13) | NOT NULL | AN ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_NPI_OSCAR_BGN_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN THE ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR)/ NATIONAL PROVIDER IDENTIFIER (NPI) CROSSWALK MATCH WAS MADE IN THE INTEGRATED DATA REPOSITORY (IDR) BASED ON THE ADDRESS TYPE CODE.
                PRVDR_NPI_OSCAR_END_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN THE ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR)/ NATIONAL PROVIDER IDENTIFIER (NPI) CROSSWALK MATCH WAS TERMINATED IN THE INTEGRATED DATA REPOSITORY (IDR) BASED ON THE ADDRESS TYPE CODE. THE CURRENT VERSION OF A RECORD WILL BE SET TO 12/31/9999.
                CLM_CNTRCTR_NUM, -- TEXT(5) | NOT NULL | A NUMBER ASSIGNED BY CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) IDENTIFYING A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC) AUTHORIZED TO PROCESS MEDICARE CLAIMS. REFERENCE TABLE: CLM_CNTRCTR_NUM
                PRVDR_NPI_OSCAR_MDCR_BGN_DT, -- DATE | NOT NULL | A DATE IDENTIFYING WHEN THE NATIONAL PROVIDER IDENTIFIER (NPI)/ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER COMBINATION BECAME ELIGIBLE FOR MEDICARE PAYMENTS.
                PRVDR_NPI_OSCAR_MDCR_END_DT, -- DATE | NOT NULL | A DATE IDENTIFYING WHEN THE NATIONAL PROVIDER IDENTIFIER (NPI)/ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER COMBINATION BECAME INELIGIBLE FOR MEDICARE PAYMENTS.
                PRVDR_NPI_OSCAR_NAME, -- TEXT(31) | NOT NULL | THE NAME OF THE PROVIDER.
                PRVDR_NPI_OSCAR_FED_TAX_NUM, -- TEXT(9) | NOT NULL | THIS IS THE FEDERAL TAX ID NUMBER OF THE PROVIDER.
                PRVDR_NPI_OSCAR_LINE_1_ADR, -- TEXT(31) | NOT NULL | THE FIRST LINE OF A PARTY ADDRESS.
                PRVDR_NPI_OSCAR_LINE_2_ADR, -- TEXT(31) | NOT NULL | THE SECOND LINE OF A PARTY ADDRESS.
                PRVDR_NPI_OSCAR_INVLD_PLC_NAME, -- TEXT(20) | NOT NULL | THE NAME OF THE CITY
                PRVDR_NPI_OSCAR_INVLD_ZIP_CD, -- TEXT(9) | NOT NULL | A ZIP CODE DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT IDENTIFIES A DESTINATION POST OFFICE OR DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. NOTE: THIS IS THE ZIP CODE FOR A NATIONAL PROVIDER IDENTIFIER (NPI)/ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER COMBINATION. REFERENCE TABLE: GEO_ZIP5_CD AND GEO_ZIP9_CD
                PRVDR_NPI_OSCAR_INVLD_STATE_CD, -- TEXT(2) | NOT NULL | A CODE IDENTIFYING THE TWO-CHARACTER ALPHABETIC ABBREVIATION FOR A STATE IN THE UNITED STATES AS DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS). NOTE: THIS IS THE STATE CODE FOR A NATIONAL PROVIDER IDENTIFIER (NPI)/ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER COMBINATION. REFERENCE TABLE: GEO_USPS_STATE_CD
                GEO_SK, -- NUMBER(38) | NOT NULL | IDENTIFIER OF THE GEOGRAPHICAL AREA ASSOCIATED WITH THE PROVIDER.
                GEO_ZIP4_CD, -- TEXT(4) | NOT NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_NPI_OSCAR_PHNE_NUM, -- TEXT(10) | NOT NULL | TELEPHONE NUMBER
                PRVDR_NPI_OSCAR_TYPE_CD, -- TEXT(2) | NOT NULL | A CODE IDENTIFYING A TYPE OF ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) PROVIDER AS DEFINED IN THE PROVIDER SPECIFIC FILE (PSF). NOTE: PROVIDER TYPE VALUES 49-54 REFER TO SPECIAL UNIT DESIGNATIONS THAT ARE ASSIGNED TO THE THIRD POSITION OF THE OSCAR NUMBER. REFERENCE TABLE: V2_MDCR_PRVDR_PSF_TYPE_CD
                PRVDR_LGCY_ADR_TYPE_CD, -- TEXT(1) | NOT NULL | ENCODING OF THE CATEGORIZATION OF ADDRESSES BASED ON BUSINESS FUNCTION PERFORMED AT THAT LOCATION (NPICS) .
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_OSCAR"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrNpiOscarExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
