"""
==========
V2_MDCR_PRVDR_TXNMY_CD IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_TXNMY_CD

Table Type: VIEW
Columns: 12
Source Pattern: %mdcr_prvdr%
Table Comment: A LISTING OF THE HEALTHCARE PROVIDER TAXONOMY CODE SET WHICH CATEGORIZES HEALTH CARE PROVIDERS BY TYPE, CLASSIFICATION, AND/OR AREA OF SPECIALIZATION.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrTxnmyCdExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrTxnmyCdExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_TXNMY_CD data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_TXNMY_CD (VIEW)
    Columns: 12
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_txnmy_cd_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_TXNMY_CD export.
        
        Includes all 12 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_TXNMY_CD, -- TEXT(10) | NOT NULL | A CODE IDENTIFYING THE TYPE, CLASSIFICATION, AND/OR SPECIALIZATION OF A PROVIDER. FOR EXAMPLE: 207R00000X = INTERNAL MEDICINE 3416A0800X = AMBULANCE AIR TRANSPORT
                PRVDR_TXNMY_TYPE_TXT, -- TEXT(200) | NOT NULL | A TEXT DESCRIPTION OF THE TYPE OF PROVIDER FOR A TAXONOMY CODE. THIS IS THE FIRST LEVEL IDENTIFYING THE MAJOR GROUPING OF SERVICE OR OCCUPATION OF A HEALTH CARE PROVIDER FOR AN ASSOCIATED TAXONOMY CODE. FOR EXAMPLE: GROUP ALLOPATHIC & OSTEOPATHIC PHYSICIANS AMBULATORY HEALTH CARE FACILITIES SUPPLIERS
                PRVDR_TXNMY_CLSFCTN_TXT, -- TEXT(200) | NOT NULL | A TEXT DESCRIPTION OF THE CLASSIFICATION FOR A TAXONOMY CODE. THIS IS THE SECOND LEVEL IDENTIFYING A MORE SPECIFIC SERVICE OR OCCUPATION RELATED TO THE PROVIDER TYPE FOR AN ASSOCIATED TAXONOMY CODE. FOR EXAMPLE: 193200000X= MULTI-SPECIALTY (CLASSIFICATION OF GROUP PROVIDER TYPE) 207K00000X = ALLERGY & IMMUNOLOGY (CLASSIFICATION OF ALLOPATHIC & OSTEOPATHIC PHYSICIANS PROVIDER TYPE)
                PRVDR_TXNMY_SPCLZTN_TXT, -- TEXT(200) | NOT NULL | A TEXT DESCRIPTION OF THE AREA OF SPECIALIZATION FOR A TAXONOMY CODE. THIS IS THE THIRD LEVEL IDENTIFYING A SPECIFIC AREA A PROVIDER CHOOSES TO PRACTICE OR MAKE SERVICES AVAILABLE. FOR EXAMPLE: 207KA0200K = ALLERGY (AREA OF SPECIALIZATION UNDER ALLERGY & IMMUNOLOGY) 261QM0850X = ADULT MENTAL HEALTH (AREA OF SPECIALIZATION UNDER AMBULATORY HEALTH CARE FACILITIES CLASSIFICATION) NOTE: NOT ALL TAXONOMY CODES HAVE AN AREA OF SPECIALIZATION.
                PRVDR_TXNMY_EFCTV_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN A PROVIDER TAXONOMY CODE BECAME EFFECTIVE.
                PRVDR_TXNMY_OBSLT_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN A PROVIDER TAXONOMY CODE IS NO LONGER EFFECTIVE.
                PRVDR_TXNMY_LAST_MDFYD_DT, -- DATE | NULL | A DATE INDICATING THE LAST TIME THE PROVIDER TAXONOMY CODE DATA WAS MODIFIED BY THE NATIONAL UNIFORM CLAIM COMMITTEE(NUCC).
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                META_SRC_PRCSG_ID, -- NUMBER(38) | NOT NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS INSERTED.
                META_LTST_SRC_PRCSG_ID, -- NUMBER(38) | NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS SUBSEQUENTLY UPDATED.
                IDR_INSRT_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHILE PERFORMING AN INSERT OPERATION.
                IDR_UPDT_TS -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN UPDATES ARE MADE TO ANY NON-PRIMARY KEY COLUMN.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_TXNMY_CD"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrTxnmyCdExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
