"""
==========
V2_MDCR_PRVDR_NCPDP_PRNT_ORG IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PRNT_ORG

Table Type: VIEW
Columns: 20
Source Pattern: %mdcr_prvdr%
Table Comment: THE NATIONAL COUNCIL FOR PRESCRIPTION DRUG PROGRAMS (NCPDP) MAINTAINED INFORMATION FOR HEADQUARTER ADDRESS INFORMATION FOR CHAINS, BUYING GROUPS OR THIRD PARTY CONTRACTING ORGANIZATIONS WHERE MULTIPLE RELATIONSHIP ENTITIES EXIST AND NEED TO BE LINKED TO A COMMON ORGANIZATION SUCH AS COMMON OWNERSHIP FOR SEVERAL CHAINS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrNcpdpPrntOrgExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrNcpdpPrntOrgExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_NCPDP_PRNT_ORG data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PRNT_ORG (VIEW)
    Columns: 20
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_ncpdp_prnt_org_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_NCPDP_PRNT_ORG export.
        
        Includes all 20 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NCPDP_PRNT_ORG_ID, -- TEXT(6) | NOT NULL | HEADQUARTER ADDRESS INFORMATION FOR CHAINS, BUYING GROUPS OR THIRD PARTY CONTRACTING ORGANIZATIONS WHERE MULTIPLE RELATIONSHIP ENTITIES EXIST AND NEED TO BE LINKED TO A COMMON ORGANIZATION SUCH AS COMMON OWNERSHIP FOR SEVERAL CHAINS.
                PRVDR_NCPDP_PRNT_NAME, -- TEXT(35) | NULL | THE NAME OF THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_LINE_1_ADR, -- TEXT(55) | NULL | THE FIRST ADDRESS LINE OF THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_LINE_2_ADR, -- TEXT(55) | NULL | THE SECOND ADDRESS LINE OF THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_INVLD_NAME, -- TEXT(30) | NULL | INVALID PARENT ORGANIZATION PLACE NAME. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_INVLD_STATE_CD, -- TEXT(2) | NULL | INVALID PARENT ORGANIZATION STATE CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_PRNT_INVLD_ZIP_CD, -- TEXT(9) | NULL | INVALID PARENT ORGANIZATION ZIP CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_NCPDP_PRNT_TEL_NUM, -- TEXT(10) | NULL | THE TELEPHONE NUMBER OF THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_EXTNSN_NUM, -- TEXT(5) | NULL | THE TELEPHONE EXTENSION NUMBER OF THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_FAX_NUM, -- TEXT(10) | NULL | THE FAX NUMBER OF THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_CNTCT_NAME, -- TEXT(30) | NULL | NAME OF THE PRIMARY CONTACT PERSON OF THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_TITLE_NAME, -- TEXT(30) | NULL | TITLE OF THE PRIMARY CONTACT PERSON FOR THE PARENT ORGANIZATION.
                PRVDR_NCPDP_PRNT_EMAIL_ADR, -- TEXT(50) | NULL | E-MAIL ADDRESS OF THE PRIMARY CONTACT PERSON FOR THE PARENT ORGANIZATION
                PRVDR_NCPDP_PRNT_NPI, -- TEXT(10) | NULL | NPI OF PARENT ORGANIZATION. THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS.
                PRVDR_NCPDP_PRNT_DLT_DT, -- DATE | NULL | THE DATE STAMPED BY NCPDP THAT THIS PARENT ORGANIZATION INFORMATION IS NO LONGER ACTIVE.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_NCPDP_PRNT_FED_TAX_NUM -- TEXT(15) | NULL | THE FEDERAL TAX ID, ALSO KNOWN AS EIN OR TIN, ASSIGNED TO THE PARENT ORGANIZATION ENTITY.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_PRNT_ORG"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrNcpdpPrntOrgExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
