"""
==========
V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK

Table Type: VIEW
Columns: 62
Source Pattern: %mdcr_prvdr%
Table Comment: A PBX (PROVIDER PART B EXTRACT) FILE THAT CONTAINS ENROLLMENT, DEMOGRAPHIC, CREDENTIAL, AND PAYEE INFORMATION FOR HEALTHCARE PROVIDERS THAT BILL MEDICARE PART B.   (PART B IS MEDICAL INSURANCE. IT HELPS PAY FOR DOCTORS FEES, OUTPATIENT HOSPITAL VISITS, AND OTHER MEDICAL SERVICES AND SUPPLIES THAT ARE NOT COVERED BY PART A.)   THESE PROVIDERS ARE GENERALLY CLASSIFIED AS “INDIVIDUAL PRACTITIONERS” (SUCH AS DOCTORS, CHIROPRACTORS, PHYSICAL THERAPISTS, PSYCHOLOGISTS, OSTEOPATHS, AND PATHOLOGISTS) OR AS “ORGANIZATIONAL PROVIDERS” (SUCH AS GROUP PRACTICES, MULTI-SPECIALTY CLINICS, AMBULANCE COMPANIES, CLINICAL LABORATORIES, MEDICAL SUPPLY COMPANIES, PUBLIC HEALTH AGENCIES, AND PORTABLE X-RAY SUPPLIERS)… TO NAME A FEW. PROVIDERS ARE REPRESENTED ON MEDICARE CLAIMS BY UP TO FOUR (4) DIFFERENT IDENTIFIERS, EACH OF WHICH (WHEN AVAILABLE) IS CARRIED ON THE PROVBX FILE.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrPbxCntrctrXwlkExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrPbxCntrctrXwlkExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK (VIEW)
    Columns: 62
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_pbx_cntrctr_xwlk_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK export.
        
        Includes all 62 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_PBX_EFCTV_DT, -- DATE | NOT NULL | THE DATE THAT THE PROVIDER DATA BECAME EFFECTIVE
                PRVDR_PBX_CNTRCTR_NUM, -- TEXT(5) | NOT NULL | A NUMBER ASSIGNED BY CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) IDENTIFYING A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC) AUTHORIZED TO PROCESS MEDICARE CLAIMS. REFERENCE TABLE: CLM_CNTRCTR_NUM
                CLM_CNTRCTR_NUM, -- TEXT(5) | NOT NULL | A NUMBER ASSIGNED BY CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) IDENTIFYING A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC) AUTHORIZED TO PROCESS MEDICARE CLAIMS. REFERENCE TABLE: CLM_CNTRCTR_NUM
                PRVDR_CLIA_NUM, -- TEXT(12) | NULL | THE PROVIDERÒ² CERTIFICATION NUMBER UNDER CLIA (CLINICAL LABORATORY IMPROVEMENT AMENDMENTS OF 1988). PROVIDERS MUST BE ACCREDITED BY A CMS-APPROVED ACCREDITATION ORGANIZATION IF THEY PERFORM CLINICAL LAB TESTS. CLIA NUMBERS CAN BE ISSUED TO AN INDIVIDUAL PRACTICING PHYSICIAN/PROVIDER FOR LAB WORK PERFORMED IN HIS/HER OFFICE; OR THE NUMBER CAN BE ASSIGNED TO A GROUP, CLINIC, OR FACILITY (AND ALL PHYSICIANS/PRACTITIONERS WITHIN THAT ORGANIZATION WOULD USE THE SAME CLIA NUMBER). ACCORDING TO CMS DOCUMENTATION, CLIA REQUIRES ALL ENTITIES THAT PERFORM EVEN ONE TEST, INCLUDING WAIVED TESTS ON ... MATERIALS DERIVED FROM THE HUMAN BODY FOR THE PURPOSE OF PROVIDING INFORMATION FOR THE DIAGNOSIS, PREVENTION OR TREATMENT OF ANY DISEASE OR IMPAIRMENT OF, OR THE ASSESSMENT OF THE HEALTH OF, HUMAN BEINGS TO MEET CERTAIN FEDERAL REQUIREMENTS. IF AN ENTITY PERFORMS TESTS FOR THESE PURPOSES, IT IS CONSIDERED UNDER CLIA TO BE A LABORATORY AND MUST REGISTER WITH THE CLIA PROGRAM. THIS REQUIREMENT EXTENDS TO INDIVIDUAL PHYSICIANS WHO PERFORM TESTS IN THEIR OFFICES, AS WELL AS TO LABORATORIES, RADIOLOGISTS, FACILITIES, ETC.
                PRVDR_DEATH_DT, -- DATE | NULL | DATE ON WHICH THE PROVIDER DIED, IF THE PROVIDER IS NOW DECEASED.
                PRVDR_GRDTN_YR_NUM, -- TEXT(4) | NULL | YEAR IN WHICH THE PROVIDER GRADUATED FROM MEDICAL SCHOOL OR OBTAINED A SIMILAR DEGREE (E.G., NURSING OR CHIROPRACTIC).
                PRVDR_GRP_NUM, -- TEXT(10) | NULL | ON AN INDIVIDUAL PROVIDERÒ² PROVBX RECORD (PROV-TYPE = 0), THE PROV-GROUP-NBR FIELD CONTAINS THE IDENTIFICATION NUMBER FOR THE GROUP OF WHICH THIS INDIVIDUAL PROVIDER IS A MEMBER. ELSEWHERE ON THE PROVBX FILE, THERE IS ANOTHER RECORD WITH A TYPE CODE OF Ó°Ò (FOR GROUP) IN WHICH THE SAME PROVIDER IDENTIFICATION NUMBER IS STORED AS THE PROV-NBR. THE PURPOSE OF CARRYING THE PROV-GROUP-NBR ON THE INDIVIDUAL MEMBERSÒ RECORDS IS SO USERS CAN USE THAT INFORMATION TO LOCATE THE CORRESPONDING GROUPÒ² RECORD. THE PROV-GROUP-NBR IS THE IDENTIFICATION NUMBER ASSIGNED TO THE GROUP BY THE LOCAL CARRIER/B-MAC. ALTHOUGH IN SOME CASES THIS ID IS USED AS THE PERFORMING/RENDERING PROVIDER ON CMS 1500 CLAIMS, GROUP PROVIDER NUMBERS ARE MORE OFTEN RESERVED FOR USE AS THE PAY-TO OR BILLING PROVIDER ON CLAIMS, IN WHICH CASE THE NUMBER IS USED BY MCS TO DETERMINE TO WHOM TO SEND PAYMENTS AND REMITTANCE ADVICES. THE PROV-GROUP-NBR IS NOT CARRIED ON NATIONAL CLAIMS HISTORY (NCH) IF IT IS USED AS THE PAY-TO OR BILLING PROVIDER. IF THE PROV-GROUP-NBR IS USED AS THE RENDERING PROVIDER, THEN IT WOULD BE CARRIED ON NCH IN THE FIELD NAMED ÓƒARRIER LINE PERFORMING PIN NUMBERÔ® TO SOME EXTENT, THE TERM Ó¦ROUP NUMBERÔ CAN BE MISLEADING. MANY Ó¦ROUP NUMBERSÔ ARE ASSIGNED TO INDIVIDUAL PRACTITIONERS WHO HAVE INCORPORATED THEIR BUSINESSES, AND PERHAPS THEY HAVE NURSE PRACTITIONERS OR PHYSICIAN ASSISTANTS WHO WORK FOR THEM AND ARE LINKED TOGETHER BY THE PROV-GROUP-NBR.
                PRVDR_GRP_PREX_NAME, -- TEXT(5) | NULL | TO ENSURE UNIQUENESS FOR EACH RECORD, THE PROVBX PROGRAM ADDS A PREFIX TO THE PROV-GROUP-NBR THAT IS COMPRISED OF (1) THE CMS-ISSUED THREE-POSITION BUSINESS SEGMENT INDICATOR (BSI) OF THE Ó®WNINGÔ CARRIER/B-MAC, (2) A FILLER VALUE OF 0 (ZERO), AND (3) A ONE-DIGIT COUNTER. CMS USES THE BSI AS THE ÓƒONTRACTOR WORKLOAD IDENTIFIERÔ TO INDICATE: 1. THE STATE JURISDICTION FOR THE CARRIER/B-MAC; AND 2. WHETHER THE CONTRACTOR IS RESPONSIBLE FOR PROCESSING MEDICARE PART B, PART A, HOME HEALTH+HOSPICE, OR DMEPOS CLAIMS. THE EXTRA Ó¢OUNTERÔ FIELD, WHICH WAS CREATED BY THE NATIONAL DATABASE TEAM, SERVES TO ENSURE UNIQUENESS FOR PROVIDER NUMBERS IN THE THREE STATES WHERE MORE THAN ONE CARRIER PROCESSES CLAIMS (E.G., CALIFORNIA, MISSOURI, AND NEW YORK).
                PRVDR_LAST_UPDT_DT, -- DATE | NULL | THE DATE ON WHICH THIS RECORD WAS LAST UPDATED IN THE MCS PROVIDER FILE. UPDATES CAN BE THE RESULT OF MANUAL ENTRIES IN MCS BY CARRIER PERSONNEL OR, MORE FREQUENTLY, BY THE AUTOMATED POSTING OF NEW INFORMATION FROM PECOS AND/OR THE NPI CROSSWALK FILE.
                PRVDR_LCNS_USPS_STATE_CD, -- TEXT(2) | NULL | IF A PROVIDER HAS A LICENSE NUMBER ON FILE, THIS FIELD INDICATES WHICH STATE ISSUED THE LICENSE. FROM THE GEO_USPS_STATE_CD TABLE TABLE, UNIQUE VALUE THAT IDENTIFIES A STATE. STATE CODE USED BY THE UNITED STATES POSTAL SERVICE TO IDENTIFY A STATE
                PRVDR_MDCR_ENRLMT_BGN_DT, -- DATE | NULL | DATE WHEN THE PROVIDERÒ² ENROLLMENT IN THE MEDICARE PROGRAM BECAME EFFECTIVE. THIS DATE IS SPECIFIC TO THE PIN (PROV-NBR) THAT IS THE KEY TO THIS RECORD. IF A PROVIDER HAS MORE THAN ONE PIN ON FILE, THERE WILL BE EFFECTIVE (AND END) DATES SPECIFIC TO EACH OF THE PROVIDERÒ² RECORDS.
                PRVDR_MDCR_ENRLMT_END_DT, -- DATE | NULL | DATE ON WHICH THIS PIN (PROV-NBR) WAS TERMINATED (E.G., WHEN THE PIN COULD NO LONGER BE USED TO RECEIVE PAYMENT FROM MEDICARE).
                PRVDR_NPI_NUM, -- TEXT(10) | NULL | THE PROVIDERÒ² 10-DIGIT NATIONAL PROVIDER IDENTIFIER (NPI). ASSIGNED BY THE NATIONAL PLAN AND PROVIDER ENUMERATION SYSTEM (NPPES), THE NPI IS BEING PHASED IN AS THE STANDARD IDENTIFIER USED BY PROVIDERS WHEN SUBMITTING MEDICARE CLAIMS. EFFECTIVE MARCH 1, 2008, PART B PROVIDERS MUST USE NPIS IN THE PERFORMING/RENDERING PROVIDER FIELD, THE PAY-TO PROVIDER FIELD, AND THE BILLING PROVIDER FIELD WHEN SUBMITTING CLAIMS TO MEDICARE FOR PAYMENT. EFFECTIVE MAY 23, 2008, NPIS WILL ALSO BE REQUIRED AS THE IDENTIFIERS FOR THE FOLLOWING Ó²ECONDARYÔ PROVIDER FIELDS ON PART B, DMEPOS, AND PART A CLAIMS: ORDERING PHYSICIAN, REFERRING PHYSICIAN, ATTENDING PHYSICIAN, OPERATING PHYSICIAN, OTHER PHYSICIAN, PURCHASED SERVICE PROVIDER, OR SERVICE FACILITY PROVIDER. DATA PROFILING SHOWS THAT DATA SEEMS TO MATCH IDR. SELECT * FROM CMS_VIEW_PRVDR_CDEV.V1_PRVDR WHERE PRVDR_NPI_NUM IN ( SELECT DISTINCT PBX_PROV_NPI FROM CMS_WORK_COMM_CDEV.PROV_EXTRACT_EXTERNAL_OUT_SM)
                PRVDR_NPI_SRC_ID, -- TEXT(1) | NULL | INDICATES THE SOURCE OF THE NPI NUMBER CARRIED IN THE PROV-NPI FIELD. DATA PROFILING AGAINST THE SAMPLE DATABASE SHOWS THESE VALUES: X, P, G, AND SPACES.
                PRVDR_PRCTC_1ST_NAME, -- TEXT(25) | NULL | FIRST NAME OF THE INDIVIDUAL PRACTITIONER.
                PRVDR_PRCTC_CITY_NAME, -- TEXT(28) | NULL | CITY IN WHICH THE PROVIDERÒ² PRACTICE IS PHYSICALLY LOCATED.
                PRVDR_PRCTC_GEO_SK, -- NUMBER(38) | NOT NULL | IDENTIFIER OF THE GEOGRAPHICAL AREA ASSOCIATED WITH THE PROVIDER PRACTICE LOCATION
                PRVDR_PRCTC_GEO_ZIP4_CD, -- TEXT(4) | NULL | THE ÓšIP PLUS 4Ô FOR THE PROVIDERÒ² PHYSICAL PRACTICE LOCATION. PER THE GEO_ZIP4_CD ATTRIBUTE, A FOUR DIGIT EXTENSION TO A ZIP CODE THAT REPRESENTS A SUBDIVISION FOR MAILING PURPOSES OF THE ZIP CODE.
                PRVDR_PRCTC_GEO_ZIP5_CD, -- TEXT(5) | NULL | THE FIVE-DIGIT ZIP CODE, WHERE THE PROVIDERÒ² PRACTICE IS PHYSICALLY LOCATED.
                PRVDR_PRCTC_LAST_NAME, -- TEXT(35) | NULL | LAST NAME OF THE INDIVIDUAL PRACTITIONER, INCLUDING A SUFFIX (IF AVAILABLE).
                PRVDR_PRCTC_LINE_1_ADR, -- TEXT(100) | NULL | FIRST LINE OF THE ADDRESS WHERE THE PROVIDERÒ² PRACTICE (OFFICE, FACILITY, STORE, CLINIC, ETC.) IS PHYSICALLY LOCATED.
                PRVDR_PRCTC_LINE_2_ADR, -- TEXT(100) | NULL | OPTIONAL SECOND LINE OF THE ADDRESS WHERE THE PROVIDERÒ² PRACTICE (OFFICE, FACILITY, STORE, CLINIC, ETC.) IS PHYSICALLY LOCATED.
                PRVDR_PRCTC_MDL_INITL_NAME, -- TEXT(1) | NULL | MIDDLE INITIAL OF THE INDIVIDUAL PRACTITIONER.
                PRVDR_PRCTC_ORG_NAME, -- TEXT(70) | NULL | ORGANIZATIONAL PRACTICE NAME FOR THE PIN (PROV-NBR) ON THIS RECORD. THIS FIELD IS GENERALLY USED FOR GROUP PRACTICES, CLINICS, PHARMACIES, AMBULATORY SURGERY CENTERS, AMBULANCE COMPANIES, OPTICIANS, AND OTHER TYPES OF NON-INDIVIDUAL ENTITIES/PROVIDERS. THIS FIELD SOMETIMES ALSO CONTAINS A PERSONÒ² NAME (EXAMPLE: JOHN Q SMITH MD, INC) WHEN THE INDIVIDUAL HAS INCORPORATED HIS/HER PRACTICE.
                PRVDR_PRCTC_TEL_NUM, -- TEXT(10) | NULL | TELEPHONE NUMBER FOR THE PROVIDERÒ² PRACTICE LOCATION.
                PRVDR_PRCTC_USPS_CNTY_CD, -- TEXT(3) | NULL | A THREE-DIGIT CODE THAT REPRESENTS THE COUNTY IN WHICH THE PROVIDERÒ² PRACTICE IS PHYSICALLY LOCATED.
                PRVDR_PBX_OBSLT_DT, -- DATE | NULL | THE DATE THAT THE PROVIDER DATA BECAME OBSOLETE.
                PRVDR_PYEE_LINE_1_ADR, -- TEXT(100) | NULL | FIRST LINE OF THE PAYEEÒ² ADDRESS.
                PRVDR_PYEE_1ST_NAME, -- TEXT(25) | NULL | FIRST NAME OF THE PAYEE (WHEN THE PAYEE IS A PERSON, AS OPPOSED TO BEING AN ORGANIZATION).
                PRVDR_PYEE_LINE_2_ADR, -- TEXT(100) | NULL | OPTIONAL SECOND LINE OF THE PAYEEÒ² ADDRESS.
                PRVDR_PYEE_CITY_NAME, -- TEXT(28) | NULL | CITY IN WHICH THE PAYEEÒ² OFFICE IS PHYSICALLY LOCATED.
                PRVDR_PYEE_GEO_SK, -- NUMBER(38) | NOT NULL | IDENTIFIER OF THE GEOGRAPHICAL AREA ASSOCIATED WITH THE PROVIDER PAYEE LOCATION
                PRVDR_PYEE_GEO_ZIP4_CD, -- TEXT(4) | NULL | THE ÓšIP PLUS 4Ô FOR THE PAYEEÒ² OFFICE LOCATION. PER THE GEO_ZIP4_CD ATTRIBUTE, A FOUR DIGIT EXTENSION TO A ZIP CODE THAT REPRESENTS A SUBDIVISION FOR MAILING PURPOSES OF THE ZIP CODE.
                PRVDR_PYEE_GEO_ZIP5_CD, -- TEXT(5) | NULL | THE FIVE-DIGIT ZIP CODE, WHERE THE PAYEEÒ² OFFICE IS PHYSICALLY LOCATED.
                PRVDR_PYEE_LAST_NAME, -- TEXT(35) | NULL | LAST NAME OF THE PAYEE (WHEN THE PAYEE IS A PERSON, AS OPPOSED TO BEING AN ORGANIZATION. INCLUDES A SUFFIX (IF AVAILABLE).
                PRVDR_PYEE_MDL_INITL_NAME, -- TEXT(1) | NULL | MIDDLE INITIAL FOR THE PAYEE (WHEN THE PAYEE IS A PERSON, AS OPPOSED TO BEING AN ORGANIZATION).
                PRVDR_PYEE_ORG_NAME, -- TEXT(70) | NULL | ORGANIZATIONAL LEGAL BUSINESS NAME FOR THE PAYEE ASSOCIATED WITH THIS PIN (PROV-NBR). THIS IS THE Ó°AY-TOÔ ENTITY THAT RECEIVES REIMBURSEMENT FOR THE SERVICES/SUPPLIES BILLED UNDER THE PROV-NBR ON THIS RECORD. IN 84% OF SUPERPES INDIVIDUAL PROVIDER RECORDS (PROV-TYPE = 0), THE PAYEE IS AN ORGANIZATION (RATHER THAN THE INDIVIDUAL PRACTITIONER).
                PRVDR_PYEE_TEL_NUM, -- TEXT(10) | NULL | TELEPHONE NUMBER FOR THE PAYEE (Ó°AY-TOÔ PROVIDER).
                PRVDR_SPCLTY_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) SPECIALTY OF A PROVIDER OR SUPPLIER. FOR EXAMPLE: 11 = INTERNAL MEDICINE 49 = AMBULATORY SURGICAL CENTER REFERENCE TABLE: CLM_PRVDR_SPCLTY_CD
                PRVDR_STATE_LCNSD_NUM, -- TEXT(12) | NULL | MANY TYPES OF PART B PROVIDERS ARE REQUIRED TO HOLD A CURRENT STATE-ISSUED LICENSE IN ORDER TO BE PERMITTED TO BILL MEDICARE. THIS FIELD CONTAINS THE LICENSE NUMBER OF RECORD FOR THE PROVIDER, ASSUMING THE PROVIDER IS ONE OF THE TYPES THAT NEEDS LICENSING. DEFINITION FROM PROVIDER STATE LICENSE NUMBER - CHAR(20). THE LICENSE NUMBER WHICH THE PROVIDER WAS ASSIGNED IN ASSOCIATION WITH THE TAXONOMY NUMBER GIVEN. [NPS] A NUMBER ASSIGNED BY A STATE OR TERRITORY TO AN INDIVIDUAL PROVIDER CERTIFYING THE PERSONS ABILITY TO PRACTICE MEDICINE WITHIN A RANGE OF SPECIALIZATION. [NPS]
                PRVDR_SUB_SPCLTY_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING THE CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) SPECIALTY OF A PROVIDER OR SUPPLIER. FOR EXAMPLE: 11 = INTERNAL MEDICINE 49 = AMBULATORY SURGICAL CENTER REFERENCE TABLE: CLM_PRVDR_SPCLTY_CD
                PRVDR_TIN_NUM, -- TEXT(9) | NULL | TAX IDENTIFICATION NUMBER FOR THIS PROVIDER (I.E., THE TIN THAT IS USED FOR PAYMENT/TAX PURPOSES FOR THE PROVIDER IDENTIFIED BY THE PROV-NBR-KEY ON THIS RECORD). MORE THAN ANY OTHER FIELD, THE TIN GIVES A GENERALLY RELIABLE METHOD OF LINKING TOGETHER ALL OF THE PROVIDERS WHO ARE MEMBERS OF A GROUP, SINCE THEY WILL ALL SHARE THE SAME TIN. THE TIN FIELD CONTAINS AN IRS-ISSUED NUMBER THAT IDENTIFIES TO WHOM MEDICARE PAYMENT IS MADE. EVERY PART B NCH CLAIM CONTAINS A TIN, EVEN THOUGH THE NCH CLAIM RECORDS DO NOT CARRY PAY-TO OR BILLING PROVIDER IDS.
                PRVDR_TYPE_IND, -- TEXT(1) | NULL | INDICATES IF THIS RECORD IS FOR AN INDIVIDUAL PRACTITIONER OR IF IT IS FOR A GROUP.
                PRVDR_UPIN_NUM, -- TEXT(6) | NULL | A UNIQUE PROVIDER IDENTIFICATION NUMBER (UPIN) ASSIGNED TO A PROVIDER ELIGIBLE TO ORDER OR REFER SERVICES.
                PRVDR_PIN_NUM, -- TEXT(14) | NOT NULL | A PROVIDER IDENTIFICATION NUMBER (PIN) ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_CNTRCTR_USPS_STATE_CD, -- TEXT(2) | NOT NULL | STATE CODE USED BY THE UNITED STATES POSTAL SERVICE TO IDENTIFY A STATE.
                PRVDR_CNTRCTR_TYPE_CD, -- TEXT(1) | NULL | THE CONTRACTOR TYPE CODE (ALWAYS B, (INDICATING THAT THE CARRIER/B-MAC PROCESSES PART B CLAIMS)
                PRVDR_SBCNTRCTR_IND, -- TEXT(1) | NULL | A SEQUENCE NUUMBER THAT WAS CREATED BY VIPS, WHICH SERVES TO ENSURE UNIQUENESS FOR PROVIDER NUMBERS IN THE THREE STATES WHERE MORE THAN ONE CARRIER PROCESSES CLAIMS (E.G., CALIFORNIA, MISSOURI, AND NEW YORK).
                PRVDR_PRCTC_USPS_STATE_CD, -- TEXT(2) | NOT NULL | U.S. STATE OR TERRITORY IN WHICH THE PROVIDERÒ² PRACTICE IS PHYSICALLY LOCATED. PER THE GEO_USPS_STATE_CD ATTRIBUTE, STATE CODE USED BY THE UNITED STATES POSTAL SERVICE TO IDENTIFY A STATE
                PRVDR_PYEE_USPS_STATE_CD, -- TEXT(2) | NOT NULL | U.S. STATE OR TERRITORY IN WHICH THE PAYEEÒ² OFFICE IS PHYSICALLY LOCATED. PER THE GEO_USPS_STATE_CD ATTRIBUTE, STATE CODE USED BY THE UNITED STATES POSTAL SERVICE TO IDENTIFY A STATE
                PRVDR_HBP_IND, -- TEXT(1) | NULL | INDICATES WHETHER OR NOT THIS IS A HOSPITAL-BASED PHYSICIAN. HBPS GENERALLY ARE SPECIALISTS SUCH AS ANESTHESIOLOGISTS, EMERGENCY ROOM PHYSICIANS, PATHOLOGISTS, RADIOLOGISTS, AND TEACHING PHYSICIANS.
                PRVDR_MDCR_PRTCPTN_IND, -- TEXT(1) | NULL | AN INDICATION THAT THE PROVIDER PARTICIPATES IN THE MEDICARE PROGRAM.
                PRVDR_PBX_CRDNTL_CD, -- TEXT(5) | NULL | ABBREVIATION FOR THE PROVIDERÒ² Ó¢REDENTIALSÔ OR THE TYPE OF PRACTICE/BUSINESS REPRESENTED BY THE PROVIDER. EXAMPLES: MD, DO, PHD, CSW.
                PRVDR_PBX_MDCL_SCHL_CD, -- TEXT(5) | NULL | MEDICAL SCHOOL CODE FOR THE INSTITUTION FROM WHICH THE PROVIDER GRADUATED. PRESUMABLY, THIS FIELD CONTAINS CODES FOR THE FOLLOWING TYPES OF SCHOOLS: MEDICAL AND OSTEOPATHIC, CHIROPRACTIC, PODIATRIC, AND OPTOMETRIC.
                PRVDR_PBX_STRUC_CD, -- TEXT(2) | NULL | INDICATES THE STRUCTURE AND FINANCIAL CHARACTERISTICS OF THE PROVIDERÒ² PRACTICE/BUSINESS.
                PRVDR_PBX_STUS_CD, -- TEXT(2) | NULL | A STATUS OF THE RECORD (IF DEACTIVATED); OR A STATUS OF THE PROVIDERÒ² PRACTICE (E.G., THE PROVIDERÒ² STATUS IS A RESIDENT, INTERN, IN PRACTICE, OR OPTED OUT OF THE MEDICARE PROGRAM).
                PRVDR_GRP_CNTRCTR_TYPE_CD, -- TEXT(1) | NULL | THE CONTRACTOR GROUP TYPE CODE (ALWAYS B, (INDICATING THAT THE CARRIER/B-MAC PROCESSES PART B CLAIMS)
                PRVDR_GRP_SBCNTRCTR_SQNC, -- TEXT(1) | NULL | A SEQUENCE NUMBER WHICH SERVES TO ENSURE UNIQUENESS FOR PROVIDER GROUP NUMBERS IN STATES WHERE MORE THAN ONE CARRIER PROCESSES CLAIMS (E.G., CALIFORNIA, MISSOURI, AND NEW YORK).
                PRVDR_ID_PREX_NUM, -- TEXT(5) | NULL | TO ENSURE UNIQUENESS FOR EACH RECORD, THE PROVBX PROGRAM ADDS A PREFIX TO THE PROV-NBR THAT IS COMPRISED OF (1) THE CMS-ISSUED THREE-POSITION BUSINESS SEGMENT INDICATOR (BSI) OF THE Ó®WNINGÔ CARRIER/B-MAC, (2) A ONE-DIGIT ZERO-FILLED FILLER, AND (3) A ONE-DIGIT COUNTER. CMS USES THE BSI AS THE ÓƒONTRACTOR WORKLOAD IDENTIFIERÔ TO INDICATE: 1. THE STATE JURISDICTION FOR THE CARRIER/B-MAC; AND 2. WHETHER THE CONTRACTOR IS RESPONSIBLE FOR PROCESSING MEDICARE PART B, PART A, HOME HEALTH+HOSPICE, OR DMEPOS CLAIMS. THE EXTRA Ó¢OUNTERÔ FIELD, WHICH WAS CREATED BY VIPS, SERVES TO ENSURE UNIQUENESS FOR PROVIDER NUMBERS IN STATES WHERE MORE THAN ONE CARRIER PROCESSES CLAIMS (E.G., CALIFORNIA, MISSOURI, AND NEW YORK).
                PRVDR_GRP_CNTRCTR_STATE_CD, -- TEXT(2) | NULL | STATE CODE USED BY THE UNITED STATES POSTAL SERVICE TO IDENTIFY A STATE. VALUE WILL BE A VALID U.S.P.S. ALPHA STATE CODE (OR TERRITORY) AS USED BY CMS IN CARRIER/B-MAC BSIS, OR THE VALUE WILL BE Ó…RÔ WHEN THE CONTRACTOR-GROUP-ID ON THE RECORD IS NOT FOUND ON THE PROVBX CONTRACTOR CROSSWALK TABLE.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PBX_CNTRCTR_XWLK"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrPbxCntrctrXwlkExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
