"""
==========
V2_MDCR_PRVDR_SPCL_PMT_AUDT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_SPCL_PMT_AUDT

Table Type: VIEW
Columns: 27
Source Pattern: %mdcr_prvdr%
Table Comment: THE SPECIAL PAYMENT CHILD RECORD IS CREATED TO INCLUDE SPECIAL PAYMENT INFORMATION. PECOS WILL SEND BOTH HISTORIC AND CURRENT SPECIAL PAYMENT ADDRESS INFORMATION. IT IS SENT ALONG WITH THE PRACTICE LOCATION CHILD RECORD. PECOS COLLECTS DOMESTIC AND FOREIGN SPECIAL PAYMENT ADDRESS.  PECOS: EACH INSTANCE CONTAINS THE ADDRESS IDENTIFIER WHERE THE PROVIDER WANTS ITS MEDICARE PAYMENTS TO BE SENT.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrSpclPmtAudtExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrSpclPmtAudtExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_SPCL_PMT_AUDT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_SPCL_PMT_AUDT (VIEW)
    Columns: 27
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_spcl_pmt_audt_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_SPCL_PMT_AUDT export.
        
        Includes all 27 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_ENRLMT_ID, -- TEXT(15) | NOT NULL | PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
                PRVDR_PECOS_SK, -- NUMBER(38) | NOT NULL | A UNIQUE IDENTIFIER ASSIGNED BY IDR
                PRVDR_SPCL_PMT_BGN_DT, -- DATE | NULL | BEGIN DATE FOR SPECIAL PAYMENTS IF DIFFERENT THEN BUSINESS ADDRESS.
                PRVDR_SPCL_PMT_END_DT, -- DATE | NULL | END DATE FOR SPECIAL PAYMENTS IF DIFFERENT THEN BUSINESS ADDRESS.
                PRVDR_SPCL_LINE_1_ADR, -- TEXT(55) | NOT NULL | FIRST LINE OF THE PROVIDER CORRESPONDENCE ADDRESS FOR SPECIAL PAYMENTS IF DIFFERENT THEN BUSINESS ADDRESS.
                PRVDR_SPCL_LINE_2_ADR, -- TEXT(55) | NULL | SECOND LINE OF THE PROVIDER CORRESPONDENCE ADDRESS FOR SPECIAL PAYMENTS IF DIFFERENT THEN BUSINESS ADDRESS.
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_SPCL_INVLD_PLC_NAME, -- TEXT(30) | NULL | THE INVALID PLACE NAME OF A SPECIAL PAYMENT LOCATION. POPULATED WHEN THE PLACE NAME SUPPLIED BY THE SOURCE FOR A GIVEN ZIP CODE DOES NOT MATCH THE PLACE NAME FOR THE ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA.
                PRVDR_SPCL_INVLD_STATE_CD, -- TEXT(2) | NULL | STATE CODE OF SPECIAL PAYMENT ADDRESS. POPULATED ONLY WHEN THE STATE CODE SUPPLIED BY THE PECOS SYSTEM DIFFERS FROM THE PLACE NAME ASSOCIATED WITH THE CORRESPONDING ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA. PECOS IS NOT THE AUTHORITATIVE SOURCE OF ZIP CODE DATA.
                PRVDR_SPCL_INVLD_ZIP_CD, -- TEXT(9) | NULL | INNVALID ZIP CODE OF SPECIAL PAYMENT. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_SPCL_FRGN_STATE_NAME, -- TEXT(30) | NULL | THE NAME OF THE FOREIGN STATE FOR SPECIAL PAYMENTS IF DIFFERENT THEN THE BUSINESS ADDRESS.
                PRVDR_SPCL_FRGN_PSTL_CD, -- TEXT(15) | NULL | FOREIGN POSTAL CODE FOR SPECIAL PAYMENTS IF DIFFERENT THEN THE BUSINESS ADDRESS.
                PRVDR_SPCL_CNTRY_NAME, -- TEXT(30) | NOT NULL | FOREIGN COUNTRY NAME FOR SPECIAL PAYMENTS IF DIFFERENT THEN THE BUSINESS ADDRESS.
                PRVDR_SPCL_PRCTC_LCTN_KEY, -- TEXT(20) | NOT NULL | A UNIQUE KEY USED TO IDENTIFY A PRACTICE LOCATION FOR SPECIAL PAYMENTS IF DIFFERENT THEN THE BUSINESS ADDRESS.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_RPT_SW, -- TEXT(1) | NULL | AN INDICATION THAT THERE IS A UNIQUENESS PROBLEM IN THE SOURCE DATA
                PRVDR_SPCL_PYMT_UPDT_DT, -- DATE | NULL | DATE DATA WAS CORRECTED IN SOURCE
                PRVDR_DRVD_END_DT, -- DATE | NOT NULL | END DATE OF INPUT FILE
                PRVDR_PAC_ID, -- TEXT(10) | NULL | UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
                PRVDR_OSCAR_NUM, -- TEXT(10) | NULL | AN ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_SPCL_CREAT_DT, -- DATE | NULL | CREATION DATE OF PRACTICE LOCATION
                PRVDR_SPCL_FRGN_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THE ADDRESS IS A FOREIGN ADDRESS.
                PRVDR_ENRLMT_CNTRCTR_ID, -- TEXT(5) | NOT NULL | UNIQUE NUMBER THAT IDENTIFIES A MEDICARE CONTRACTOR.
                PRVDR_ENRLMT_CREAT_DT, -- DATE | NOT NULL | DATE THE RECORD WAS CREATED (MM/DD/YYYY)
                PRVDR_SPCL_PYMT_CREAT_DT -- DATE | NULL | DATE DATA WAS CREATED IN SOURCE
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_SPCL_PMT_AUDT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrSpclPmtAudtExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
