"""
==========
V2_MDCR_PRVDR_PRCTC_LCTN_AUDT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT

Table Type: VIEW
Columns: 42
Source Pattern: %mdcr_prvdr%
Table Comment: AN AUDIT OF THE PROVIDER PRACTION LOCATION INFORMATION.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrPrctcLctnAudtExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrPrctcLctnAudtExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_PRCTC_LCTN_AUDT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT (VIEW)
    Columns: 42
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_prctc_lctn_audt_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_PRCTC_LCTN_AUDT export.
        
        Includes all 42 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_ENRLMT_ID, -- TEXT(15) | NOT NULL | PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
                PRVDR_PECOS_SK, -- NUMBER(38) | NOT NULL | A UNIQUE IDENTIFIER ASSIGNED BY IDR
                PRVDR_PRCTC_AUDT_BGN_DT, -- DATE | NULL | THE EFFECTIVE DATE OF A PRACTICE LOCATION.
                PRVDR_PRCTC_AUDT_END_DT, -- DATE | NULL | THE TERMINATION DATE OF A PRACTICE LOCATION
                PRVDR_PRCTC_AUDT_NAME, -- TEXT(70) | NOT NULL | THE NAME OF THE PRACTICE LOCATION. ALSO REFERRED TO AS THE DOING BUSINESS AS (DBA) NAME.
                PRVDR_PRCTC_AUDT_LINE_1_ADR, -- TEXT(55) | NOT NULL | THE FIRST ADDRESS LINE OF A PRACTICE LOCATION.
                PRVDR_PRCTC_AUDT_LINE_2_ADR, -- TEXT(55) | NULL | THE SECOND ADDRESS LINE OF A PRACTICE LOCATION.
                GEO_SK, -- NUMBER(38) | NULL | IDENTIFIER OF THE GEOGRAPHICAL AREA ASSOCIATED WITH THE PROVIDER.
                GEO_AUDT_ZIP4_CD, -- TEXT(4) | NULL | A FOUR DIGIT EXTENSION TO A ZIP CODE THAT REPRESENTS A SUBDIVISION FOR MAILING PURPOSES OF THE ZIP CODE.
                PRVDR_AUDT_INVLD_PLC_NAME, -- TEXT(30) | NULL | THE INVALID PLACE NAME OF A PRACTICE LOCATION. POPULATED WHEN THE PLACE NAME SUPPLIED BY THE SOURCE FOR A GIVEN ZIP CODE DOES NOT MATCH THE PLACE NAME FOR THE ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA.
                PRVDR_AUDT_INVLD_STATE_CD, -- TEXT(2) | NULL | THE INVALID STATE CODE OF A PRACTICE LOCATION. POPULATED WHEN THE STATE CODE SUPPLIED BY THE SOURCE FOR A GIVEN ZIP CODE DOES NOT MATCH THE STATE CODE FOR THE ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA.
                PRVDR_AUDT_INVLD_ZIP_CD, -- TEXT(9) | NULL | INNVALID ZIP CODE OF PRACTICE LOCATION. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_PRCTC_AUDT_PHNE_NUM, -- TEXT(20) | NOT NULL | THE TELEPHONE NUMBER OF A PRACTICE LOCATION
                PRVDR_PRCTC_AUDT_FAX_NUM, -- TEXT(20) | NULL | THE FAX NUMBER OF A PRACTICE LOCATION.
                PRVDR_PRCTC_AUDT_EMAIL_ADR, -- TEXT(80) | NULL | THE EMAIL ADDRESS OF A PRACTICE LOCATION.
                PRVDR_PRCTC_AUDT_LCTN_KEY, -- TEXT(20) | NOT NULL | UNIQUE KEY USED TO IDENTIFY A PRACTICE LOCATION.
                PRVDR_SK, -- NUMBER(18) | NULL | AN IDR ASSIGNED SURROGATE KEY USED TO IDENTIFY A PARTY ENGAGED IN ACTIVITY RELATED TO CMS.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_AUDT_RPT_SW, -- TEXT(1) | NULL | AN INDICATION THAT THERE IS A UNIQUENESS PROBLEM IN THE SOURCE DATA
                PRVDR_DRVD_END_DT, -- DATE | NOT NULL | END DATE OF INPUT FILE
                PRVDR_CLIA_NUM, -- TEXT(15) | NULL | CLIA NUMBER ASSOCIATED WITH THAT PRACTICE LOCATION. (CLINICAL LABORATORY IMPROVEMENT ACT)
                PRVDR_PRCTC_CLM_PIN_NUM, -- TEXT(10) | NULL | CLAIMS SYSTEM PIN
                PRVDR_PRCTC_CREAT_DT, -- DATE | NOT NULL | SYSTEM GENERATED NUMBER THAT IDENTIFIES A PRACTICE LOCATION RECORD.
                PRVDR_PRCTC_EXTNSN_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THE PRACTICE LOCATION IS AN OUTPATIENT PHYSICAL THERAPY EXTENSION SITE.
                PRVDR_PRCTC_HHA_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS AN HHA BRANCH. (ONLY APPLICABLE FOR HOSPITALS AND HHAS)
                PRVDR_PRCTC_LCTN_TYPE_CD, -- TEXT(1) | NULL | UNIQUE VALUE THAT IDENTIFIES WHETHER THE ORGANIZATION FURNISHES HEALTH CARE SERVICES FROM A PORTABLE UNIT OR MOBILE FACILITY. USES P, O, B, AND NULL TO REPRESENT PRACTICE LOCATION, BASE OF OPERATIONS, AND BOTH RESPECTIVELY.
                PRVDR_PRCTC_NPI_SW, -- TEXT(1) | NULL | NPI INDICATOR
                PRVDR_PRCTC_OTHR_DESC, -- TEXT(60) | NULL | TYPE OF HEALTH CARE FACILITY THAT USES THIS PRACTICE LOCATION.
                PRVDR_PRCTC_OTHR_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS A HEALTH CARE FACILITY OTHER THAN WHAT IS LISTED ON THE FORM.
                PRVDR_PRCTC_PRMRY_LCTN_SW, -- TEXT(1) | NULL | PRIMARY PRACTICE LOCATION IND.
                PRVDR_PRCTC_PSYCH_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS A HOSPITAL PSYCHIATRIC UNIT. (ONLY APPLICABLE FOR HOSPITALS AND HHAS)
                PRVDR_PRCTC_REHAB_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS A HOSPITAL REHABILITATION UNIT. (ONLY APPLICABLE FOR HOSPITALS AND HHAS)
                PRVDR_PRCTC_RRB_PIN_NUM, -- TEXT(10) | NULL | RAILROAD BOARD PIN
                PRVDR_PRCTC_RRB_SW, -- TEXT(1) | NULL | RAILROAD BOARD INDICATOR
                PRVDR_PRCTC_SB_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THE PRACTICE LOCATION HAS A SWING BED UNIT.
                PRVDR_PAC_ID, -- TEXT(20) | NULL | UNIQUE NUMBER THAT IDENTIFIES A PECOS ASSOCIATE.
                PRVDR_ENRLMT_CNTRCTR_ID, -- TEXT(5) | NOT NULL | UNIQUE NUMBER THAT IDENTIFIES A MEDICARE CONTRACTOR.
                PRVDR_ENRLMT_CREAT_DT, -- DATE | NOT NULL | DATE THE RECORD WAS CREATED (MM/DD/YYYY)
                PRVDR_INVLD_NPI_NUM, -- TEXT(15) | NULL | AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.
                PRVDR_PRCTC_AUDT_CREAT_DT, -- DATE | NULL | DATE DATA WAS CREATED IN SOURCE
                PRVDR_PRCTC_AUDT_UPDT_DT -- DATE | NULL | DATE DATA WAS CORRECTED IN SOURCE
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN_AUDT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrPrctcLctnAudtExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
