"""
==========
V2_MDCR_PRVDR_OF_SRVC_HHA_ASC_HOSPC IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_HHA_ASC_HOSPC

Table Type: VIEW
Columns: 85
Source Pattern: %mdcr_prvdr%
Table Comment: A PROVIDER AS REPORTED IN THE PROVIDER OF SERVICES (POS) HOME HEALTH AGENCY, AMBULATORY SURGICAL CENTER, AND HOSPICE EXTRACT, CREATED FROM THE QIES (QUALITY IMPROVEMENT EVALUATION SYSTEM) DATABASE.  CONTAINS AN INDIVIDUAL RECORD FOR EACH MEDICARE-APPROVED PROVIDER AND IS UPDATED QUARTERLY.  THE DATA INCLUDES INFORMATION ON PROVIDER DEMOGRAPHIC AND ASSOCIATED CERTIFICATION INFORMATION, NAME, ADDRESS, AND OTHER CHARACTERISTICS OF THE PARTICIPATING INSTITUTION PROVIDERS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrOfSrvcHhaAscHospcExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrOfSrvcHhaAscHospcExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_OF_SRVC_HHA_ASC_HOSPC data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_HHA_ASC_HOSPC (VIEW)
    Columns: 85
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_of_srvc_hha_asc_hospc_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_OF_SRVC_HHA_ASC_HOSPC export.
        
        Includes all 85 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_OSCAR_NUM, -- TEXT(10) | NOT NULL | AN ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_OF_SRVC_EFCTV_DT, -- DATE | NOT NULL | THE DATE THAT THE PROVIDER DATA BECAME EFFECTIVE.
                PRVDR_OF_SRVC_HHA_ASC_HOSPC_CD, -- TEXT(3) | NOT NULL | IDENTIFIES THE TYPE OF PROVIDER PARTICIPATING IN THE MEDICARE/MEDICAID PROGRAM. REFERENCE TABLE: PRVDR_OF_SRVC_HHA_ASC_HOSPC_CD
                POS_PRCSG_DATE, -- DATE | NULL | THIS IS THE DATE THE QUERY FOR THE FILE WAS RAN, AND DATA POPULATING THE FILE WAS RETRIEVED.
                POS_PRVDR_SBTYP_ID, -- NUMBER(38) | NULL | IDENTIFIES THE SUBTYPE OF THE PROVIDER, WITHIN THE PRIMARY CATEGORY. USED IN REPORTING TO SHOW THE BREAKDOWN OF PROVIDER CATEGORIES.
                PRVDR_FAC_CTGRY_CD, -- TEXT(2) | NULL | A CODE TO INDICATE THE CATEGORY THAT REPRESENTS THE TYPE OF FACILITY. REFERENCE TABLE: PRVDR_FAC_CTGRY_CD
                PRVDR_CRTFCTN_SRVY_ACTN_DESC, -- TEXT(100) | NOT NULL | DESCRIPTION OF A CODE TO IDENTIFY THE TYPE OF CATEGORY TERMINATION ACTION PERFORMED BY EITHER THE CMS REGIONAL OFFICE OR THE SINGLE STATE AGENCY - VOLUNTARY, INVOLUNTARY, OR OTHER
                POS_FED_CRTFCTN_STUS_ID, -- TEXT(1) | NULL | THE ID CODE OF THE FEDERAL CERTIFICATION STATUS OF THE PROVIDER. VALID VALUES: 3 = 4 =
                POS_FED_CRTFCTN_STUS_NAME, -- TEXT(20) | NULL | THE NAME OF THE FEDERAL CERTIFICATION STATUS OF THE PROVIDER.
                POS_OWNRSHP_CNTL_TYPE, -- TEXT(50) | NULL | INDICATES THE OWNERSHIP TYPE OF THE PROVIDER.
                PRVDR_CHOW_SW, -- TEXT(1) | NULL | INDICATES IF THE HOME HEALTH AGENCY HAS UNDERGONE A CHANGE OF OWNERSHIP SINCE THE LAST SURVEY. VALID VALUES: Y = HOME HEALTH AGENCY HAS UNDERGONE A CHANGE OF OWNERSHIP N = HOME HEALTH AGENCY HAS NOT UNDERGONE A CHANGE OF OWNERSHIP ~ = UNAVAILABLE
                PRVDR_OF_SRVC_ACRDTN_CD, -- TEXT(2) | NOT NULL | INDICATES THE ACCREDITING ORGANIZATION DEEMING THE PROVIDER. IF A PROVIDER IS DEEMED BY MULTIPLE ACCREDITING ORGANIZATIONS THEN THE ACCREDITING ORGANIZATION WITH THE EARLIEST ACTIVE DEEMING EFFECTIVE DATE IS DISPLAYED IN THIS FIELD. REFERENCE TABLE: PRVDR_OF_SRVC_ACRDTN_CD
                PRVDR_MDCR_HOSPC_PRVDR_NUM, -- TEXT(10) | NULL | IF THE AGENCY ALSO PARTICIPATES IN THE MEDICARE PROGRAM AS A HOSPICE, THE HOSPICE PROVIDER NUMBER.
                PRVDR_ACUTE_RESP_CARE_CD, -- TEXT(1) | NULL | A CODE TO IDENTIFY THE TYPE OF ALTERNATIVE INPATIENT CARE RENDERED BY THE HOSPICE PROVIDER. - ACUTE AND/OR RESPITE SHORT TERM INPATIENT CARE. REFERENCE TABLE: PRVDR_ACUTE_RESP_CARE_CD
                POS_APLNC_EQUIP_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW APPLIANCE AND EQUIPMENT SERVICES ARE PROVIDED BY A HOME HEALTH AGENCY. REFERENCE TABLE: PRVDR_SRVC_CD
                POS_ASC_BGN_SRVC_DT, -- DATE | NULL | DATE INDICATING WHEN THE AMBULATORY SURGICAL CENTER BEGAN PROVIDING HEALTHCARE SERVICES. IF DATE IS NOT AVAILABLE, THIS DATE WILL BE SET TO 01/01/1000. IF THIS DATE IS NOT APPLICABLE THIS COLUMN WILL BE NULL.
                PRVDR_BRNCH_CNT, -- NUMBER(7,2) | NULL | NUMBER OF BRANCHES OPERATED BY THE HOME HEALTH AGENCY.
                PRVDR_BRNCH_OPRTN_SW, -- TEXT(1) | NULL | INDICATES IF THE HOME HEALTH AGENCY OPERATES ANY BRANCHES. VALID VALUES: Y = FACILITY OPERATES ANY BRANCHES N = FACILITY DOES NOT OPERATE ANY BRANCHES
                PRVDR_CNSLNG_SRVC_CD, -- TEXT(1) | NOT NULL | INDICATES HOW COUNSELING SERVICES ARE PROVIDED BY THE HOSPICE. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_CNSLR_EMPLEE_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT COUNSELORS EMPLOYED BY THE HOSPICE.
                PRVDR_FTE_CNSLR_VLNTR_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT COUNSELORS VOLUNTEERING IN A HOSPICE.
                PRVDR_FTE_DIETN_EMPLEE_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT DIETITIANS EMPLOYED BY A PROVIDER.
                PRVDR_DNTL_SRGRY_SW, -- TEXT(1) | NULL | INDICATES IF DENTAL SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES DENTAL SURGERY IS OFFERED N = NO DENTAL SURGERY IS NOT OFFERED
                PRVDR_FLTM_EMPLEE_CNT, -- NUMBER(8,2) | NULL | TOTAL NUMBER OF FULL-TIME EQUIVALENT EMPLOYEES OF A PROVIDER.
                PRVDR_ENDSCPY_SRGRY_SW, -- TEXT(1) | NULL | INDICATES IF ENDOSCOPY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES, ENDOSCOPY SURGERY IS OFFERED N = ENDOSCOPY SURGERY IS NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_SRGRY_FT_SW, -- TEXT(1) | NULL | INDICATES IF PODIATRIC SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES PODIATRIC SURGERY IS OFFERED N = PODIATRIC SURGERY IS NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_FTE_HHA_EMPLEE_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT HOME HEALTH AIDES EMPLOYED BY A HOME HEALTH AGENCY.
                PRVDR_HOSPC_AIDE_EMPLEE_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT AIDES EMPLOYED BY THE HOSPICE.
                POS_HH_AIDE_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW HOME HEALTH AIDE SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                POS_HH_AIDE_TRNG_PGM_CD, -- TEXT(30) | NOT NULL | INDICATES HOW THE AGENCY PROVIDES HOME HEALTH AIDE TRAINING AND COMPETENCY EVALUATION PROGRAMS.
                PRVDR_FTE_HHA_VLNTR_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT AIDES VOLUNTEERING IN A HOSPICE.
                PRVDR_FTE_HMMKR_EMPLEE_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT HOMEMAKERS EMPLOYED BY THE HOSPICE.
                PRVDR_HMMKR_SRVC_CD, -- TEXT(1) | NOT NULL | INDICATES HOW HOMEMAKER SERVICES ARE PROVIDED BY THE HOSPICE. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_HMMKR_VLNTR_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT HOMEMAKERS VOLUNTEERING IN A HOSPICE.
                POS_HOSPC_TYPE, -- TEXT(50) | NULL | INDICATES THE TYPE OF HOSPICE.
                POS_INTRN_RSDNT_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW INTERN AND RESIDENT SERVICES ARE PROVIDED BY A HOME HEALTH AGENCY. REFERENCE TABLE: PRVDR_SRVC_CD
                POS_LAB_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW LABORATORY SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_LPN_LVN_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT LICENSED PRACTICAL OR VOCATIONAL NURSES EMPLOYED BY A PROVIDER.
                PRVDR_FTE_LPN_LVN_CNTRCT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT LICENSED PRACTICAL OR VOCATIONAL NURSES VOLUNTEERING IN THE HOSPICE.
                POS_MDCL_SCL_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW MEDICAL SOCIAL SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_MSW_EMPLEE_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT MEDICAL SOCIAL WORKERS EMPLOYED BY A PROVIDER.
                PRVDR_FTE_MSW_VLNTR_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT MEDICAL SOCIAL WORKERS VOLUNTEERING IN THE HOSPICE.
                PRVDR_MDCL_SUPLY_SRVC_CD, -- TEXT(1) | NOT NULL | INDICATES HOW MEDICAL SUPPLY SERVICES ARE PROVIDED BY THE HOSPICE. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_MDCR_HOSPC_SW, -- TEXT(1) | NULL | INDICATES IF THE HOME HEALTH AGENCY ALSO PARTICIPATES IN THE MEDICARE PROGRAM AS A HOSPICE. VALID VALUES: Y = YES HHA PARTICIPATES IN THE MEDICARE PROGRAM AS A HOSPICE N = HHA DOES NOT PARTICIPATE IN MEDICARE PROGRAM AS A HOSPICE ~ = NOT AVAILABLE/NOT APPLICABLE
                POS_NRSNG_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW NURSING SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                POS_NTRTNL_GDNC_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW NUTRITIONAL GUIDANCE SERVICES ARE PROVIDED BY A HOME HEALTH AGENCY. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_SRGRY_OB_GYN_SW, -- TEXT(1) | NULL | INDICATES IF OBSTETRICS/GYNECOLOGY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES OBSTETRICS/GYNECOLOGY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. N = OBSTETRICS/GYNECOLOGY SURGERY IS NOT OFFERED BY AN AMBULATORY SURGICAL CENTER. ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_FTE_OT_TOT_CNT, -- NUMBER(8,2) | NULL | TOTAL NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPISTS EMPLOYED BY A PROVIDER.
                PRVDR_OR_CNT, -- TEXT(20) | NULL | NUMBER OF OPERATING ROOMS IN AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_OPTHMLGY_SW, -- TEXT(1) | NULL | INDICATES IF OPHTHALMOLOGIC SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES, OPHTHALMOLOGIC SURGERY IS OFFERED N = OPHTHALMOLOGIC SURGERY IS NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_SRGRY_ORTHO_SW, -- TEXT(1) | NULL | INDICATES IF ORTHOPEDIC SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES, ORTHOPEDIC SURGERY IS OFFERED N = ORTHOPEDIC SURGERY IS NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                POS_OT_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW OCCUPATIONAL THERAPY SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_OTHR_SRGRY_SW, -- TEXT(1) | NULL | INDICATES IF OTHER SURGERY TYPES ARE PERFORMED AT AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES, OTHER SURGERY TYPES ARE OFFERED N = OTHER SURGERY TYPES ARE NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                POS_OTHR_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW OTHER (NON-SPECIFIED) SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_SRGRY_OTLNGY_SW, -- TEXT(1) | NULL | INDICATES IF EAR, NOSE AND THROAT SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES, EAR, NOSE AND THROAT SURGERY IS OFFERED N = EAR, NOSE AND THROAT SURGERY IS NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_PAIN_SRGRY_SW, -- TEXT(1) | NULL | INDICATES IF PAIN SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES, PAIN SURGERY IS OFFERED N = PAIN SURGERY IS NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                POS_PGM_PRTCPTN_CD, -- TEXT(50) | NOT NULL | INDICATES IF THE PROVIDER PARTICIPATES IN MEDICARE, MEDICAID, OR BOTH PROGRAMS.
                POS_PHRMCY_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW PHARMACEUTICAL SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_PT_STF_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS EMPLOYED BY A PROVIDER.
                PRVDR_FTE_PHYSN_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT PHYSICIANS EMPLOYED BY A PROVIDER.
                PRVDR_PHYSN_SRVC_CD, -- TEXT(1) | NOT NULL | INDICATES HOW PHYSICIAN SERVICES ARE PROVIDED BY THE HOSPICE. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_PHYSN_VLNTR_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT PHYSICIANS VOLUNTEERING IN A HOSPICE.
                PRVDR_SRGRY_PLSTC_SW, -- TEXT(1) | NULL | INDICATES IF PLASTIC AND RECONSTRUCTIVE SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER. VALID VALUES: Y = YES, PLASTIC AND RECONSTRUCTIVE SURGERY IS OFFERED N = PLASTIC AND RECONSTRUCTIVE SURGERY IS NOT OFFERED ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_OTHR_PRSNEL_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT OTHER PERSONNEL EMPLOYED BY A PROVIDER.
                POS_PT_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW PHYSICAL THERAPY SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_RDLGY_SRVC_CD, -- TEXT(1) | NOT NULL | INDICATES HOW RADIOLOGY SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_RGSD_PHRMCST_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT REGISTERED PHARMACISTS EMPLOYED BY THE PROVIDER.
                PRVDR_FTE_RN_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSES EMPLOYED BY A PROVIDER.
                PRVDR_FTE_RN_VLNTR_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSES VOLUNTEERING IN A HOSPICE.
                PRVDR_SBUNIT_OPRTN_CNT, -- NUMBER(8,2) | NULL | NUMBER OF SUBUNITS OPERATED BY THE HOME HEALTH AGENCY.
                PRVDR_SBUNIT_OPRTN_SW, -- TEXT(1) | NULL | INDICATES IF THE HOME HEALTH AGENCY OPERATES ANY SUBUNITS. VALID VALUES: Y = YES, HHA OPERATES SUBUNITS N = NO, HHA DOES NOT OPERATE SUBUNITS ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_IS_A_SBUNIT_SW, -- TEXT(1) | NULL | INDICATES IF THE HOME HEALTH AGENCY IS A SUBUNIT OF ANOTHER AGENCY. VALID VALUES: Y = YES, HHA IS A SUBUNIT OF ANOTHER AGENCY N = NO, HHA IS NOT A SUBUNIT OF ANOTHER AGENCY ~ = NOT AVAILABLE/NOT APPLICABLE
                PRVDR_FTE_SCL_EMPLEE_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT SOCIAL WORKERS EMPLOYED BY THE PROVIDER.
                PRVDR_SS_IP_SRVC_CD, -- TEXT(1) | NOT NULL | INDICATES HOW SHORT TERM INPATIENT CARE SERVICES ARE PROVIDED BY THE HOSPICE. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_SPCH_AUDLGST_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT SPEECH PATHOLOGISTS OR AUDIOLOGISTS EMPLOYED BY THE PROVIDER.
                PRVDR_SPCH_PTHLGST_SRVC_CD, -- TEXT(1) | NOT NULL | INDICATES HOW SPEECH PATHOLOGY SERVICES ARE PROVIDED. REFERENCE TABLE: PRVDR_SRVC_CD
                POS_SPCH_THRPY_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW SPEECH THERAPY SERVICES ARE PROVIDED BY THE HOME HEALTH AGENCY. REFERENCE TABLE: PRVDR_SRVC_CD
                POS_VCTNL_GDNC_SRVC_CD, -- TEXT(20) | NOT NULL | INDICATES HOW VOCATIONAL GUIDANCE SERVICES ARE PROVIDED BY THE HOME HEALTH AGENCY. REFERENCE TABLE: PRVDR_SRVC_CD
                PRVDR_FTE_STF_VLNTR_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT VOLUNTEERS IN THE HOSPICE.
                PRVDR_FTE_OTHR_STF_TOT_CNT, -- NUMBER(8,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT OTHERS VOLUNTEERING IN THE HOSPICE.
                IDR_INSRT_TS, -- TIMESTAMP_NTZ | NOT NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHILE PERFORMING AN INSERT OPERATION.
                IDR_UPDT_TS, -- TIMESTAMP_NTZ | NULL | THE SYSTEM DATE AND TIME ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) WHEN UPDATES ARE MADE TO ANY NON-PRIMARY KEY COLUMN.
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                META_SRC_PRCSG_ID, -- NUMBER(38) | NOT NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS INSERTED.
                META_LTST_SRC_PRCSG_ID -- NUMBER(38) | NULL | A VALUE ASSIGNED BASED ON A BATCH IDENTIFICATION IN ORDER TO TRACE IT BACK TO ITS ORIGINAL SOURCE. IT WILL ONLY BE POPULATED WHEN A RECORD IS SUBSEQUENTLY UPDATED.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_HHA_ASC_HOSPC"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrOfSrvcHhaAscHospcExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
