"""
==========
V2_MDCR_PRVDR_HCIDEA_ADR_ERX IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HCIDEA_ADR_ERX

Table Type: VIEW
Columns: 28
Source Pattern: %mdcr_prvdr%
Table Comment: THE PROVIDER ADDRESS OBTAINED FROM THE SURESCRIPTS E-PRESCRIPTION NETWORK.   HCIDEA IS THE HEALTH CARE IDENTIFIER DRUG ENFORCEMENT AGENCY DATABASE FILE STANDARD GOVERNED BY NCPDP.  NOTE: THIS TABLE IS NO LONGER BEING UPDATED BY THE SOURCE.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrHcideaAdrErxExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrHcideaAdrErxExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_HCIDEA_ADR_ERX data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HCIDEA_ADR_ERX (VIEW)
    Columns: 28
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_hcidea_adr_erx_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_HCIDEA_ADR_ERX export.
        
        Includes all 28 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_HCIDEA_ADR_ID, -- NUMBER(38) | NOT NULL | UNIQUE INTERNAL IDENTIFIER FOR AN INDIVIDUAL HEALTHCARE LOCATION. SHOULD BE USED TO JOIN THE ADDRESS, PHONE, AND MEDICAID TABLES TO RETAIN PROVIDER/ADDRESS RELATIONSHIP BETWEEN DATA VALUES.
                PRVDR_HCIDEA_ERX_INACTV_DT, -- DATE | NOT NULL | DATE THAT THE PRESCRIBERÒ² SPI WILL BECOME INACTIVE. A PRESCRIBER MAY HAVE ACTIVE AND INACTIVE SPI VALUES
                PRVDR_HCIDEA_ERX_SRVC_LVL_KEY, -- NUMBER(5) | NOT NULL | THE PRESCRIBER SERVICE LEVEL CODE IS USED TO DETERMINE THE MESSAGING CAPABILITIES OF A PRESCRIBER. THE INTEGER VALUE IS SUPPLIED FOR BACKWARD COMPATIBILITY FOR THOSE HCIDEA CLIENTS WHO ARE ALSO EXISTING SURESCRIPTS CLIENTS
                PRVDR_HCIDEA_HC_ID, -- TEXT(10) | NOT NULL | UNIQUE NCPDP-ASSIGNED IDENTIFIER FOR AN INDIVIDUAL HEALTHCARE PROVIDER. THERE IS A ONE-TO-ONE RELATIONSHIP BETWEEN PROVIDERID AND HCID
                PRVDR_ERX_SRVC_LVL_10_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF THE PRESCRIBER HAS MESSAGING CAPABILITY TO RECEIVE A CONTINUITY OF CARE RECORD, A DATA FIELD ASSIGNED AND MAINTAINED BY ASTM INTERNATIONAL, FORMERLY THE AMERICAN SOCIETY FOR TESTING AND MATERIALS. 1 IF CCR IS SUPPORTED, 0 IF CCR IS NOT SUPPORTED
                PRVDR_ERX_SRVC_LVL_11_CD, -- NUMBER(1) | NOT NULL | FOR FUTURE USE (CURRENTLY 0).
                PRVDR_ERX_SRVC_LVL_12_CD, -- NUMBER(1) | NOT NULL | FOR FUTURE USE (CURRENTLY 0).
                PRVDR_ERX_SRVC_LVL_13_CD, -- NUMBER(1) | NOT NULL | FOR FUTURE USE (CURRENTLY 0).
                PRVDR_ERX_SRVC_LVL_14_CD, -- NUMBER(1) | NOT NULL | FOR FUTURE USE (CURRENTLY 0).
                PRVDR_ERX_SRVC_LVL_15_CD, -- NUMBER(1) | NOT NULL | FOR FUTURE USE (CURRENTLY 0).
                PRVDR_ERX_SRVC_LVL_16_CD, -- NUMBER(1) | NOT NULL | FOR FUTURE USE (CURRENTLY 0).
                PRVDR_HCIDEA_CNFDNC_TIER_CD, -- NUMBER(38) | NOT NULL | THE CONFIDENCE TIER ASSOCIATED WITH THE SPI VALUE FOR THE PROVIDER AT THE ADDRESS. VALID VALUES: 1, 2, 3, 99
                PRVDR_HCIDEA_CORP_CNT, -- NUMBER(38) | NOT NULL | THE TOTAL COUNT OF DATA SOURCES THAT SUPPLIED THE SPI VALUE FOR THE PROVIDER AT THE ADDRESS.
                PRVDR_HCIDEA_ERX_ID, -- TEXT(10) | NOT NULL | UNIQUE SURESCRIPTS IDENTIFIER FOR AN INDIVIDUAL HEALTHCARE PROVIDER THAT IS CAPABLE OF EPRESCRIBING. THE COMPLETE SPI IS THE COMBINATION OF THE SPI ROOT AND THE SPI LOCATION CODE
                PRVDR_HCIDEA_ERX_LCTN_CD, -- TEXT(3) | NOT NULL | UNIQUE SURESCRIPTS IDENTIFIER FOR AN INDIVIDUAL HEALTHCARE PROVIDER LOCATION THAT IS CAPABLE OF E-PRESCRIBING. THE COMPLETE SPI IS THE COMBINATION OF THE SPI ROOT AND THE SPI LOCATION CODE
                PRVDR_HCIDEA_ERX_SRVC_LVL_1_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF THE PRESCRIBER HAS MESSAGING CAPABILITY TO SEND A NEW PRESCRIPTION TO THE PHARMACY. 1 IF NEWRX SUPPORTED, 0 IF NEWRX NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_2_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF THE PRESCRIBER HAS MESSAGING CAPABILITY TO RECEIVE A MESSAGE FROM THE PHARMACY REQUESTING ADDITIONAL REFILLS AND CAN PROVIDE A RESPONSE. 1 IF REFREQ/REFRES SUPPORTED, 0 IF REFREQ/REFRES NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_3_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF THE PRESCRIBER HAS MESSAGING CAPABILITY TO RECEIVE A REQUEST FROM THE PHARMACY FOR A CHANGE IN THE ORIGINAL PRESCRIPTION AND CAN PROVIDE A RESPONSE. 1 IF RXCHG/CHGRES SUPPORTED, 0 IF RXCHG/CHGRES NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_4_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF THE PRESCRIBER HAS MESSAGING CAPABILITY TO RECEIVE A MESSAGE FROM THE PHARMACY THAT INDICATES THE STATUS OF THE PRESCRIPTIONS DISPENSING (DISPENSED, PARTIALLY DISPENSED, AND NOT DISPENSED). 1 IF RXFILL SUPPORTED, 0 IF RXFILL NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_5_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF THE PRESCRIBER HAS MESSAGING CAPABILITY TO SEND A REQUEST TO THE PHARMACY TO NOT FILL A PREVIOUSLY SENT PRESCRIPTION AND TO RECEIVE A RESPONSE FROM THE PHARMACY. 1 IF CANRX/CANRXRES SUPPORTED, 0 IF CANRX/CANRXRES NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_6_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF AN ENTITY HAS MESSAGING CAPABILITY TO SEND A MESSAGE REQUESTING MEDICATION HISTORY AND TO RECEIVE A RESPONSE. 1 IF MEDICATION HISTORY SUPPORTED, 0 IF MEDICATION HISTORY NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_7_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF A PRESCRIBER HAS MESSAGING CAPABILITY FOR AN ELIGIBILIITY TRANSACTION. 1 IF ELIGIBILITY IS SUPPORTED, 0 IF ELIGIBILITY IS NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_8_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF THE FACILITY HAS MESSAGING CAPABILITY TO SEND A RESUPPLY REQUEST TRANSACTION Ö REQUEST FOR REFILL - TO A PHARMACY. AN EXAMPLE USE CASE IS WHEN A MEDICATION SUPPLY FOR A RESIDENT IS RUNNING LOW (2-3 DOSES) AND A NEW SUPPLY IS NEEDED FROM THE PHARMACY, THE NURSE NEEDS A WAY TO NOTIFY THE PHARMACY THAT A REFILL FOR THE MEDICATION IS NEEDED. 1 IF RESUPP IS SUPPORTED, 0 IF RESUPP IS NOT SUPPORTED
                PRVDR_HCIDEA_ERX_SRVC_LVL_9_CD, -- NUMBER(1) | NOT NULL | A CODE SIGNIFYING IF A FACILITY IN A LONG TERM CARE ENVIRONMENT HAS MESSAGING CAPABILITY TO NOTIFY THE PHARMACY ABOUT CENSUS EVENTS. THE TRANSACTION CAN BE USED IN THREE CASES - TO NOTIFY THE PHARMACY OF A NEW RESIDENT, A CHANGE TO DEMOGRAPHIC INFORMATION OF A RESIDENT, OR THE DISCHARGE OF A RESIDENT. 1 IF CENSUS IS SUPPORTED, 0 IF CENSUS IS NOT SUPPORTED
                PRVDR_HCIDEA_REC_VRFCTN_CD, -- TEXT(2) | NOT NULL | REPRESENTS THE VERIFICATION STATUS FOR THIS DATA ELEMENT FOR THIS PROVIDER BASED ON INGENIXÒ PROVIDER OFFICE OUTREACH OR ELECTRONIC VERIFICATION PROGRAMS. VALID VALUES: C- VERIFIED CORRECT, U - UNVERIFIED
                PRVDR_HCIDEA_REC_VRFCTN_DT, -- DATE | NOT NULL | FOR C VERIFICATION CODES, THIS IS THE DATE THAT THE DATA VALUE WAS VERIFIED. FOR U VERIFICATION CODES, THIS IS THE DATE THAT THE DATA VALUE WAS POPULATED INTO THE HCIDEA DATABASE. VERIFICATION CODE X INDICATES THE DATA IS NOT RECOGNIZED
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HCIDEA_ADR_ERX"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrHcideaAdrErxExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
