"""
==========
V2_MDCR_PRVDR_NCPDP_REMIT IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_REMIT

Table Type: VIEW
Columns: 20
Source Pattern: %mdcr_prvdr%
Table Comment: ADDRESS RECORDS FOR MAILING REMIT AND RECONCILIATION, IF DIFFERENT FROM THE PAYMENT CENTER ADDRESS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrNcpdpRemitExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrNcpdpRemitExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_NCPDP_REMIT data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_REMIT (VIEW)
    Columns: 20
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_ncpdp_remit_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_NCPDP_REMIT export.
        
        Includes all 20 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NCPDP_REMIT_ID, -- TEXT(6) | NOT NULL | THE REMIT AND RECONCILIATION IDENTIFIER ASSOCIATED WITH THE PROVIDER.
                PRVDR_NCPDP_REMIT_NAME, -- TEXT(35) | NOT NULL | THE NAME OF THE REMIT AND RECONCILIATION LOCATION.
                PRVDR_NCPDP_REMIT_LINE_1_ADR, -- TEXT(55) | NOT NULL | THE FIRST ADDRESS LINE WHERE REMITTANCE ADVICE AND RECONCILIATION FORMS ARE SENT. SPECIFICATION OF A LOCATION BY REFERENCE TO A THOROUGHFARE, OR A LANDMARK; OR A POINT OF POSTAL DELIVERY. STREET ADDRESS MAY ENCOMPASSES ANY OF THE COMPONENTS THAT ARE DESCRIBED BY THE UNITED STATES POSTAL SERVICE AS A STANDARDIZED DELIVERY ADDRESS LINE IN USPS PUBLICATION 28.
                PRVDR_NCPDP_REMIT_LINE_2_ADR, -- TEXT(55) | NOT NULL | THE SECOND ADDRESS LINE FOR REMITTANCE ADDRESS. SPECIFICATION OF A LOCATION BY REFERENCE TO A THOROUGHFARE, OR A LANDMARK; OR A POINT OF POSTAL DELIVERY. STREET ADDRESS MAY ENCOMPASSES ANY OF THE COMPONENTS THAT ARE DESCRIBED BY THE UNITED STATES POSTAL SERVICE AS A STANDARDIZED DELIVERY ADDRESS LINE IN USPS PUBLICATION 28.
                PRVDR_NCPDP_REMIT_PLC_NAME, -- TEXT(30) | NOT NULL | THE NAME OF THE CITY. A FINER PARTITIONING OF GEOGRAPHIC SUBDIVISIONS OF A STATE OR COUNTY, USUALLY ASSOCIATED WITH ADDITIONAL LEVELS OF GOVERNMENT. LOCATION CITY.
                PRVDR_NCPDP_REMIT_STATE_CD, -- TEXT(20) | NOT NULL | REPRESENTS AN ADMINISTRATIVE AREA DIRECTLY SUBORDINATE TO THE PERTINENT GOVERNING AUTHORITY. THIS STANDARD PROVIDES A SET OF TWO-DIGIT NUMERIC CODES (IN ALPHANUMERIC FORMAT) FOR REPRESENTING THE 50 STATES, THE DISTRICT OF COLUMBIA AND THE OUTLYING AREAS OF THE UNITED STATES, AND ASSOCIATED AREAS. THE STANDARD COVERS ALL LAND AREAS UNDER THE SOVEREIGNTY OF THE UNITED STATES, THE FREELY ASSOCIATED STATES OF FEDERATED STATES OF MICRONESIA AND MARSHALL ISLANDS, AND THE TRUST TERRITORY OF PALAU.
                PRVDR_NCPDP_REMIT_ZIP_CD, -- TEXT(9) | NOT NULL | THE EXPANDED ZIP CODE.
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_NCPDP_REMIT_TEL_NUM, -- TEXT(10) | NOT NULL | THE TELEPHONE NUMBER.
                PRVDR_NCPDP_REMIT_EXTNSN_NUM, -- TEXT(5) | NOT NULL | THE TELEPHONE NUMBER EXTENSION.
                PRVDR_NCPDP_REMIT_FAX_NUM, -- TEXT(10) | NOT NULL | THE FACSIMILE MACHINE TELEPHONE LINE NUMBER.
                PRVDR_NPI_NUM, -- TEXT(10) | NOT NULL | NPI OF THE REMIT AND RECONCILIATION LOCATION. THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS.
                PRVDR_NCPDP_REMIT_TAX_NUM, -- TEXT(15) | NOT NULL | THE FEDERAL TAX ID, ALSO KNOWN AS EIN OR TIN, ASSIGNED TO THE REMIT AND RECONCILIATION ENTITY.
                PRVDR_NCPDP_REMIT_CNTCT_NAME, -- TEXT(30) | NOT NULL | REMITTANCE AND RECONCILIATION CONTACT PERSON NAME.
                PRVDR_NCPDP_REMIT_TITLE_NAME, -- TEXT(30) | NOT NULL | TITLE OF THE PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_REMIT_EMAIL_ADR, -- TEXT(50) | NOT NULL | E-MAIL ADDRESS FOR CONTACT PERSON.
                PRVDR_NCPDP_REMIT_DLT_DT, -- DATE | NOT NULL | THE DATE STAMPED BY NCPDP THAT THIS INFORMATION IS NO LONGER ACTIVE. IF INFORMATION IS ACTIVE, THIS FIELD WILL CONTAIN ZEROES.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_REMIT"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrNcpdpRemitExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
