"""
==========
V2_MDCR_PRVDR_NPI_PIN_GRP IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_GRP

Table Type: VIEW
Columns: 24
Source Pattern: %mdcr_prvdr%
Table Comment: A CROSSWALK OF A NATIONAL PROVIDER IDENTIFIER (NPI) TO A LEGACY GROUP PROVIDER IDENTIFICATION NUMBER (PIN) BY THE TYPE OF ADDRESS.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrNpiPinGrpExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrNpiPinGrpExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_NPI_PIN_GRP data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_GRP (VIEW)
    Columns: 24
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_npi_pin_grp_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_NPI_PIN_GRP export.
        
        Includes all 24 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_SK, -- NUMBER(18) | NOT NULL | AN IDR ASSIGNED SURROGATE KEY USED TO IDENTIFY A PARTY ENGAGED IN ACTIVITY RELATED TO CMS.
                PRVDR_PIN_GRP_NUM, -- TEXT(14) | NOT NULL | A GROUP PROVIDER IDENTIFICATION NUMBER (PIN) ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_NPI_PIN_BGN_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN THE PROVIDER IDENTIFICATION NUMBER (PIN) / NATIONAL PROVIDER IDENTIFIER (NPI) CROSSWALK MATCH WAS MADE IN THE INTEGRATED DATA REPOSITORY (IDR) BASED ON THE ADDRESS TYPE CODE.
                PRVDR_NPI_PIN_END_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN THE PROVIDER IDENTIFICATION NUMBER (PIN) / NATIONAL PROVIDER IDENTIFIER (NPI) CROSSWALK MATCH WAS TERMINATED IN THE INTEGRATED DATA REPOSITORY (IDR) BASED ON THE ADDRESS TYPE CODE. THE CURRENT VERSION OF A RECORD WILL BE SET TO 12/31/9999.
                CLM_CNTRCTR_NUM, -- TEXT(5) | NOT NULL | A NUMBER ASSIGNED BY CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) IDENTIFYING A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC) AUTHORIZED TO PROCESS MEDICARE CLAIMS. REFERENCE TABLE: CLM_CNTRCTR_NUM
                PRVDR_NPI_PIN_MDCR_BGN_DT, -- DATE | NOT NULL | A DATE IDENTIFYING WHEN THE NATIONAL PROVIDER IDENTIFIER (NPI)/PROVIDER IDENTIFICATION NUMBER (PIN) COMBINATION BECAME ELIGIBLE FOR MEDICARE PAYMENTS.
                PRVDR_NPI_PIN_MDCR_END_DT, -- DATE | NOT NULL | A DATE IDENTIFYING WHEN THE NATIONAL PROVIDER IDENTIFIER (NPI)/PROVIDER IDENTIFICATION NUMBER (PIN) COMBINATION BECAME INELIGIBLE FOR MEDICARE PAYMENTS.
                PRVDR_NPI_PIN_NAME, -- TEXT(43) | NOT NULL | THE NAME OF THE PROVIDER.
                PRVDR_NPI_PIN_TIN_NUM, -- TEXT(9) | NOT NULL | A UNIQUE TAX IDENTIFIER ASSIGNED TO A HEALTH CARE PROVIDER BY SOCIAL SECURITY ADMINISTRATION (SSA) OR THE INTERNAL
                PRVDR_NPI_PIN_LINE_1_ADR, -- TEXT(55) | NOT NULL | THE FIRST LINE OF A PARTY ADDRESS.
                PRVDR_NPI_PIN_LINE_2_ADR, -- TEXT(55) | NOT NULL | THE SECOND LINE OF A PARTY ADDRESS.
                PRVDR_NPI_PIN_INVLD_PLC_NAME, -- TEXT(40) | NOT NULL | INVALID PLACE NAME. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NPI_PIN_INVLD_ZIP_CD, -- TEXT(9) | NOT NULL | INVALID ZIP CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NPI_PIN_INVLD_STATE_CD, -- TEXT(2) | NOT NULL | INVALID STATE CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                GEO_SK, -- NUMBER(38) | NOT NULL | IDENTIFIER OF THE GEOGRAPHICAL AREA ASSOCIATED WITH THE PROVIDER.
                GEO_ZIP4_CD, -- TEXT(4) | NOT NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_NPI_PIN_RSNBL_CHRG_CD, -- TEXT(3) | NOT NULL | A CODE IDENTIFYING THE PRICING AREA USED IN DETERMINING THE CUSTOMARY AND PREVAILING ALLOWANCE FOR A SERVICE.
                PRVDR_NPI_PIN_PHYSN_FEE_CD, -- TEXT(3) | NOT NULL | A CODE IDENTIFYING A PROVIDERS LOCATION TO DETERMINE A PHYSICIANS FEES.
                PRVDR_NPI_PIN_SPCLTY_CD, -- TEXT(2) | NOT NULL | A CODE IDENTIFYING THE CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) SPECIALTY OF A PROVIDER OR SUPPLIER.FOR EXAMPLE:11 = INTERNAL MEDICINE49 = AMBULATORY SURGICAL CENTER REFERENCE TABLE: CLM_PRVDR_SPCLTY_CD
                PRVDR_NPI_PIN_UPIN_NUM, -- TEXT(6) | NOT NULL | A UNIQUE PROVIDER IDENTIFICATION NUMBER (UPIN) ASSIGNED TO A PROVIDER ELIGIBLE TO ORDER OR REFER SERVICES.
                PRVDR_NPI_PIN_CLIA_NUM, -- TEXT(15) | NOT NULL | A CLINICAL LABORATORY IMPROVEMENT AMENDMENTS (CLIA) NUMBER ASSIGNED TO A PROVIDER.
                PRVDR_LGCY_ADR_TYPE_CD, -- TEXT(1) | NOT NULL | ENCODING OF THE CATEGORIZATION OF ADDRESSES BASED ON BUSINESS FUNCTION PERFORMED AT THAT LOCATION (NPICS) .
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NPI_PIN_GRP"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrNpiPinGrpExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
