"""
==========
V2_MDCR_PRVDR_OF_SRVC IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC

Table Type: VIEW
Columns: 46
Source Pattern: %mdcr_prvdr%
Table Comment: AN INSTITUTIONAL PROVIDER AS REPORTED IN THE PROVIDER OF SERVICES (POS) EXTRACT. IT IS CREATED FROM THE QIES (QUALITY IMPROVEMENT EVALUATION SYSTEM) DATABASE AS OF SECOND QUARTER 2011 AND ALL FUTURE POS FILES. THE FILE CONTAINS AN INDIVIDUAL RECORD FOR EA

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrOfSrvcExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrOfSrvcExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_OF_SRVC data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC (VIEW)
    Columns: 46
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_of_srvc_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_OF_SRVC export.
        
        Includes all 46 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_OSCAR_NUM, -- TEXT(10) | NOT NULL | AN ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_OF_SRVC_EFCTV_DT, -- DATE | NOT NULL | THE DATE THAT THE PROVIDER DATA BECAME EFFECTIVE
                GEO_SK, -- NUMBER(38) | NOT NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                PRVDR_ACRDTN_STUS_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE THE CURRENT STATUS OF THE RECORD - ACCEPTED OR COMPLAINT.
                PRVDR_CBSA_URBN_RRL_CD, -- TEXT(1) | NOT NULL | AN IDENTIFIER OF A CORE BASED STATISTICAL AREA (CBSA) - URBAN OR RURAL.
                PRVDR_CHOW_CNT, -- NUMBER(38) | NULL | THE NUMBER OF OCCURRENCES OF A CHANGE OF OWNERSHIP (CHOW) FOR A PROVIDER/SUPPLIER.
                PRVDR_CHOW_DT, -- DATE | NULL | THE DATE THAT A CHANGE OF OWNERSHIP (CHOW) BECAME ACTIVE.
                PRVDR_CITY_NAME, -- TEXT(28) | NULL | THE CITY IN WHICH THE PROVIDER IS PHYSICALLY LOCATED.
                PRVDR_CRTFCTN_FAC_SBTYP_CD, -- TEXT(2) | NOT NULL | AN IDENTIFIER THAT NARROWS THE FOCUS OF THE PROVIDER CATEGORY CODE. .
                PRVDR_CRTFCTN_FAC_TYPE_CD, -- TEXT(2) | NOT NULL | AN IDENTIFIER OF A PROVIDER/SUPPLIER CATEGORY REPORTED ON THE MEDICARE/MEDICAID CERTIFICATION AND TRANSMITTAL FORM (CMS1539)..
                PRVDR_CRTFCTN_SRVY_ACTN_CD, -- TEXT(1) | NOT NULL | A CODE TO IDENTIFY THE TYPE OF CATEGORY TERMINATION ACTION PERFORMED BY EITHER THE CMS REGIONAL OFFICE OR THE SINGLE STATE AGENCY - VOLUNTARY, INVOLUNTARY, OR OTHER.
                PRVDR_FAX_NUM, -- TEXT(10) | NULL | THE 10-DIGIT FAX PHONE NUMBER OF THE PRIMARY CONTACT OR THE OPERATOR OF THE LABORATORY.
                PRVDR_FIPS_CNTY_CD, -- TEXT(3) | NOT NULL | A CODE IDENTIFYING A UNITED STATES COUNTY AS ASSIGNED BY THE FEDERAL INFORMATION PROCESSING STANDARD (FIPS).
                PRVDR_FIPS_STATE_CD, -- TEXT(2) | NOT NULL | A UNIQUE IDENTIFIER ASSIGNED BY ANSI (AMERICAN NATIONAL STANDARDS INSTITUTE) TO A US STATE (FORMERLY FIPS STATE CODE).
                PRVDR_FY_END_MO_DAY_NUM, -- TEXT(4) | NULL | THE ENDING DATE (MONTH AND DAY) OF A FACILITYS FISCAL YEAR.
                PRVDR_INCMPLT_REC_SW, -- TEXT(1) | NULL | A CODE TO INDICATE WHETHER OR NOT THE PROVIDER DATA IS LIMITED, INCOMPLETE.
                PRVDR_OF_SRVC_CLM_CNTRCTR_NUM, -- TEXT(5) | NOT NULL | A NUMBER ASSIGNED BY CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) IDENTIFYING A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC) AUTHORIZED TO PROCESS MEDICARE CLAIMS. REFERENCE TABLE: CLM_CNTRCTR_NUM
                PRVDR_MDCD_VNDR_NUM, -- TEXT(15) | NULL | A NUMBER WHICH MAY BE ASSIGNED TO A FACILITY BY THE STATE MEDICAID AGENCY FOR EXTERNAL CONTROL OR BILLING PURPOSES.
                PRVDR_OF_SRVC_GEO_ZIP5_CD, -- TEXT(5) | NOT NULL | THE GEOGRAPHIC 5 DIGIT ZIP CODE OF THE PROVIDER.
                PRVDR_OF_SRVC_OBSLT_DT, -- DATE | NULL | THE DATE THAT THE PROVIDER DATA BECAME OBSOLETE
                PRVDR_ORG_TYPE_CD, -- TEXT(2) | NOT NULL | INDICATES THE NATURE OF THE ORGANIZATION THAT OPERATES A PROVIDER OF SERVICES.
                PRVDR_PGM_CMPLNT_STUS_SW, -- TEXT(1) | NULL | INDICATES THE PROVIDER IS IN COMPLIANCE WITH PROGRAM REQUIREMENTS AND/OR APPLIED WAIVERS. (A/B)
                PRVDR_PGM_APRVL_DT, -- DATE | NULL | THE DATE THE FACILITY WAS FIRST APPROVED TO PROVIDE MEDICARE AND/OR MEDICAID SERVICES.
                PRVDR_PGM_CRTFCT_EXPRTN_DT, -- DATE | NULL | THE TERMINATION DATE OF THE LABORATORYS CERTIFICATION; THE EXPIRATION DATE OF A CURRENT CLIA OR OTHER PROGRAM CERTIFICATE. NON-CLIA PROVIDERS - THE DATE OF TERMINATION OF THE FACILITY.
                PRVDR_PGM_CRTFCTN_DT, -- DATE | NULL | THE DATE OF THE PROVIDERS AUTHENTICATION. IT IS EQUAL TO THE EXIT DATE OF THE INITIAL VISIT OF EITHER THE HEALTH SURVEY OR THE LIFE SAFETY CODE (LSC) SURVEY, WHICHEVER IS LATER.
                PRVDR_PGM_CRTFD_FAC_NAME, -- TEXT(50) | NULL | THE NAME OF A PROVIDER CERTIFIED TO PARTICIPATE IN THE MEDICARE AND/OR MEDICAID PROGRAMS.
                PRVDR_PGM_ELGBLTY_CD, -- TEXT(1) | NOT NULL | AN INDICATOR OF THE FACILITYS ELIGIBILITY FOR PARTICIPATION IN THE MEDICARE AND/OR MEDICAID PROGRAMS.
                PRVDR_PGM_POC_CMPLNT_SW, -- TEXT(1) | NULL | INDICATES THE PROVIDER IS IN COMPLIANCE WITH PROGRAM REQUIREMENTS BASED ON AN ACCEPTABLE PLAN AND/OR APPROVED WAIVERS OF SPECIFIC REQUIREMENTS. (Y/N)
                PRVDR_PGM_TRMNTN_RSN_CD, -- TEXT(2) | NOT NULL | A CODE TO IDENTIFY THE REASON FOR TERMINATION FROM THE CLIA, MEDICARE, AND/OR MEDICAID, OR OTHER PROGRAMS.
                PRVDR_PRIOR_CHOW_DT, -- DATE | NULL | THE DATE OF A PRIOR CHANGE OF OWNERSHIP (CHOW).
                PRVDR_PRIOR_CLM_CNTRCTR_NUM, -- TEXT(5) | NOT NULL | A NUMBER ASSIGNED BY CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) IDENTIFYING A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC) AUTHORIZED TO PROCESS MEDICARE CLAIMS. REFERENCE TABLE: CLM_CNTRCTR_NUM
                PRVDR_RGN_CD, -- TEXT(2) | NOT NULL | THE REGIONAL LOCATION OF THE PROVIDER.
                PRVDR_RLTD_PRVDR_NUM, -- TEXT(10) | NULL | RELATED PROVIDER NUMBER
                PRVDR_SSA_CNTY_CD, -- TEXT(3) | NOT NULL | THE SOCIAL SECURITY ADMINISTRATION STANDARD CODE IDENTIFYING A COUNTY.
                PRVDR_SSA_STATE_CD, -- TEXT(2) | NOT NULL | THE SOCIAL SECURITY ADMINISTRATION STANDARD CODE IDENTIFYING A STATE.
                PRVDR_ST_ADR, -- TEXT(50) | NULL | THE STREET ADDRESS OF A CERTIFIED MEDICARE/MEDICAID PROVIDER.
                PRVDR_STATE_RGN_CD, -- TEXT(6) | NOT NULL | FOR SELECTED STATES, IDENTIFIES THE PARTICULAR REGION WITHIN THE STATE WHERE THE PROVIDER IS LOCATED.
                PRVDR_TEL_NUM, -- TEXT(10) | NULL | THE TELEPHONE NUMBER AND AREA CODE OF EITHER THE PROVIDER OPERATOR OR PROVIDER PRIMARY CONTACT.
                PRVDR_USPS_STATE_CD, -- TEXT(2) | NOT NULL | STATE CODE USED BY THE UNITED STATES POSTAL SERVICE TO IDENTIFY A STATE.
                PRVDR_XREF_PRVDR_NUM, -- TEXT(10) | NULL | A NUMBER THAT ALLOWS FOR CROSS REFERENCING OF PROVIDER NUMBERS TO MEDICARE NUMBERS.
                PRVDR_VLDTN_SRVY_DT, -- DATE | NULL | DATE A VALIDATION SURVEY IS PERFORMED BY THE STATE AGENCY IN A JCAHCO (JOINT COMMISSION ON ACCREDITATION OF HEALTH CARE ORGANIZATIONS) OR AOA (AMERICAN OSTEOPATHIC ASSOCIATION) ACCREDITED HOSPITAL.
                PRVDR_CRNT_FMS_SRVY_DT, -- DATE | NULL | A DATE THE FEDERAL MONITORING SURVEY (FMS) WAS CONDUCTED BY THE REGIONAL OFFICE. FMS IS USED TO VALIDATE IF A STATE IS USING PROPER SURVEY PROCEDURES.
                PRVDR_CRNT_STUS_CD, -- TEXT(1) | NULL | A CODE TO INDICATE OR SPECIFY THE CURRENT STATUS OF THE RECORD. A - THE RECORD TYPE HAS BEEN ACCEPTED D -THE RECORD TYPE HAS BEEN DELETED N- THE RECORD TYPE IS NOT A LAB P- THE RECORD TYPE IS PENDING T-THE RECORD IS TEMPORARY(CLIA ONLY) W- THE RECORD TYPE IS WORK
                PRVDR_GEO_CBSA_CD, -- TEXT(5) | NOT NULL | A CODE IDENTIFYING A FIVE-DIGIT NUMBER ASSIGNED TO A METROPOLITAN, MICROPOLITAN, OR DIVISION STATISTICAL AREA DEFINED BY THE OFFICE OF MANAGEMENT AND BUDGET (OMB). THIS IS DESIGNATED AS A CORE BASE STATISTICAL AREA (CBSA).
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrOfSrvcExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
