"""
==========
V2_MDCR_PRVDR_PSF IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PSF

Table Type: VIEW
Columns: 73
Source Pattern: %mdcr_prvdr%
Table Comment: AN INSTITUTIONAL PROVIDER AT A POINT IN TIME AS DOCUMENTED IN THE PROVIDER SPECIFIC FILE.  NOTE: THE PROV FILE CONTAINS NEEDED INFORMATION ABOUT EACH PROVIDER TO ENABLE THE PRICING SOFTWARE TO CALCULATE THE PAYMENT AMOUNT.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrPsfExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrPsfExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_PSF data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PSF (VIEW)
    Columns: 73
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_psf_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_PSF export.
        
        Includes all 73 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_OSCAR_NUM, -- TEXT(6) | NOT NULL | AN ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_PSF_EFCTV_DT, -- DATE | NOT NULL | THE PROVIDER SPECIFIC FILE EFFECTIVE DATE DERIVED BY IDR.
                PRVDR_ACTL_CBSA_CD, -- TEXT(5) | NOT NULL | A UNIQUE IDENTIFIER OF A CORE BASED STATISTICAL AREA (CBSA), A GEOGRAPHIC ENTITY ASSOCIATED WITH AT LEAST ONE CORE OF 10,000 OR MORE POPULATION, PLUS ADJACENT TERRITORY THAT HAS A HIGH DEGREE OF SOCIAL AND ECONOMIC INTEGRATION WITH THE CORE AS MEASURED BY COMMUTING TIES. THE OMB STANDARDS DESIGNATE AND DELINEATE TWO CATEGORIES OF CBSAS: METROPOLITAN STATISTICAL AREAS AND MICROPOLITAN STATISTICAL AREAS. THE TERM CBSA WAS ADOPTED BY OMB IN 2000. A CODE FOR THE ACTUAL GEOGRAPHIC LOCATION CORE-BASED STATISTICAL AREA (CBSA) WHERE THE FACILITY IS PHYSICALLY LOCATED.
                PRVDR_ACTL_MSA_CD, -- TEXT(4) | NOT NULL | A UNIQUE IDENTIFIER OF A MEDICAL METROPOLITAN STATISTICAL AREA (MSA) . THE MEDMSA (MEDICAL METROPOLITAN STATISTICAL AREA) CODE IS BASED ON THE HCFA MSA DEFINITION OF FROM AUGUST, 2000. THE HFCA MSA LIST DIFFERS FROM THE CENSUS BUREAU/OMB MSA DEFINITION IN MANY AREAS. FOR THAT REASON, THIS DATABASE SHOULD BE USED ONLY FOR THOSE APPLICATIONS WHERE THE HCFA MSA DEFINITION IS APPROPRIATE, SUCH AS MEDICAL CLAIM FORMS TO BE SUBMITTED TO THE HCFA. THE MSA CODE USED HERE INCLUDES THE SO-CALLED GOLDSMITH MODIFICATION, WHICH IDENTIFIES RURAL AREAS OF METROPOLITAN COUNTIES. THE MEDMSA FIELD CONTAINS SPECIAL MSA CODES FOR THE ZIP CODES OF ALL RURAL COUNTIES AND THE RURAL PORTION (IF ANY) OF METROPOLITAN COUNTIES. THESE CODES ALWAYS HAVE THE FORM 99XX, WHERE XX IS ALWAYS TWO DIGITS. THESE TWO DIGITS OFTEN APPEAR TO BE THE SAME AS THE TWO-DIGIT STATE FIPS CODE, BUT THAT IS NOT REALLY THE CASE. THE MSA CODES FOR RURAL AREAS ARE DEFINED BY HCFA, AND DO NOT CONFORM TO THE STATE FIPS CODING SCHEME. NOTE THAT THE SAME RURAL MSA CODE IS USED FOR ALL RURAL ZIP CODES OF A GIVEN STATE. A CODE FOR THE ACTUAL GEOGRAPHIC LOCATION - MSA WHERE THE FACILITY IS PHYSICALLY LOCATED.
                PRVDR_CBSA_CMI_RATE, -- NUMBER(9,4) | NULL | THIS IS THE CASE MIX INDEX THAT HAS BEEN CALCULATED AND PUBLISHED BY CMS FOR EACH HOSPITAL (BASED ON 1981 COST AND BILLING DATA) REFLECTING THE RELATIVE COST OF THAT HOSPITALS MIX OF CASES COMPARED TO THE NATIONAL AVERAGE MIX.
                PRVDR_CBSA_HOSP_QLTY_SW, -- TEXT(1) | NULL | HOSPITAL QUALITY INDICATOR CODE WHICH INDICATES HOSPITAL MEETS CRITERIA TO RECEIVE HIGHER PAYMENT PER MMA QUALITY STANDARDS. BLANK = HOSPITAL DOES NOT MEET CRITERIA 1 = HOSPITAL QUALITY STANDARDS HAVE BEEN MET
                PRVDR_SPCL_PYMT_CD, -- TEXT(1) | NOT NULL | IDENTIFIES A TYPE OF SPECIAL PAYMENT PROVISION. BLANK = NOT APPLICABLE Y = RECLASSIFIED 1 = SPECIAL WAGE INDEX INDICATOR 2 = BOTH SPECIAL WAGE INDEX INDICATOR AND RECLASSIFIED
                PRVDR_CHG_CD_RECLSFCTN_SW, -- TEXT(1) | NULL | WHETHER THE HOSPITALS WAGE INDEX LOCATION HAS BEEN RECLASSIFIED FOR THE YEAR.
                PRVDR_COLA_RATE, -- NUMBER(9,3) | NULL | A FACTOR FOR A COST OF LIVING ADJUSTMENT.
                PRVDR_CPTL_CST_TO_CHRG_RATIO, -- NUMBER(4,3) | NULL | THE CAPITAL COST-TO-CHARGE RATIO FOR HOSPITALS.
                PRVDR_CPTL_EXCPTN_PYMT_RATE, -- NUMBER(9,4) | NULL | THE PER DISCHARGE EXCEPTION PAYMENT TO WHICH A HOSPITAL IS ENTITLED (FOR HOSPITALS WITH INORDINATELY HIGH LEVELS OF CAPITAL OBLIGATIONS).
                PRVDR_CPTL_IME_RATIO, -- NUMBER(9,4) | NULL | CAPITAL INDIRECT MEDICAL EDUCATION RATIO IS THE RATIO OF RESIDENTS/INTERNS TO THE HOSPITALS AVERAGE DAILY CENSUS. CALCULATED BY DIVIDING THE HOSPITALS FULL-TIME EQUIVALENT TOTAL OF RESIDENTS DURING THE FISCAL YEAR BY THE HOSPITALS TOTAL INPATIENT DAYS. ZERO FILL FOR A NON-TEACHING HOSPITAL.
                PRVDR_DSH_ADJSTMT_PCT, -- NUMBER(9,4) | NULL | THE DISPROPORTIONATE SHARE ADJUSTMENT PERCENTAGE FOR HOSPITALS (A RATE REFLECTING INDIGENT POPULATION SERVED).
                PRVDR_FY_BGN_DT, -- DATE | NULL | THE FISCAL YEAR BEGINNING DATE FOR PROVIDERS.
                PRVDR_FY_END_DT, -- DATE | NULL | THE FISCAL YEAR ENDING DATE FOR PROVIDERS. THIS FIELD IS NO LONGER USED. IF PRESENT, MUST BE CCYYMMDD.
                PRVDR_HOSP_SPECF_CPTL_RATE, -- NUMBER(6,2) | NULL | HOSPITAL SPECIFIC CAPITAL RATE IS THE THE HOSPITALS ALLOWABLE ADJUSTED BASE YEAR INPATIENT CAPITAL COSTS PER DISCHARGE. THIS FIELD IS NOT USED AS OF 10/1/02.
                PRVDR_INTRMDRY_NUM, -- TEXT(5) | NOT NULL | THE IDENTIFICATION NUMBER ASSIGNED BY HCFA TO A FISCAL INTERMEDIARY AUTHORIZED TO PROCESS INSTITUTIONAL CLAIM RECORDS. (NCH) NOTE: CURRENTLY, THE SAME ORGANIZATION WILL RECEIVE TWO UNIQUE IDENTIFICATION NUMBERS FROM HCFA IF THEY ACT AS BOTH A CARRIER AND FISCAL INTERMEDIARY.
                PRVDR_INTRN_BED_RATIO, -- NUMBER(9,4) | NULL | THE PROVIDERÒ² INTERN/RESIDENT TO BED RATIO. A HOSPITALS RATIO OF FULL-TIME EQUIVALENT (FTE) INTERNS AND RESIDENTS (I&R) (SEE Ç±405.3.F.) IN APPROVED PROGRAMS TO ITS NUMBER OF BEDS (SEE Ç±405.3.G.) AS DEFINED IN Ç±510.5A OF THE PROVIDER REIMBURSEMENT MANUAL.
                PRVDR_IP_BED_QTY, -- NUMBER(5) | NULL | THE NUMBER OF ADULT HOSPITAL BEDS AND PEDIATRIC BEDS AVAILABLE FOR LODGING INPATIENT.
                PRVDR_LGR_RECLSFCTN_SW, -- TEXT(1) | NULL | WHETHER THE METROPOLITAN STATISTICAL AREA (MSA) HAS BEEN RECLASSIFIED FOR WAGE INDEX PURPOSES UNDER Ç±886(D)(8)(B) OF THE ACT. THIS IS KNOWN AS A LUGAR RECLASSIFICATION AND APPLIES TO ASC-APPROVED SERVICES PROVIDED ON AN OUTPATIENT BASIS WHEN A HOSPITAL QUALIFIES FOR PAYMENT UNDER AN ALTERNATE WAGE INDEX MSA. L= ENTER AN L IF THE MSA HAS BEEN RECLASSIFIED FOR WAGE INDEX PURPOSES UNDER Ç±886(D)(8)(B) OF THE ACT. BLANK= LEAVE BLANK FOR HOSPITALS IF THERE HAS NOT BEEN A LUGAR RECLASSIFICATION.
                PRVDR_MDCD_RATIO, -- NUMBER(9,4) | NULL | A RATIO OF PATIENT DAYS THAT WERE FURNISHED TO PATIENTS WHO, DURING A GIVEN MONTH, WERE ENTITLED TO BOTH MEDICARE PART A AND SUPPLEMENTAL SECURITY INCOME (SSI) (EXCLUDING STATE SUPPLEMENTATION) AND PATIENT DAYS ASSOCIATED WITH BENEFICIARIES WHO WERE ELIGIBLE FOR MEDICAL ASSISTANCE (MEDICAID) UNDER A STATE PLAN APPROVED UNDER TITLE XIX BUT WHO WERE NOT ENTITLED TO MEDICARE PART A.
                PRVDR_MDH_BASE_YR_NUM, -- TEXT(4) | NULL | THE BASE YEAR FOR A SOLE COMMUNITY HOSPITAL OR A MEDICARE DEPENDENT HOSPITAL FOR OPERATING HOSPITAL SPECIFIC RATE, THE HIGHER OF EITHER 82 OR 87.
                PRVDR_NEW_CPTL_HLD_HRMLS_RATIO, -- NUMBER(9,4) | NULL | THE RATIO OF THE HOSPITALS ALLOWABLE INPATIENT COSTS FOR NEW CAPITAL TO THE HOSPITALS TOTAL ALLOWABLE INPATIENT CAPITAL COSTS.
                PRVDR_NEW_HOSP_SW, -- TEXT(1) | NULL | INDICATOR WHEN THERE IS A NEW HOSPITAL IN OPERATION WITHIN THE FIRST 2 YEARS. Y= ENTER Y FOR THE FIRST 2 YEARS THAT A NEW HOSPITAL IS IN OPERATION. BLANK= LEAVE BLANK IF HOSPITAL IS NOT WITHIN FIRST 2 YEARS OF OPERATION.
                PRVDR_NPI_NUM, -- TEXT(10) | NULL | THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER.
                PRVDR_OLD_CPTL_HLD_HRMLS_RATE, -- NUMBER(6,2) | NULL | THE HOSPITALS ALLOWABLE INPATIENT OLD CAPITAL COSTS PER DISCHARGE INCURRED FOR ASSETS ACQUIRED BEFORE DECEMBER 31, 1990, FOR CAPITAL PPS.
                PRVDR_OPRTG_CST_TO_CHRG_RATIO, -- NUMBER(9,3) | NULL | THE OPERATING COST TO CHARGE RATIO ARE USED TO CALCULATE COST OUTLIER PAYMENTS FOR THOSE HOSPITALS WHERE YOU COMPUTE COST-TO-CHARGE RATIOS THAT ARE NOT WITHIN THE LIMITS PUBLISHED IN THE FEDERAL REGISTER.
                PRVDR_PASS_THRU_FOR_CPTL_AMT, -- NUMBER(6,2) | NULL | THE PASS THROUGH AMOUNT FOR CAPITAL IS THE PER DIEM AMOUNT BASED ON THE INTERIM PAYMENTS TO THE HOSPITAL. (SEE THE PROVIDER REIMBURSEMENT MANUAL, Ç±405.2).
                PRVDR_PASS_THRU_MDCL_EDCTN_AMT, -- NUMBER(6,2) | NULL | THE PASS THROUGH AMOUNT FOR DIRECT MEDICAL EDUCATION IS THE PER DIEM AMOUNT BASED ON THE INTERIM PAYMENTS TO THE HOSPITAL. (SEE THE PROVIDER, REIMBURSEMENT MANUAL, Ç±405.2.)
                PRVDR_PASS_THRU_ORGN_AMT, -- NUMBER(6,2) | NULL | THE PASS THROUGH AMOUNT FOR ORGAN ACQUISITION IS THE PER DIEM AMOUNT BASED ON THE INTERIM PAYMENTS TO THE HOSPITAL. INCLUDE STANDARD ACQUISITION AMOUNTS FOR KIDNEY, HEART, AND LIVER TRANSPLANTS. DO NOT INCLUDE ACQUISITION COSTS FOR BONE MARROW TRANSPLANTS. (SEE THE PROVIDER REIMBURSEMENT MANUAL, Ç±405.2.)
                PRVDR_PPS_BLEND_CD, -- TEXT(1) | NOT NULL | AN IDENTIFIER OF AN APPROPRIATE PERCENTAGE PAYMENT TO BE MADE ON HOME HEALTH (HH) PROSPECTIVE PAYMENT SYSTEM RAPS, OR AN IDENTIFIER OF A BLEND RATIO BETWEEN FEDERAL AND FACILITY RATES. HH PPS: 0 = PAY STANDARD PERCENTAGES 1 = PAY ZERO PERCENT IRF PPS: ALL IRFS ARE 100% FEDERAL FOR COST REPORTING PERIODS BEGINNING ON OR AFTER 10/01/2002. LTCH PPS: 1= 20 (FEDERAL %); 80 (FACILITY %) 2= 40 (FEDERAL %); 60 (FACILITY %) 3= 60 (FEDERAL %); 40 (FACILITY %) 4= 80 (FEDERAL %); 20 (FACILITY %) 5= 100 (FEDERAL %); 00 (FACILITY %) IPF PPS: 1= 25 (FEDERAL %); 75 (FACILITY %) 2= 50 (FEDERAL %); 50 (FACILITY %) 3= 75 (FEDERAL %); 25 (FACILITY %) 4= 100 (FEDERAL %); 00 (FACILITY %)
                PRVDR_PPS_CPTL_PYMT_CD, -- TEXT(1) | NOT NULL | AN IDENTIFIER OF A CAPITAL PAYMENT METHODOLOGY UNDER THE PROSPECTIVE PAYMENT SYSTEM FOR HOSPITALS.
                PRVDR_PPS_WVR_SW, -- TEXT(1) | NULL | WHETHER THE PROVIDER HAS A WAIVER TO NOT BE UNDER THE PROSPECTIVE PAYMENT SYSTEM (PPS). Y = WAIVED (PROVIDER IS NOT UNDER PPS). N = NOT WAIVED (PROVIDER IS UNDER PPS).
                PRVDR_PSF_BGN_DT, -- DATE | NULL | THE EFFECTIVE DATE OF THE PROVIDERS FIRST PROSPECTIVE PAYMENT SYSTEM (PPS) PERIOD, OR FOR SUBSEQUENT PPS PERIODS, THE EFFECTIVE DATE OF A CHANGE TO THE PROV FILE.
                PRVDR_PSF_CNSUS_DIV_CD, -- TEXT(1) | NOT NULL | UNIQUELY IDENTIFIES THE PROVIDER SPECIFIC FILE CENSUS DIVISION. THE CENSUS DIVISION TO WHICH THE FACILITY BELONGS FOR PAYMENT PURPOSES.
                PRVDR_PSF_DRVD_CNSUS_DIV_CD, -- TEXT(1) | NOT NULL | UNIQUELY IDENTIFIES THE PROVIDER SPECIFIC FILE CENSUS DIVISION. THE CENSUS DIVISION TO WHICH THE FACILITY BELONGS FOR PAYMENT PURPOSES.
                PRVDR_PSF_OBSLT_DT, -- DATE | NULL | THE DATE THE PROVIDER SPECIFIC FILE (PSF) DATA HAS EXPIRED. DERIVED BY IDR.
                PRVDR_PSF_PRVDR_TYPE_CD, -- TEXT(2) | NOT NULL | AN IDENTIFIER OF A TYPE OF PROVIDER AS DEFINED IN THE PROVIDER SPECIFIC FILE. NOTE: PROVIDER TYPE VALUES 49-54 REFER TO SPECIAL UNIT DESIGNATIONS THAT ARE ASSIGNED TO THE THIRD POSITION OF THE OSCAR NUMBER
                PRVDR_PSF_SRC_FIL_TYPE_CD, -- TEXT(3) | NOT NULL | INDICATES THE TYPE OF PROVIDER FILE.
                PRVDR_RPT_DT, -- DATE | NULL | THE DATE THE FILE WAS CREATED/RUN DATE OF THE PROV REPORT FOR SUBMITTAL TO CMS CO.
                PRVDR_SPCL_UPDT_FCTR_RATE, -- NUMBER(9,5) | NULL | SPECIAL PROVIDER UPDATE FACTOR ZERO FILL FOR ALL HOSPITALS AFTER FY91. THIS FIELD IS OBSOLETE AS OF FY92.
                PRVDR_SPCL_WGE_IDX_RATE, -- NUMBER(7,2) | NULL | THE SPECIAL WAGE INDEX THAT CERTAIN PROVIDERS MAY BE ASSIGNED TO.
                PRVDR_SSI_RATIO, -- NUMBER(9,4) | NULL | THE SUPPLEMENTAL SECURITY INCOME RATIO IS USED TO DETERMINE IF THE HOSPITAL QUALIFIES FOR A DISPROPORTIONATE SHARE ADJUSTMENT AND TO DETERMINE THE SIZE OF THE CAPITAL AND OPERATING DSH ADJUSTMENTS.
                PRVDR_STDZD_AMT_CBSA_CD, -- TEXT(5) | NOT NULL | A UNIQUE IDENTIFIER OF A CORE BASED STATISTICAL AREA (CBSA), A GEOGRAPHIC ENTITY ASSOCIATED WITH AT LEAST ONE CORE OF 10,000 OR MORE POPULATION, PLUS ADJACENT TERRITORY THAT HAS A HIGH DEGREE OF SOCIAL AND ECONOMIC INTEGRATION WITH THE CORE AS MEASURED BY COMMUTING TIES. THE OMB STANDARDS DESIGNATE AND DELINEATE TWO CATEGORIES OF CBSAS: METROPOLITAN STATISTICAL AREAS AND MICROPOLITAN STATISTICAL AREAS. THE TERM CBSA WAS ADOPTED BY OMB IN 2000. THE APPROPRIATE CODE FOR THE CBSA, 00001-89999, OR THE RURAL AREA, (BLANK)(BLANK) (BLANK) (2 DIGIT NUMERIC STATE CODE) SUCH AS _ _ _ 3 6 FOR OHIO, TO WHICH A HOSPITAL HAS BEEN RECLASSIFIED DUE TO ITS PREVAILING WAGE RATES.
                PRVDR_STDZD_AMT_MSA_CD, -- TEXT(4) | NOT NULL | A CODE IDENTIFYING A MEDICAL METROPOLITAN STATISTICAL AREA (MSA) AS DEFINED AND MAINTAINED BY THE CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) FOR THE PURPOSE OF MEDICARE BILLING AND PAYMENTS. THE MEDICAL MSA CODE DIFFERS FROM THE CENSUS BUREAU/OFFICE OF MANAGEMENT & BUDGET (OMB) MSA DEFINITION IN SOME SIGNIFICANT AREAS AND IS ONLY USED FOR THOSE SITUATIONS WHERE THE CMS DEFINITION IS APPROPRIATE, SUCH AS ON MEDICAL CLAIM FORMS SUBMITTED TO CMS. THE MEDICAL MSA CODE USED BY CMS INCLUDES THE GOLDSMITH MODIFICATION, WHICH IDENTIFIES A RURAL CENSUS TRACT LOCATED WITHIN A LARGE METROPOLITAN COUNTY OF AT LEAST 1,225 SQUARE MILES, SO ISOLATED FROM THE METROPOLITAN CORE BY DISTANCE OR PHYSICAL FEATURES THAT IT IS MORE RURAL THAN URBAN IN CHARACTER. THE MEDICAL MSA FIELD CONTAINS SPECIAL MSA CODES FOR THE ZIP CODES OF ALL RURAL COUNTIES AND THE RURAL PORTION (IF ANY) OF METROPOLITAN COUNTIES. THE RURAL CODES ARE ALWAYS IN THE FORMAT 99XX, WHERE XX IS ALWAYS A TWO-DIGIT NUMERIC VALUE REPRESENTING THE SOCIAL SECURITY ADMINISTRATION (SSA) STANDARD STATE CODE. THE MSA CODES FOR RURAL AREAS ARE DEFINED BY CMS, AND DO NOT CONFORM TO THE STATE FEDERAL INFORMATION PROCESSING STANDARD (FIPS) FIPS CODING SCHEME.
                PRVDR_TEMP_RLF_SW, -- TEXT(1) | NULL | WHETHER THE PROVIDER QUALIFIES FOR A PAYMENT UPDATE UNDER THE TEMPORARY RELIEF PROVISION. Y= ENTER A Y IF THIS PROVIDER QUALIFIES FOR A PAYMENT UPDATE UNDER THE TEMPORARY RELIEF PROVISION, OTHERWISE LEAVE BLANK.
                PRVDR_TOT_PASS_THRU_AMT, -- NUMBER(6,2) | NULL | THE TOTAL PASS THROUGH AMOUNT, INCLUDING MISCELLANEOUS IS THE PER DIEM AMOUNT BASED ON THE INTERIM PAYMENTS TO THE HOSPITAL. MUST BE AT LEAST EQUAL TO PROVIDER PASS THROUGH FOR CAPITAL, PROVIDER PASS THROUGH FOR DIRECT MEDICAL EDUCATION, AND PROVIDER PASS THROUGH FOR ORGAN ACQUISITION. THE FOLLOWING ARE INCLUDED IN TOTAL PASS THROUGH AMOUNT IN ADDITION TO THE ABOVE PASS THROUGH AMOUNTS. CERTIFIED REGISTERED NURSE ANESTHETISTS (CRNAS) ARE PAID AS PART OF MISCELLANEOUS PASS THROUGH FOR RURAL HOSPITALS THAT PERFORM FEWER THAN 500 SURGERIES PER YEAR, AND NURSING AND ALLIED HEALTH PROFESSIONAL EDUCATION WHEN CONDUCTED BY A PROVIDER IN AN APPROVED PROGRAM. DO NOT INCLUDE AMOUNTS PAID FOR INDIRECT MEDICAL EDUCATION, HEMOPHILIA CLOTTING FACTORS, OR DSH ADJUSTMENTS.
                PRVDR_PSF_END_DT, -- DATE | NULL | THE DATE, AS REPORTED BY THE PROVIDER SPECIFIC FILE (PSF), IN WHICH THE REPORTING FISCAL INTERMEDIARY (FI) CEASED SERVICING THE PROVIDER
                PRVDR_WGE_IDX_CBSA_CD, -- TEXT(5) | NOT NULL | A UNIQUE IDENTIFIER OF A CORE BASED STATISTICAL AREA (CBSA), A GEOGRAPHIC ENTITY ASSOCIATED WITH AT LEAST ONE CORE OF 10,000 OR MORE POPULATION, PLUS ADJACENT TERRITORY THAT HAS A HIGH DEGREE OF SOCIAL AND ECONOMIC INTEGRATION WITH THE CORE AS MEASURED BY COMMUTING TIES. THE OMB STANDARDS DESIGNATE AND DELINEATE TWO CATEGORIES OF CBSAS: METROPOLITAN STATISTICAL AREAS AND MICROPOLITAN STATISTICAL AREAS. THE TERM CBSA WAS ADOPTED BY OMB IN 2000. THE APPROPRIATE CODE FOR THE CBSA, TO WHICH A HOSPITAL HAS BEEN RECLASSIFIED DUE TO ITS PREVAILING WAGE RATES.
                PRVDR_WGE_IDX_MSA_CD, -- TEXT(4) | NOT NULL | A CODE IDENTIFYING A MEDICAL METROPOLITAN STATISTICAL AREA (MSA) AS DEFINED AND MAINTAINED BY THE CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) FOR THE PURPOSE OF MEDICARE BILLING AND PAYMENTS. THE MEDICAL MSA CODE DIFFERS FROM THE CENSUS BUREAU/OFFICE OF MANAGEMENT & BUDGET (OMB) MSA DEFINITION IN SOME SIGNIFICANT AREAS AND IS ONLY USED FOR THOSE SITUATIONS WHERE THE CMS DEFINITION IS APPROPRIATE, SUCH AS ON MEDICAL CLAIM FORMS SUBMITTED TO CMS. THE MEDICAL MSA CODE USED BY CMS INCLUDES THE GOLDSMITH MODIFICATION, WHICH IDENTIFIES A RURAL CENSUS TRACT LOCATED WITHIN A LARGE METROPOLITAN COUNTY OF AT LEAST 1,225 SQUARE MILES, SO ISOLATED FROM THE METROPOLITAN CORE BY DISTANCE OR PHYSICAL FEATURES THAT IT IS MORE RURAL THAN URBAN IN CHARACTER. THE MEDICAL MSA FIELD CONTAINS SPECIAL MSA CODES FOR THE ZIP CODES OF ALL RURAL COUNTIES AND THE RURAL PORTION (IF ANY) OF METROPOLITAN COUNTIES. THE RURAL CODES ARE ALWAYS IN THE FORMAT 99XX, WHERE XX IS ALWAYS A TWO-DIGIT NUMERIC VALUE REPRESENTING THE SOCIAL SECURITY ADMINISTRATION (SSA) STANDARD STATE CODE. THE MSA CODES FOR RURAL AREAS ARE DEFINED BY CMS, AND DO NOT CONFORM TO THE STATE FEDERAL INFORMATION PROCESSING STANDARD (FIPS) FIPS CODING SCHEME.
                PRVDR_CMI_RATE, -- NUMBER(5,4) | NULL | A FACTOR THAT TAKES INTO CONSIDERATION PATIENT CONDITIONS AND SERVICE NEEDS. THE CASE MIX INDEX IS USED TO COMPUTE CASE MIX ADJUSTED COST PER DISCHARGE/PPS FACILITY SPECIFIC RATE WHICH HAS BEEN CALCULATED AND PUBLISHED BY CMS FOR EACH HOSPITAL (BASED ON 1981 COST AND BILLING DATA) REFLECTING THE RELATIVE COST OF THAT HOSPITALS MIX OF CASES COMPARED TO THE NATIONAL AVERAGE MIX.
                PRVDR_HRR_ADJSTMT_AMT, -- NUMBER(5,4) | NULL | THE AMOUNT THE HOSPITALÒ² READMISSION PAYMENT IS REDUCED TO ACCOUNT FOR CERTAIN EXCESS READMISSIONS WHEN THE HOSPITAL IS PARTICIPATING IN THE READMISSION REDUCTION PROGRAM.
                PRVDR_HRR_ADJSTMT_CD, -- TEXT(1) | NOT NULL | IDENTIFIES WHETHER IF A PROVIDER IS PARTICIPATING IN HOSPITAL READMISSIONS REDUCTION PROGRAM AND IF THE PAYMENT ADJUSTMENT IS 1.0000.
                PRVDR_BNDLD_CARE_DSCNT_PCT, -- NUMBER(2,2) | NULL | THE DISCOUNT % FOR HOSPITALS PARTICIPATING IN BUNDLED PAYMENTS FOR CARE IMPROVEMENT INITIATIVE (BPCI), MODEL 1 (DEMO CODE 61).
                PRVDR_PPS_BLEND_YR_CD, -- TEXT(1) | NULL | AN IDENTIFIER OF AN APPROPRIATE PERCENTAGE PAYMENT TO BE MADE ON HOME HEALTH (HH) PROSPECTIVE PAYMENT SYSTEM RAPS, OR AN IDENTIFIER OF A CODE FOR THE BLEND RATIO BETWEEN FEDERAL AND FACILITY RATES. HH PPS: 0 = PAY STANDARD PERCENTAGES 1 = PAY ZERO PERCENT IRF PPS: ALL IRFS ARE 100% FEDERAL FOR COST REPORTING PERIODS BEGINNING ON OR AFTER 10/01/2002. LTCH PPS: 1= 20 (FEDERAL %); 80 (FACILITY %) 2= 40 (FEDERAL %); 60 (FACILITY %) 3= 60 (FEDERAL %); 40 (FACILITY %) 4= 80 (FEDERAL %); 20 (FACILITY %) 5= 100 (FEDERAL %); 00 (FACILITY %) IPF PPS: 1= 25 (FEDERAL %); 75 (FACILITY %) 2= 50 (FEDERAL %); 50 (FACILITY %) 3= 75 (FEDERAL %); 25 (FACILITY %) 4= 100 (FEDERAL %); 00 (FACILITY %)
                PRVDR_VBP_ADJSTMT_FCTR_NUM, -- NUMBER(12,11) | NULL | THE VALUE BASED PURCHASING ADJUSTMENT FACTOR NUMBER
                PRVDR_VBP_PRTCPNT_SW, -- TEXT(1) | NULL | A CODE TO IDENTIFY IF PROVIDER IS PARTICIPATING IN HOSPITAL VALUE BASED PURCHASING OR NOT. Y= ENTER Ó˜Ô IF PARTICIPATING IN HOSPITAL VALUE BASED PURCHASING. N= ENTER ÓÔ IF NOT PARTICIPATING. NOTE IF DATA ELEMENT 34 (HOSPITAL QUALITY IND) IS BLANK, THEN THIS FIELD MUST = N.
                PRVDR_HAC_RDCTN_SW, -- TEXT(1) | NULL | A VALUE THAT INDICATES IF THE HOSPITAL IS SUBJECT TO A REDUCTION UNDER THE HOSPITAL-ACQUIRED CONDITION (HAC) REDUCTION PROGRAM. VALID VALUES: Y = THE HOSPITAL IS SUBJECT TO A REDUCTION UNDER THE HAC REDUCTION PROGRAM. N = THE HOSPITAL IS NOT SUBJECT TO A REDUCTION UNDER THE HAC REDUCTION PROGRAM.
                PRVDR_UNCOMPD_CARE_AMT, -- NUMBER(9,2) | NULL | A VALUE THAT REPRESENTS THE ESTIMATED PER DISCHARGE UNCOMPENSATED CARE PAYMENT AMOUNT CALCULATED AND PUBLISHED BY CMS FOR EACH HOSPITAL.
                PRVDR_EHR_PGM_RDCTN_SW, -- TEXT(1) | NULL | A VALUE THAT INDICATES IF THE HOSPITAL IS SUBJECT TO A REDUCTION DUE TO NOT BEING AN ELECTRONIC HEALTH RECORDS (EHR) MEANINGFUL USER. VALID VALUES: Y = THE HOSPITAL IS SUBJECT TO A REDUCTION DUE TO NOT BEING AN EHR MEANINGFUL USER. BLANK = THE HOSPITAL IS AN EHR RECORDS MEANINGFUL USER.
                PRVDR_LOW_VOL_ADJSTMT_FCTR_NUM, -- NUMBER(7,6) | NULL | A VALUE THAT REPRESENTS THE LOW-VOLUME (LV) HOSPITAL PAYMENT ADJUSTMENT FACTOR CALCULATED AND PUBLISHED BY CMS FOR EACH ELIGIBLE HOSPITAL.
                GEO_FIPS_STATE_CD, -- TEXT(2) | NULL | A CODE IDENTIFYING A TWO-CHARACTER ALPHABETIC ABBREVIATION FOR A STATE DEFINED BY THE FEDERAL INFORMATION PROCESSING STANDARD (FIPS). REFERENCE TABLE: GEO_FIPS_STATE_CD
                GEO_FIPS_CNTY_CD, -- TEXT(3) | NULL | A CODE IDENTIFYING A UNITED STATES COUNTY AS ASSIGNED BY THE FEDERAL INFORMATION PROCESSING STANDARD (FIPS). REFERENCE TABLE: GEO_FIPS_CNTY_CD
                META_SK, -- NUMBER(38) | NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_MDCR_PRFMNC_ADJSTMT_PCT, -- NUMBER(5,4) | NULL | A SCALED ADJUSTMENT PERCENTAGE CALCULATED AND PUBLISHED BY THE CENTERS FOR MEDICARE AND MEDICAID SERVICES (CMS) FOR EACH HOSPITAL BASED ON ITS PERFORMANCE RELATIVE TO A MEDICARE TOTAL COST OF CARE (TCOC) BENCHMARK.
                PRVDR_LTCH_DSCHRG_PYMT_PCTG_SW, -- TEXT(1) | NULL | AN INDICATOR IN THE PROVIDER SPECIFIC FILE (PSF) IDENTIFYING WHETHER THE LONG TERM CARE HOSPITAL (LTCH) IS SUBJECT TO THE DISCHARGE PAYMENT PERCENTAGE (DPP) PAYMENT ADJUSTMENT FOR FAILURE TO MAINTAIN THE REQUIRED DISCHARGE PAYMENT PERCENTAGE. VALID VALUES: BLANK - LTCH IS NOT SUBJECT TO THE DPP PAYMENT ADJUSTMENT. Y - LTCH IS SUBJECT TO THE DPP PAYMENT ADJUSTMENT.
                PRVDR_SPLMTL_WGE_IDX_RATE, -- NUMBER(6,4) | NULL | A SUPPLEMENTAL WAGE INDEX THAT CERTAIN PROVIDERS MAY BE ASSIGNED.
                PRVDR_SPLMTL_WGE_IDX_SW, -- TEXT(1) | NULL | A SUPPLEMENTAL WAGE INDEX FLAG THAT CERTAIN PROVIDERS MAY BE ASSIGNED. VALID VALUES: 1 - PRIOR YEAR WAGE INDEX 2 - SPECIAL INPATIENT PROSPECTIVE PAYMENT SYSTEM (IPPS) - COMPARABLE WAGE INDEX* *ONLY FOR LONG TERM CARE HOSPITAL (LTCH) PROVIDERS. PRICER WILL OVERRIDE THE OTHERWISE DETERMINED IPPS COMPARABLE WAGE INDEX WITH THIS VALUE.
                PRVDR_PASS_THRU_ASC_ACQSTN_AMT, -- NUMBER(9,2) | NOT NULL | THE PER DIEM AMOUNT BASED ON THE INTERIM PAYMENTS TO THE HOSPITAL. INCLUDES ACQUISITION AMOUNTS FOR ALLOGENEIC STEM CELL TRANSPLANTS.
                PRVDR_PASS_THRU_DRCT_GME_AMT, -- NUMBER(6,2) | NOT NULL | THE PER DIEM AMOUNT OF DIRECT GRADUATE MEDICAL EDUCATION TO BE EXCLUDED FROM THE MEDICARE ADVANTAGE (MA) CAPITATION RATES PER REGULATION.
                PRVDR_PASS_THRU_KDNY_AMT, -- NUMBER(6,2) | NOT NULL | THE PER DIEM AMOUNT OF KIDNEY ACQUISITION COSTS TO BE EXCLUDED FROM THE MEDICARE ADVANTAGE (MA) CAPITATION RATES PER REGULATION.
                PASS_THRU_SUPLY_CHAIN_AMT -- NUMBER(9,2) | NULL | THE PER DIEM AMOUNT BASED ON THE INTERIM PAYMENTS TO THE HOSPITAL. INCLUDES PAYMENT ADJUSTMENTS FOR THE ADDITIONAL RESOURCE COSTS OF ESTABLISHING AND MAINTAINING ACCESS TO BUFFER STOCKS OF ESSENTIAL MEDICINES. ALSO INCLUDE PAYMENT ADJUSTMENTS FOR THE ADDITIONAL COST FOR PROCUREMENT OF WHOLLY DOMESTICALLY MADE NIOSH-APPROVED SURGICAL N95 RESPIRATORS.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PSF"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrPsfExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
