"""
==========
V2_MDCR_PRVDR_NCPDP_HSTRY IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_HSTRY

Table Type: VIEW
Columns: 101
Source Pattern: %mdcr_prvdr%
Table Comment: NCPDP MAINTAINED INFORMATION ASSIGNED TO EVERY LICENSED PHARMACY IN THE UNITED STATES AND TERRITORIES.  THIS TABLE HOLDS THE VERSIONED INFORMATION.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrNcpdpHstryExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrNcpdpHstryExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_NCPDP_HSTRY data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_HSTRY (VIEW)
    Columns: 101
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_ncpdp_hstry_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_NCPDP_HSTRY export.
        
        Includes all 101 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NCPDP_ID, -- TEXT(7) | NOT NULL | THE PROVIDERS NCPDP NUMBER.
                PRVDR_NCPDP_EFCTV_DT, -- DATE | NOT NULL | DATE THAT A VERSION OF A NCPDP BECAME EFFECTIVE.
                PRVDR_NCPDP_OBSLT_DT, -- DATE | NULL | DATE THAT A VERSION OF A NCPDP BECAME OBSOLETE.
                PRVDR_NCPDP_DBA_NAME, -- TEXT(60) | NULL | THE DBA (DOING BUSINESS AS) NAME OF THE PROVIDER.
                PRVDR_NCPDP_LGL_BUSNS_NAME, -- TEXT(60) | NULL | THE SELF DESIGNATED LEGAL NAME OF THE ENTITY
                PRVDR_NCPDP_STORE_NUM, -- TEXT(10) | NULL | THE STORE NUMBER (USUALLY ASSIGNED BY PARENT COMPANY) ASSOCIATED WITH THE PROVIDER.
                PRVDR_NCPDP_LINE_1_ADR, -- TEXT(55) | NULL | THE PHYSICAL LOCATION OF THE STORE AND FIRST LINE OF THE ADDRESS.
                PRVDR_NCPDP_LINE_2_ADR, -- TEXT(55) | NULL | THE SECOND LINE OF THE PHYSICAL ADDRESS.
                PRVDR_NCPDP_INVLD_PLC_NAME, -- TEXT(30) | NULL | INVALID PHYSICAL PLACE NAME. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_INVLD_STATE_CD, -- TEXT(2) | NULL | INNVALID PHYSICAL STATE CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_INVLD_ZIP_CD, -- TEXT(9) | NULL | INVALID PHYSICAL ZIP CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_INVLD_CNTY_CD, -- TEXT(5) | NULL | INVALID COUNTRY CODE. POPULATED WHEN COUNTRY CODE IS NOT VALID.
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_NCPDP_SITE_TEL_NUM, -- TEXT(10) | NULL | TELEPHONE NUMBER.
                PRVDR_NCPDP_SITE_EXTNSN_NUM, -- TEXT(5) | NULL | TELEPHONE EXTENSION.
                PRVDR_NCPDP_SITE_FAX_NUM, -- TEXT(10) | NULL | FAX NUMBER.
                PRVDR_NCPDP_SITE_EMAIL_ADR, -- TEXT(50) | NULL | E-MAIL ADDRESS OF PHARMACY IF DIFFERENT THAN PRIMARY CONTACT E-MAIL.
                PRVDR_NCPDP_SITE_DRCTN_TXT, -- TEXT(50) | NULL | TEXT STATING CROSS STREET OR DIRECTIONS FOR PHYSICAL LOCATION OF PROVIDER.
                PRVDR_NCPDP_INVLD_METSA_CD, -- TEXT(4) | NULL
                PRVDR_NCPDP_INVLD_P_METSA_CD, -- TEXT(4) | NULL
                PRVDR_NCPDP_24_HR_IND, -- TEXT(1) | NULL | INDICATES WHETHER THIS PROVIDER OPERATES 24 HOURS A DAY. [Y] = YES; [N] = NO
                PRVDR_NCPDP_MON_OPEN_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION OPENS FOR BUSINESS.
                PRVDR_NCPDP_MON_CLOSE_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION CLOSES FOR BUSINESS.
                PRVDR_NCPDP_TUE_OPEN_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION OPENS FOR BUSINESS.
                PRVDR_NCPDP_TUE_CLOSE_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION CLOSES FOR BUSINESS.
                PRVDR_NCPDP_WED_OPEN_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION OPENS FOR BUSINESS.
                PRVDR_NCPDP_WED_CLOSE_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION CLOSES FOR BUSINESS.
                PRVDR_NCPDP_THU_OPEN_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION OPENS FOR BUSINESS.
                PRVDR_NCPDP_THU_CLOSE_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION CLOSES FOR BUSINESS.
                PRVDR_NCPDP_FRI_OPEN_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION OPENS FOR BUSINESS.
                PRVDR_NCPDP_FRI_CLOSE_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION CLOSES FOR BUSINESS.
                PRVDR_NCPDP_SAT_OPEN_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION OPENS FOR BUSINESS.
                PRVDR_NCPDP_SAT_CLOSE_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION CLOSES FOR BUSINESS.
                PRVDR_NCPDP_SUN_OPEN_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION OPENS FOR BUSINESS.
                PRVDR_NCPDP_SUN_CLOSE_HR_TIME, -- NUMBER(2) | NULL | TIME (IN HOURS) WHEN THE LOCATION CLOSES FOR BUSINESS.
                PRVDR_NCPDP_E_RX_IND, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER ACCEPTS NCPDP SCRIPT TRANSACTIONS.
                PRVDR_NCPDP_DLVRY_SVC_IND, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER PROVIDES PRESCRIPTION DELIVERY SERVICE.
                PRVDR_NCPDP_CMPNDG_IND, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER PROVIDES PRESCRIPTION COMPOUNDING SERVICES.
                PRVDR_NCPDP_DRV_UP_WNDW_IND, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER HAS A DRIVE UP WINDOW.
                PRVDR_NCPDP_DME_IND, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER SELLS DURABLE MEDICAL EQUIPMENT (DME).
                PRVDR_NCPDP_INVLD_CNGRSL_ID, -- TEXT(4) | NULL | INVALID CONGRESSIONAL DISTRICT. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_PHYS_1_LANG_CD, -- TEXT(2) | NULL | CODE THAT IDENTIFIES LANGUAGES. EXAMPLES INCLUDE: ENGLISH, SPANISH AND FRENCH.
                PRVDR_NCPDP_PHYS_2_LANG_CD, -- TEXT(2) | NULL | CODE THAT IDENTIFIES LANGUAGES. EXAMPLES INCLUDE: ENGLISH, SPANISH AND FRENCH.
                PRVDR_NCPDP_PHYS_3_LANG_CD, -- TEXT(2) | NULL | CODE THAT IDENTIFIES LANGUAGES. EXAMPLES INCLUDE: ENGLISH, SPANISH AND FRENCH.
                PRVDR_NCPDP_PHYS_4_LANG_CD, -- TEXT(2) | NULL | CODE THAT IDENTIFIES LANGUAGES. EXAMPLES INCLUDE: ENGLISH, SPANISH AND FRENCH.
                PRVDR_NCPDP_PHYS_5_LANG_CD, -- TEXT(2) | NULL | CODE THAT IDENTIFIES LANGUAGES. EXAMPLES INCLUDE: ENGLISH, SPANISH AND FRENCH.
                PRVDR_NCPDP_HNDCP_IND, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER IS ACCESSIBLE FOR HANDICAPPED INDIVIDUALS.
                PRVDR_NCPDP_STORE_OPEN_DT, -- DATE | NULL | DATE OF STORE OPENING.
                PRVDR_NCPDP_STORE_CLSR_DT, -- DATE | NULL | DATE AFTER WHICH STORE IS NO LONGER OPEN FOR BUSINESS.
                PRVDR_NCPDP_MLG_LINE_1_ADR, -- TEXT(55) | NULL | THE FIRST LINE OF THE MAILING ADDRESS.
                PRVDR_NCPDP_MLG_LINE_2_ADR, -- TEXT(55) | NULL | THE SECOND LINE OF THE MAILING ADDRESS.
                PRVDR_NCPDP_INVLD_MLG_PLC_NAME, -- TEXT(30) | NULL | INVALID MAILING PLACE NAME. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_INVLD_MLG_STATE_CD, -- TEXT(2) | NULL | INVALID MAILING STATE CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_INVLD_MLG_ZIP_CD, -- TEXT(9) | NULL | INVALID MAILING ZIP CODE
                GEO_MLG_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_MLG_ZIP4_CD, -- TEXT(4) | NULL | A FOUR DIGIT EXTENSION TO A ZIP CODE THAT REPRESENTS A SUBDIVISION FOR MAILING PURPOSES OF THE ZIP CODE.
                PRVDR_NCPDP_CNTCT_1ST_NAME, -- TEXT(20) | NULL | FIRST NAME OF PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_CNTCT_MDL_NAME, -- TEXT(1) | NULL | MIDDLE INITIAL OF THE PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_CNTCT_LAST_NAME, -- TEXT(20) | NULL | LAST NAME OF THE PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_CNTCT_TITLE_NAME, -- TEXT(30) | NULL | TITLE OF THE PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_CNTCT_TEL_NUM, -- TEXT(10) | NULL | THE CONTACTS PHONE NUMBER INCLUDING AREA CODE.
                PRVDR_NCPDP_CNTCT_EXTNSN_NUM, -- TEXT(5) | NULL | THE PHONE EXTENSION FOR THE CONTACT.
                PRVDR_NCPDP_CNTCT_EMAIL_ADR, -- TEXT(50) | NULL | E-MAIL ADDRESS OF THE CONTACT.
                PRVDR_NCPDP_DSPNSR_CLS_CD, -- TEXT(2) | NULL | THE CLASS CODE ASSOCIATED WITH THIS PROVIDER. THE DISPENSER CLASS CODE IS SELF-DESIGNATED AND IS NOT RELATED TO TAXONOMY CODES.
                PRVDR_NCPDP_1_DSPNSR_TYPE_CD, -- TEXT(2) | NULL | THIS FIELD CONTAINS THE PROVIDERÒ² DISPENSER TYPE CODE. PRIMARY DISPENSER TYPE CANNOT BE BLANK. SECONDARY THROUGH TERTIARY MAY CONTAIN BLANK (MEANING NONE / NOT SPECIFIED OR NOT APPLICABLE ).
                PRVDR_NCPDP_2_DSPNSR_TYPE_CD, -- TEXT(2) | NULL | THIS FIELD CONTAINS THE PROVIDERÒ² DISPENSER TYPE CODE. PRIMARY DISPENSER TYPE CANNOT BE BLANK. SECONDARY THROUGH TERTIARY MAY CONTAIN BLANK (MEANING NONE / NOT SPECIFIED OR NOT APPLICABLE ).
                PRVDR_NCPDP_3_DSPNSR_TYPE_CD, -- TEXT(2) | NULL | THIS FIELD CONTAINS THE PROVIDERÒ² DISPENSER TYPE CODE. PRIMARY DISPENSER TYPE CANNOT BE BLANK. SECONDARY THROUGH TERTIARY MAY CONTAIN BLANK (MEANING NONE / NOT SPECIFIED OR NOT APPLICABLE ).
                PRVDR_NCPDP_UPIN_ID, -- TEXT(10) | NULL | UNIVERSAL PROVIDER ID NUMBER (UPIN) OF THE PROVIDER USED TO SUBMIT MEDICARE CLAIMS.
                PRVDR_NCPDP_NPI, -- TEXT(10) | NULL | THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS. AT THE PHARMACY OR ALTERNATE DISPENSING SITE LEVEL.
                PRVDR_NCPDP_DEA_ID, -- TEXT(12) | NULL | THIS FIELD CONTAINS THE DRUG ENFORCEMENT ADMINISTRATION (DEA) NUMBER OF THE PROVIDER. FORMERLY CALLED THE FEDERAL LICENSE NUMBER FROM NCPDP.
                PRVDR_NCPDP_FED_TAX_NUM, -- TEXT(15) | NULL | THE FEDERAL TAX ID NUMBER OF THE PROVIDER. ALSO KNOWN AS EIN OR TIN.
                PRVDR_NCPDP_STATE_LCNS_NUM, -- TEXT(20) | NULL | THE STATE BOARD OF PROVIDER LICENSE NUMBER ASSIGNED TO THE PROVIDER.
                PRVDR_NCPDP_STATE_TAX_NUM, -- TEXT(15) | NULL | THIS FIELD CONTAINS THE STATE TAX ID OF THE PROVIDER.
                PRVDR_NCPDP_DLT_DT, -- DATE | NULL | THE DATE STAMPED BY NCPDP THAT THIS INFORMATION IS NO LONGER ACTIVE.
                PRVDR_NCPDP_HSTRY_VRSN_DT, -- DATE | NULL | VERSION DATE FOR PARTY NCPDP HISTORY REFLECTING THE SOURCE DATE OF THE NCPDP DATA.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_NCPDP_CLOSE_DOOR_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_CLOSE_DOOR_SW, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT SITE IS A CLOSED DOOR FACILITY. BLANK FIELD = UNREPORTED.
                PRVDR_NCPDP_CMPND_SRVC_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_DEA_EXPRTN_DT, -- DATE | NULL | THE DATE THE DRUG ENFORCEMENT ADMINISTRATION (DEA) REQUIRES THE FEDERAL LICENSE BE RENEWED BY.
                PRVDR_NCPDP_DEACTVTN_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE REASON FOR DEACTIVATION OF THE RECORD.
                PRVDR_NCPDP_DLVRY_SVC_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_DME_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_DRV_UP_WNDW_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_ELCTRNC_RX_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_EMER_SRVC_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_EMER_SRVC_SW, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER OFFERS SOME LEVEL OF 24-HOUR EMERGENCY SERVICE. BLANK FIELD = UNREPORTED.
                PRVDR_NCPDP_HNDCP_ACSBL_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_IMNZTN_PRVDD_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_IMNZTN_PRVDD_SW, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER OFFERS SOME LEVEL IMMUNIZATIONS ON-SITE. BLANK FIELD = UNREPORTED.
                PRVDR_NCPDP_MLT_DOSE_PACKG_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_MLT_DOSE_PACKG_SW, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER OFFERS SOME LEVEL OF MULTI-DOSE COMPLIANCE PACKAGING. BLANK FIELD = UNREPORTED.
                PRVDR_NCPDP_PHYSN_NAME, -- TEXT(60) | NULL | THE NAME OF THE DOCTOR DISPENSING AT THE ALTERNATE DISPENSING SITE. THIS WILL ONLY BE POPULATED IF THE PRIMARY PROVIDER TYPE = 7 (NON-PHARMACY DISPENSING SITE), AND THE PROVIDER CLASS = 7 (ALTERNATE DISPENSING SITE)
                PRVDR_NCPDP_REINSTMT_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE REASON FOR REACTIVATION OF THE RECORD.
                PRVDR_NCPDP_REINSTMT_DT, -- DATE | NULL | DATE THE REINSTATEMENT OF THE RECORD OCCURS.
                PRVDR_NCPDP_STUS_340B_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_STUS_340B_SW, -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT SITE OFFERS SOME LEVEL OF 340B SERVICE. BLANK FIELD = UNREPORTED.
                PRVDR_NCPDP_WLK_IN_CLNC_CD, -- TEXT(2) | NULL | CODE REPRESENTING THE TYPE OF SERVICE OFFERED
                PRVDR_NCPDP_WLK_IN_CLNC_SW -- TEXT(1) | NULL | (Y)ES OR (N)O INDICATOR THAT PROVIDER OFFERS SOME LEVEL OF WALK-IN CLINICAL SERVICES. BLANK FIELD = UNREPORTED.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_HSTRY"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrNcpdpHstryExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
