"""
==========
V2_MDCR_PRVDR_OF_SRVC_NON_CLIA IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_NON_CLIA

Table Type: VIEW
Columns: 471
Source Pattern: %mdcr_prvdr%
Table Comment: AN INSTITUTIONAL PROVIDER THAT IS NOT A MEDICARE-APPROVED CLINICAL LABORATORY PROVIDER.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrOfSrvcNonCliaExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrOfSrvcNonCliaExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_OF_SRVC_NON_CLIA data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_NON_CLIA (VIEW)
    Columns: 471
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_of_srvc_non_clia_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_OF_SRVC_NON_CLIA export.
        
        Includes all 471 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_OSCAR_NUM, -- TEXT(10) | NOT NULL | THE IDENTIFICATION NUMBER OF THE INSTITUTIONAL PROVIDER CERTIFIED BY MEDICARE TO PROVIDE SERVICES TO THE BENEFICIARY (I.E., THE CMS CERTIFICATION NUMBER, CNN; AKA ONLINE SURVEY CERTIFICATION AND REPORTING SYSTEM NUMBER (OSCAR) ). THIS REPRESENTS ADDITIONAL INFORMATION THAT IS SPECIFIC TO THE COLUMN IN THE VIEW.
                PRVDR_OF_SRVC_EFCTV_DT, -- DATE | NOT NULL | THE DATE THAT THE PROVIDER DATA BECAME EFFECTIVE
                PRVDR_ACRDTN_BGN_DT, -- DATE | NULL | THE BEGIN DATE OF THE CURRENT PERIOD OF ACCREDITATION BY EITHER THE JOINT COMMISSION ON ACCREDITATION OF HEALTH CARE ORGANIZATIONS (JCAHO) OR THE AMERICAN OSTEOPATHIC ASSOCIATION (AOA).
                PRVDR_ACRDTN_TYPE_CD, -- TEXT(1) | NULL | A CODE TO IDENTIFY A PROVIDER ACCREDITATION SERVICE.
                PRVDR_ACRDTN_END_DT, -- DATE | NOT NULL | THE END DATE OF THE CURRENT PERIOD OF ACCREDITATION EITHER BY THE JOINT COMMISSION ON ACCREDITATION OF HEALTH CARE ORGANIZATIONS (JCAHO) OR THE AMERICAN OSTEOPATHIC ASSOCIATION (AOA).
                PRVDR_ACTVTY_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ACTIVITY SERVICES ARE PROVIDED OFF-SITE TO RESIDENTS.
                PRVDR_ACTVTY_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ACTIVITY SERVICES ARE PROVIDED ON-SITE TO NONRESIDENTS.
                PRVDR_ACUTE_RESP_CARE_CD, -- TEXT(1) | NULL | A CODE TO IDENTIFY THE TYPE OF ALTERNATIVE INPATIENT CARE RENDERED BY THE HOSPICE PROVIDER. - ACUTE AND/OR RESPITE SHORT TERM INPATIENT CARE.
                PRVDR_ACUTE_RNL_DLYS_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW ACUTE RENAL DIALYSIS SERVICES ARE PROVIDED IN A HOSPITAL.
                PRVDR_ACTVTY_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ACTIVITY SERVICES ARE PROVIDED ON-SITE TO NONRESIDENTS.
                PRVDR_ALCHL_DRUG_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW ALCOHOL AND/OR DRUG SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_ANSTHSA_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW ANESTHESIA SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_APLNC_EQUIP_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW APPLIANCE AND EQUIPMENT SERVICES ARE PROVIDED BY A HOME HEALTH AGENCY (HHA).
                PRVDR_ADMSN_SUSPNSN_BGN_DT, -- DATE | NOT NULL | THE DATE A SUSPENSION OF ADMISSIONS WAS INVOKED FOR A PROVIDER.
                PRVDR_ADMSN_SUSPNSN_END_DT, -- DATE | NOT NULL | THE RESCIND DATE FOR THE SUSPENSION OF PAYMENTS FOR NEW ADMISSIONS TO A LONG TERM CARE (LTC) FACILITY.
                PRVDR_AUDLGY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW AUDIOLOGY SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_APRVD_DLYS_STN_CNT, -- NUMBER(7,2) | NULL | THE TOTAL NUMBER OF APPROVED DIALYSIS STATIONS IN AN END-STAGE RENAL DIALYSIS FACILITY.
                PRVDR_BED_PER_ROOM_WVR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A WAIVER OF THE BEDS PER ROOM REQUIREMENT HAS BEEN RECOMMENDED FOR A FACILITY.
                PRVDR_BLOOD_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ADMINISTRATION AND STORAGE OF BLOOD SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_BLOOD_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ADMINISTRATION AND STORAGE OF BLOOD SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_BLOOD_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ADMINISTRATION AND STORAGE OF BLOOD SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_BRNCH_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BRANCHES OPERATED BY THE FACILITY.
                PRVDR_BRNCH_OPRTN_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE FACILITY OPERATES ANY BRANCHES.
                PRVDR_BURN_CARE_UNIT_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW BURN CARE UNIT SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_CARF_IP_REHAB_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW CARF INPATIENT REHABILITATION SERVICE IS PROVIDED.
                PRVDR_BSD_FAC_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A LONG TERM CARE FACILITY IS PROVIDER BASED.
                PRVDR_CCU_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW CORONARY CARE UNIT SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_ADLSCNT_PSYCH_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW CHILD ADOLESCENT PSYCHIATRIC SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_CHMTHRPY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW CHEMOTHERAPY SERVICE IS PROVIDED.
                PRVDR_CHRPRCTIC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW CHIROPRACTIC SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_CHOW_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A HOME HEALTH AGENCY (HHA) HAS UNDERGONE A CHANGE OF OWNERSHIP (CHOW) SINCE THE LAST SURVEY.
                PRVDR_CL_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER CLINICAL LABORATORY SERVICES ARE PROVIDED IN A HOSPITAL.
                PRVDR_CL_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER CLINICAL LABORATORY SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_CL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATEHOW CLINICAL LABORATORY SERVICES ARE PROVIDED IN A HOSPITAL.
                PRVDR_CNSLNG_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW COUNSELING SERVICES ARE PROVIDED BY A HOSPICE.
                PRVDR_CRDC_CTHRTZTN_LAB_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW CARDIAC CATHETERIZATION LAB SERVICE IS PROVIDED.
                PRVDR_CL_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER CLINICAL LABORATORY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_CT_SCNR_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW CT SCANNER SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_DGNSTC_RDLGY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW DIAGNOSTIC RADIOLOGY SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_CRTFD_AREA_BED_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN MEDICARE AND/OR MEDICAID CERTIFIED AREAS WITHIN A FACILITY.
                PRVDR_DNTL_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DENTAL SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_DNTL_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DENTAL SERVICES ARE PROVIDED ON-SITE TO NONRESIDENTS.
                PRVDR_DNTL_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DENTAL SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_DNTL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW DENTAL SERVICES ARE PROVIDED.
                PRVDR_DRCTR_QUALN_CD, -- TEXT(1) | NOT NULL | INDICATES THE QUALIFICATIONS OF THE DIRECTOR OF A SUPPLIER OF PORTABLE X-RAY SERVICES.
                PRVDR_DTRY_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DIETARY SERVICES ARE PROVIDED OFFSITE TO NONRESIDENTS.
                PRVDR_DTRY_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DIETARY SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_DTRY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW DIETARY SERVICES ARE PROVIDED.
                PRVDR_EKG_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW EKG SERVICES ARE PROVIDED BY AN AMBULATORY SURGICAL CENTER (ASC)
                PRVDR_DTRY_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DIETARY SERVICES ARE PROVIDED ON-SITE TO RESIDENTS.
                PRVDR_ER_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW DEDICATED EMERGENCY DEPARTMENT SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_EMER_HOSP_MEET_1861_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER AN EMERGENCY HOSPITAL MEETS THE DEFINITION OF HOSPITAL CONTAINED IN SECTION 1861 OF THE SOCIAL SECURITY ACT.
                PRVDR_ESWL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW EXTRACORPOREAL SHOCKWAVE LITHOTRIPTER SERVICES ARE PROVIDED IN A HOSPITAL.
                PRVDR_ESRD_NTWRK_NUM, -- TEXT(2) | NULL | THE NUMBER OF THE NETWORK TO WHICH THE END-STAGE RENAL DIALYSIS FACILITY IS ASSIGNED.
                PRVDR_FAC_CTGRY_CD, -- TEXT(2) | NOT NULL | A CODE TO INDICATE THE CATEGORY THAT REPRESENTS THE TYPE OF FACILITY.
                PRVDR_EXPRMT_RSRCH_CNDCTD_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A FACILITY USES RESIDENTS TO DEVELOP AND TEST CLINICAL TREATMENTS.
                PRVDR_FED_FUNDNG_FQHC_SW, -- TEXT(1) | NULL | INDICATES WHETHER A FQHC (FEDERALLY QUALIFIED HEALTH CENTER) IS FEDERALLY FUNDED.
                PRVDR_FED_PGM_SPRT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A CLINIC IS RECEIVING SUPPORT FROM A FEDERAL PROGRAM TO PROVIDE HEALTH SERVICES IN A MEDICALLY UNDERSERVED AREA OR IN AN AREA WITH A SHORTAGE OF PRIMARY CARE HEALTH MANPOWER.
                PRVDR_FLTM_EMPLEE_CNT, -- NUMBER(8,2) | NULL | THE TOTAL NUMBER OF FULL-TIME EMPLOYEES IN A HOSPICE OR AN INTERMEDIATE CARE FACILITY/MENTAL RETARDATION FACILITY.
                PRVDR_FQHC_APRVD_RHC_PRVDR_NUM, -- TEXT(10) | NULL | THE CMS PROVIDER IDENTIFIER NUMBER FOR A MEDICARE CERTIFIED RURAL HEALTH CLINIC (RHC) WITH FEDERALLY QUALIFIED HEALTH CENTER (FQHC) APPROVAL. AN RHC IS A CLINIC THAT IS LOCATED IN A RURAL AREA DESIGNATED AS A SHORTAGE AREA, IS NOT A REHABILITATION AGENCY OR A FACILITY PRIMARILY FOR THE CARE AND TREATMENT OF MENTAL DISEASES, AND MEETS ALL OTHER REQUIREMENTS OF 42 CFR 405 AND 491. CANT FIND THIS IN THE LAYOUT JC: IS THIS THE OSCAR NUMBER?
                PRVDR_FQHC_APRVD_RHC_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE FEDERALLY QUALIFIED HEALTH CENTER (FQHC) WAS A MEDICARE CERTIFIED RURAL HEALTH CLINIC (RHC). AN RHC IS A CLINIC THAT IS LOCATED IN A RURAL AREA DESIGNATED AS A SHORTAGE AREA, IS NOT A REHABILITATION AGENCY OR A FACILITY PRIMARILY FOR THE CARE AND TREATMENT OF MENTAL DISEASES, AND MEETS ALL OTHER REQUIREMENTS OF 42 CFR 405 AND 491.
                PRVDR_FTE_ADMIN_NRS_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NURSES WITH ADMINISTRATIVE DUTIES UNDER CONTRACT TO A FACILITY
                PRVDR_FTE_ADMIN_NRS_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NURSES WITH ADMINISTRATIVE DUTIES EMPLOYED BY A FACILITY ON A FULL-TIME BASIS
                PRVDR_FTE_ADMIN_NRS_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NURSES WITH ADMINISTRATIVE DUTIES EMPLOYED BY A FACILITY ON A PART-TIME BASIS
                PRVDR_FTE_ADMINR_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT ADMINISTRATIVE STAFF UNDER CONTRACT TO A FACILITY.
                PRVDR_FTE_ADMINR_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF PART-TIME EQUIVALENT ADMINISTRATIVE STAFF UNDER CONTRACT TO A FACILITY.
                PRVDR_FTE_ADMINR_PTP_CNT, -- NUMBER(7,2) | NULL | THE TOTAL NUMBER OF PART-TIME ADMINISTRAORS WHO ARE CONTRACTED WITH THE PROVIDER.
                PRVDR_FTE_CNSLR_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT COUNSELORS EMPLOYED BY A HOSPICE
                PRVDR_FTE_CNSLR_VLNTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT VOLUNTEER COUNSELORS IN A HOSPICE
                PRVDR_FTE_CRNA_EMPLEE_CNT, -- NUMBER(7,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT CERTIFIED REGISTERED NURSE ANESTHETISTS (CRNA) EMPLOYED BY A HOSPITAL.
                PRVDR_FTE_DIETN_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT DIETITIANS UNDER CONTRACT TO A FACILITY
                PRVDR_FTE_DIETN_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT DIETITIANS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS
                PRVDR_FTE_DIETN_EMPLEE_TOT_CNT, -- NUMBER(7,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT DIETITIANS EMPLOYED BY A FACILITY .
                PRVDR_FTE_DIETN_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT DIETITIANS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_DNTST_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT DENTISTS UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_DNTST_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT DENTISTS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_DNTST_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT DENTISTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_DRCT_CARE_EMPLEE_CNT, -- NUMBER(7,2) | NULL | NUMBER OF FULL-TIME EQUIVALENT DIRECT CARE PERSONNEL EMPLOYED BY AN INTERMEDIATE CARE FACILITY FOR THE MENTALLY RETARDED .
                PRVDR_FTE_FOOD_SRVC_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT FOOD SERVICE PERSONNEL UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_FOOD_SRVC_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT FOOD SERVICE PERSONNEL EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_FOOD_SRVC_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT FOOD SERVICE PERSONNEL EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_HHA_EMPLEE_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT HOME HEALTH AIDES EMPLOYED BY A HOME HEALTH AGENCY OR HOSPICE .
                PRVDR_FTE_HHA_VLNTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT VOLUNTEER HOME HEALTH AIDES IN A HOSPICE .
                PRVDR_FTE_HMMKR_EMPLEE_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT HOMEMAKERS EMPLOYED BY A HOSPICE .
                PRVDR_FTE_HMMKR_VLNTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT VOLUNTEER HOMEMAKERS IN A HOSPICE .
                PRVDR_FTE_HSEKPNG_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT HOUSEKEEPING PERSONNEL UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_HSEKPNG_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT HOUSEKEEPING PERSONNEL EMPLOYED BY A FACILITY ON A FULL TIME BASIS .
                PRVDR_FTE_HSEKPNG_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT HOUSEKEEPING PERSONNEL EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_LPN_LVN_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT LICENSED PRACTICAL/VOCATIONAL NURSES UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_LPN_LVN_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT LICENSED PRACTICAL OR VOCATIONAL NURSES EMPLOYED BY A FACILITY .
                PRVDR_FTE_LPN_LVN_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT LICENSED PRACTICAL/VOCATIONAL NURSES EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_LPN_LVN_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT LICENSED PRACTICAL/VOCATIONAL NURSES EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_LPN_LVN_VLNTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT VOLUNTEER LICENSED PRACTICAL/VOCATIONAL NURSES IN A HOSPICE .
                PRVDR_FTE_MH_SRVC_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MENTAL HEALTH SERVICES PERSONNEL UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_MH_SRVC_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MENTAL HEALTH SERVICES PERSONNEL EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_MH_SRVC_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MENTAL HEALTH SERVICES PERSONNEL EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_MSW_EMPLEE_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICAL SOCIAL WORKERS EMPLOYED BY A HOSPITAL OR HOSPICE.
                PRVDR_FTE_MSW_VLNTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT VOLUNTEER MEDICAL SOCIAL WORKERS IN A HOSPICE .
                PRVDR_FTE_MT_EMPLEE_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICAL TECHNOLOGISTS EMPLOYED BY A FACILITY .
                PRVDR_FTE_NAT_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NURSE AIDES IN TRAINING UNDER CONTRACT TO A FACILITY
                PRVDR_FTE_NAT_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NURSE AIDES IN TRAINING EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_NAT_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NURSE AIDES IN TRAINING EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_NRS_AIDE_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT CERTIFIED NURSE AIDES UNDER CONTRACT TO A FACILITY.
                PRVDR_FTE_NRS_AIDE_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT CERTIFIED NURSE AIDES EMPLOYED BY A FACILITY ON A FULL-TIME BASIS.
                PRVDR_FTE_NRS_AIDE_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT CERTIFIED NURSE AIDES EMPLOYED BY A FACILITY ON A PART-TIME BASIS.
                PRVDR_FTE_NRS_PRCTNR_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NURSE PRACTITIONERS IN A RURAL HEALTH CLINIC .
                PRVDR_FTE_NUCLR_MDCN_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NUCLEAR MEDICINE TECHNICIANS EMPLOYED BY A FACILITY .
                PRVDR_FTE_OT_AIDE_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPY AIDES UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_OT_AIDE_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPY AIDES UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_OT_AIDE_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPY AIDES EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_OT_ASTNT_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPY ASSISTANTS UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_OT_ASTNT_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPY ASSISTANTS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_OT_ASTNT_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPY ASSISTANTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_OT_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPISTS UNDER CONTRACT TO A FACILITY.
                PRVDR_FTE_OT_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPISTS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_OT_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPISTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_OT_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OCCUPATIONAL THERAPISTS EMPLOYED BY A PROVIDER.
                PRVDR_FTE_OTHR_STF_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT STAFF NOT INCLUDED IN ANY OTHER CATEGORIES UNDER CONTRACT TO THE FACILITY .
                PRVDR_FTE_OTHR_STF_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PERSONS NOT INCLUDED IN ANY OTHER CATEGORIES EMPLOYED BY THE FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_OTHR_STF_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PERSONS NOT INCLUDED IN ANY OTHER CATEGORIES EMPLOYED BY THE FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_OTHR_STF_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OTHER VOLUNTEERS IN A HOSPICE .
                PRVDR_FTE_PDTRST_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PODIATRISTS UNDER CONTRACT TO A FACILITY.
                PRVDR_FTE_PDTRST_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PODIATRISTS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS.
                PRVDR_FTE_PDTRST_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PODIATRISTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS.
                PRVDR_FTE_PHRMCST_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHARMACISTS UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_PHRMCST_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHARMACISTS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_PHRMCST_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHARMACISTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_PSYCHLGST_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PSYCHOLOGISTS EMPLOYED BY A PROVIDER .
                PRVDR_FTE_PHYSN_ASTNT_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICIAN ASSISTANTS (PA) EMPLOYED BY A HOSPITAL OR RURAL HEALTH CLINIC .
                PRVDR_FTE_PHYSN_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NON-CLIA PHYSICIANS UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_PHYSN_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NON-CLIA PHYSICIANS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_PHYSN_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT NON-CLIA PHYSICIANS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_PHYSN_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICIANS EMPLOYED BY A PROVIDER .
                PRVDR_FTE_PHYSN_VLNTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT VOLUNTEER PHYSICIANS IN A HOSPICE .
                PRVDR_FTE_PHYSNEXT_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICIAN EXTENDERS - (NURSE PRACTITIONERS (NPS), PHYSICIAN ASSISTANTS (PAS), OR CLINICAL NURSE SPECIALISTS (CNSS)) - UNDER CONTRACT TO THE FACILITY .
                PRVDR_FTE_PHYSNEXT_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICIAN EXTENDERS - (NURSE PRACTITIONERS (NPS), PHYSICIAN ASSISTANTS (PAS), OR CLINICAL NURSE SPECIALISTS (CNSS)) -EMPLOYED BY THE FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_PHYSNEXT_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICIAN EXTENDERS - (NURSE PRACTITIONERS (NPS), PHYSICIAN ASSISTANTS (PAS), OR CLINICAL NURSE SPECIALISTS (CNSS)) -EMPLOYED BY THE FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_PROFNL_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT ACTIVITY PROFESSIONALS UNDER CONTRACT TO A FACILITY.
                PRVDR_FTE_PROFNL_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT ACTIVITY PROFESSIONALS EMPLOYED FULL-TIME BY A FACILITY.
                PRVDR_FTE_PROFNL_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT ACTIVITY PROFESSIONALS EMPLOYED PART-TIME BY A FACILITY.
                PRVDR_FTE_PT_AIDE_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPY AIDES UNDER CONTRACT TO A FACILITY.
                PRVDR_FTE_PT_AIDE_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPY AIDES EMPLOYED BY A FACILITY ON A FULL-TIME BASIS.
                PRVDR_FTE_PT_AIDE_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS.
                PRVDR_FTE_PT_ARNGMT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS EMPLOYED BY ARRANGEMENT IN AN OUTPATIENT PHYSICAL THERAPY FACILITY .
                PRVDR_FTE_PT_ASTNT_CNTRCT_CNT, -- NUMBER(7,2) | NULL | NUMBER OF CONTRACT STAFF HOURS FOR PHYSICAL THERAPY ASSISTANTS.
                PRVDR_FTE_PT_ASTNT_EMPLEE_CNT, -- NUMBER(7,2) | NULL | NUMBER OF FULL-TIME STAFF HOURS FOR PHYSICAL THERAPY ASSISTANTS.
                PRVDR_FTE_PT_ASTNT_PTP_CNT, -- NUMBER(7,2) | NULL | NUMBER OF PART-TIME STAFF HOURS FOR PHYSICAL THERAPY ASSISTANTS.
                PRVDR_FTE_PT_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_PT_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_PT_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_PT_STF_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS EMPLOYED BY AN OUTPATIENT PHYSICAL THERAPY PROVIDER OR A HOME HEALTH AGENCY PROVIDER .
                PRVDR_FTE_PT_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT PHYSICAL THERAPISTS EMPLOYED BY AN OUTPATIENT PHYSICAL THERAPY PROVIDER OR A HOME HEALTH AGENCY PROVIDER .
                PRVDR_FTE_RDLGY_TCHNCN_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT RADIOLOGY TECHNICIANS EMPLOYED BY A PROVIDER .
                PRVDR_FTE_RGSD_PHRMCST_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED PHARMACISTS EMPLOYED BY A PROVIDER .
                PRVDR_FTE_RN_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSES UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_RN_DRCTR_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSE DIRECTORS OF NURSING UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_RN_DRCTR_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSE DIRECTORS OF NURSING EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_RN_DRCTR_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSE DIRECTORS OF NURSING EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_RN_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSES EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_RN_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED NURSES EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_RN_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT REGISTERED PROFESSIONAL NURSES EMPLOYED BY A PROVIDER .
                PRVDR_FTE_RN_VLNTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT VOLUNTEER REGISTERED NURSES IN A HOSPICE .
                PRVDR_FTE_RSDNT_PHYSN_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT RESIDENTS (PHYSICIANS) EMPLOYED BY A HOSPITAL .
                PRVDR_FTE_RT_EMPLEE_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT RESPIRATORY THERAPISTS EMPLYED BY A HOSPITAL .
                PRVDR_FTE_SCL_EMPLEE_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICAL SOCIAL WORKERS EMPLOYED BY A HOSPITAL OR HOSPICE .
                PRVDR_FTE_SCL_WORKR_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SOCIAL WORKERS UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_SCL_WORKR_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SOCIAL WORKERS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_SCL_WORKR_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SOCIAL WORKERS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_SPCH_ARNGMT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SPEECH PATHOLOGISTS EMPLOYED BY ARRANGEMENT IN AN OUTPATIENT PHYSICAL THERAPY FACILITY .
                PRVDR_FTE_SPCH_AUDLGST_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SPEECH PATHOLOGISTS OR AUDIOLOGISTS EMPLOYED BY A PROVIDER .
                PRVDR_FTE_SPCH_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SPEECH PATHOLOGISTS UNDER CONTRACT TO A FACILITY .
                PRVDR_FTE_SPCH_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SPEECH PATHOLOGISTS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_FTE_SPCH_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT SPEECH PATHOLOGISTS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_FTE_SPCH_TOT_CNT, -- NUMBER(7,2) | NULL | THE TOTAL NUMBER OF FULL-TIME EQUIVALENT SPEECH PATHOLOGISTS ON STAFF AND BY ARRANGEMENT IN AN OUTPATIENT PHYSICAL THERAPY FACILITY .
                PRVDR_FTE_STF_VLNTR_CNT, -- NUMBER(8,2) | NULL | THE NUMBER OF FULL-TIME VOLUNTEERS IN A HOSPICE .
                PRVDR_FTE_TCHNCN_2_YR_SCHL_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT TECHNOLOGISTS, EMPLOYED BY A PORTABLE X-RAY PROVIDER, WHO ARE GRADUATES OF A TWO-YEAR APPROVED SCHOOL OF RADIOLOGIC TECHNOLOGY .
                PRVDR_FTE_TCHNCN_ASCT_DGR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT TECHNOLOGISST, EMPLOYED BY A PORTABLE X-RAY PROVIDER, WITH ASSOCIATE DEGREES IN RADIOLOGIC TECHNOLOGY .
                PRVDR_FTE_TCHNCN_BS_BA_DGR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT TECHNOLOGISTS, EMPLOYED BY A PORTABLE X-RAY PROVIDER, WITH BACHELOR OF SCIENCE (BS) OR BACHELOR OF ARTS (BA) DEGREES IN RADIOLOGIC TECHNOLOGY .
                PRVDR_GRTRC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW GERONTOLOGICAL SPECIALTY SERVICE IS PROVIDED IN A HOSPITAL.
                PRVDR_HHA_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW HOME HEALTH AIDE SERVICES ARE PROVIDED
                PRVDR_HHA_AIDE_TRNG_PGM_CD, -- TEXT(1) | NOT NULL | A CODE TO IDENTIFY HOW THE AGENCY PROVIDES HOME HEALTH AIDE TRAINING AND COMPETENCY EVALUATION PROGRAMS.
                PRVDR_HMMKR_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW HOMEMAKER SERVICES ARE PROVIDED BY A HOSPICE.
                PRVDR_HMDYLS_STN_CNT, -- NUMBER(7,2) | NULL | THE TOTAL NUMBER OF HEMODIALYSIS STATIONS IN AN END STAGE RENAL DISEASE (ESRD) FACILITY.
                PRVDR_HOSP_BSD_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE FACILITY IS CONSIDERED PART OF A HOSPITAL.
                PRVDR_HSEKPNG_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER HOUSEKEEPING SERVICES ARE PROVIDED OFFSITE TO NONRESIDENTS.
                PRVDR_HSEKPNG_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER HOUSEKEEPING SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_HSEKPNG_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER HOUSEKEEPING SERVICES ARE PROVIDED OFFSITE TO NONRESIDENTS.
                PRVDR_ICU_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SERVICES ARE PROVIDED TO THE INTENSIVE CARE UNIT.
                PRVDR_ICFMR_BED_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF CERTIFIED BEDS IN AN INTERMEDIATE CARE FACILITY (ICF) FOR THE MENTALLY RETARDED.
                PRVDR_INTRN_RSDNT_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW INTERN AND RESIDENT SERVICES ARE PROVIDED BY A HOME HEALTH AGENCY.
                PRVDR_IP_SRGCL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW INPATIENT SURGICAL SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_LAB_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW LABORATORY SERVICES ARE PROVIDED.
                PRVDR_IS_A_SBUNIT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE AGENCY IS A SUBUNIT OF ANOTHER AGENCY.
                PRVDR_LIFE_SFTY_CD_WVR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A WAIVER OF ANY LIFE SAFETY CODE (LSC) PROVISIONS HAS BEEN RECOMMENDED FOR A PROVIDER.
                PRVDR_LTC_AGRMT_BGN_DT, -- DATE | NULL | THE BEGINNING DATE OF A CERTIFIED LONG TERM CARE (LTC) FACILITYS TIME-LIMITED AGREEMENT.
                PRVDR_LTC_AGRMT_END_DT, -- DATE | NOT NULL | THE ENDING DATE OF A CERTIFIED LONG TERM CARE FACILITYS (LTC) TIME-LIMITED AGREEMENT.
                PRVDR_LTC_AGRMT_EXTNSN_END_DT, -- DATE | NULL | THE LAST DATE OF AN EXTENSION OF A CERTIFIED LONG TERM CARE FACILITYS (LTC) TIME-LIMITED AGREEMENT.
                PRVDR_LTC_AGRMT_PRIOR_END_DT, -- DATE | NOT NULL | THE LAST DATE OF A CERTIFIED LONG TERM CARE FACILITYS TIME-LIMITED AGREEMENT FOR A PRIOR SURVEY.
                PRVDR_LTC_PRIOR_EXTNSN_END_DT, -- DATE | NOT NULL | THE LAST DATE OF AN EXTENSION OF A CERTIFIED LONG TERM CARE FACILITYS TIME-LIMITED AGREEMENT FOR A PRIOR SURVEY.
                PRVDR_MDCD_CRTFD_SNF_BED_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF MEDICAID CERTIFIED NURSING FACILITY BEDS IN A FACILITY.
                PRVDR_MDCD_MDCR_PRTCPTG_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A PROVIDER IS PARTICIPATING IN THE MEDICAID OR MEDICARE PROGRAM.
                PRVDR_MDCL_DRCTR_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICAL DIRECTORS UNDER CONTRACT TO A FACILITY .
                PRVDR_MDCL_DRCTR_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICAL DIRECTORS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_MDCL_DRCTR_FTE_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICAL DIRECTORS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_MDCL_SCL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE S HOW MEDICAL SOCIAL SERVICES ARE PROVIDED.
                PRVDR_MDCL_SCHL_AFLTN_TYPE_CD, -- TEXT(1) | NOT NULL | A CODE TO IDENTIFY THE TYPE OF AFFILIATION THAT A HOSPITAL MAY HAVE WITH A MEDICAL SCHOOL.
                PRVDR_MDCL_SUPLY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW MEDICAL SUPPLY SERVICES ARE PROVIDED BY A HOSPICE.
                PRVDR_MDCR_CRTFD_SNF_BED_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF MEDICARE-CERTIFIED SNF (SKILLED NURSING FACILITY) BEDS IN A FACILITY.
                PRVDR_MDCR_MDCD_PGM_PRTCPTN_CD, -- TEXT(1) | NULL | A CODE TO INDICATE IF THE PROVIDER PARTICIPATES IN MEDICARE, MEDICAID, OR BOTH PROGRAMS.
                PRVDR_MDCR_HOSPC_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE HOME HEALTH AGENCY ALSO PARTICIPATES IN THE MEDICARE PROGRAM AS A HOSPICE.
                PRVDR_MDCR_NPP_TYPE_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE THE FEDERAL STATUS OF A HOSPITAL THAT DOESNT PARTICIPATE IN THE MEDICARE PROGRAM (NON-PARTICIPATING HOSPITAL).
                PRVDR_MDCR_TRNSPLNT_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW MEDICARE TRANSPLANT CENTER SERVICE IS PROVIDED BY A HOSPITAL.
                PRVDR_MDCR_MDCD_SNF_BED_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS CERTIFIED FOR BOTH MEDICARE AND MEDICAID SKILLED NURSING CARE IN A LONG TERM CARE FACILITY.
                PRVDR_MDCTN_AIDE_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICATION AIDES/TECHNICIANS UNDER CONTRACT TO A FACILITY.
                PRVDR_MDCTN_AIDE_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICATION AIDES/TECHNICIANS EMPLOYED BY A FACILITY ON A FULL-TIME BASIS .
                PRVDR_MDCTN_AIDE_FTE_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT MEDICATION AIDES/TECHNICIANS EMPLOYED BY A FACILITY ON A PART-TIME BASIS .
                PRVDR_MH_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER MENTAL HEALTH SERVICES ARE PROVIDED OFF-SITE TO RESIDENTS.
                PRVDR_MH_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER MENTAL HEALTH SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_MH_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER MENTAL HEALTH SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_MLT_FAC_ORG_OWND_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A FACILITY IS OWNED BY AN ORGANIZATION THAT OWNS (OR LEASES) TWO OR MORE NURSING FACILITIES.
                PRVDR_MRI_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW MAGNETIC RESONANCE IMAGING SERVICE IS PROVIDED IN A HOSPITAL.
                PRVDR_NCRY_DSGNTN_LOST_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN THE PROVIDER LOST DESIGNATION AS A NECESSARY PROVIDER.
                PRVDR_NCRY_PRVDR_DSGNTN_DT, -- DATE | NOT NULL | A DATE INDICATING WHEN THE PROVIDER WAS DESIGNATED AS A NECESSARY PROVIDER.
                PRVDR_NCRY_PRVDR_DSGNTN_SW, -- TEXT(1) | NOT NULL | A SWITCH WHICH INDICATES IF THE PROVIDER IS DESIGNATED AS A NECESSARY PROVIDER. Y = THE PROVIDER IS DESIGNATED AS A NECESSARY PROVIDER. N = THE PROVIDER IS DESIGNATED AS NOT BEING A NECESSARY PROVIDER. ~ = DEFAULT VALUE
                PRVDR_NEONTL_ICU_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NEONATAL ICU SERVICE IS PROVIDED IN A HOSPITAL.
                PRVDR_NEONTL_NRSRY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NEONATAL NURSERY SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_NON_SPECF_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OTHER (NON-SPECIFIED) SERVICES ARE PROVIDED.
                PRVDR_MLT_FAC_ORG_OWNR_NAME, -- TEXT(38) | NULL | THE NAME OF THE MULTI-FACILITY ORGANIZATION THAT OWNS THE FACILITY.
                PRVDR_NRSNG_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHERE NURSING SERVICES ARE PROVIDED OFFSITE TO NONRESIDENTS.
                PRVDR_NRSNG_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER NURSING SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_NRSNG_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NURSING SERVICE IS PROVIDED.
                PRVDR_NRSNG_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NURSING SERVICE IS PROVIDED.
                PRVDR_NRSNG_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NURSING SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_NTRTNL_GDNC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NUTRITIONAL GUIDANCE SERVICES ARE PROVIDED.
                PRVDR_NUCLR_MDCN_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NUCLEAR MEDICINE SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_OB_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OBSTETRICS SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_NRSNG_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER NURSING SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_OP_PT_SPCH_THRPY_MDCR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY ALSO PARTICIPATES IN MEDICARE AS A PROVIDER OF OUTPATIENT PHYSICAL THERAPY AND/OR SPEECH PATHOLOGY.
                PRVDR_OP_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OUTPATIENT SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_OPTMTRC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OPTOMETRIC SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_OP_PT_SPCH_THRPY_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A HOME HEALTH AGENCY IS QUALIFIED TO PROVIDE OUTPATIENT PHYSICAL THERAPY/SPEECH SERVICES.
                PRVDR_OR_SRVC_CD, -- TEXT(1) | NOT NULL | AN INDICATOR OF HOW OPERATING ROOM SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_ORGN_TRNSPLNT_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INIDICATE HOW ORGAN TRANSPLANT SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_OR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF OPERATING ROOMS IN AN AMBULATORY SURGICAL CENTER.
                PRVDR_ORGNZD_FMLY_MMBR_GRP_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE FACILITY HAS AN ORGANIZED GROUP OF FAMILY MEMBERS OF RESIDENTS.
                PRVDR_ORTHTC_PRSTHTC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW ORTHOTIC PROSTHETIC SERVICE IS PROVIDED BY A COMPREHENSIVE OUTPATIENT REHAB FACILITY.
                PRVDR_ORTHTC_PRSTHTC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW ORTHOTIC PROSTHETIC SERVICE IS PROVIDED BY A COMPREHENSIVE OUTPATIENT REHAB FACILITY.
                PRVDR_ORTHTC_PRSTHTC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW ORTHOTIC/PROSTHETIC SERVICES ARE PROVIDED BY A COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY.
                PRVDR_ORGNZD_RSDNT_GRP_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE FACILITY HAS AN ORGANIZED RESIDENTS GROUP.
                PRVDR_OT_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OCCUPATIONAL THERAPY SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_OT_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OCCUPATIONAL THERAPY SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_OT_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OCCUPATIONAL THERAPY SERVICE IS PROVIDED BY A COMPREHENSIVE OUTPATIENT REHAB FACILITY.
                PRVDR_OT_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OCCUPATIONAL THERAPY SERVICE IS PROVIDED BY A COMPREHENSIVE OUTPATIENT REHAB FACILITY.
                PRVDR_OT_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OCCUPATIONAL THERAPY SERVICES ARE PROVIDED.
                PRVDR_OT_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OCCUPATIONAL THERAPY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_OTHR_CNTRCT_HRS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF CONTRACT STAFF HOURS FOR NON-CLIA ACTIVITIES.
                PRVDR_OTHR_FTE_HRS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME STAFF HOURS FOR OTHER ACTIVITIES.
                PRVDR_OTHR_FTE_PTP_HRS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF PART-TIME STAFF HOURS PROVIDED BY OTHER ACTIVITY STAFF.
                PRVDR_OTHR_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OTHER ACTIVITY SERVICES ARE PROVIDED BY STAFF OFF-SITE TO RESIDENTS.
                PRVDR_OTHR_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OTHER ACTIVITY SERVICES ARE PROVIDED BY STAFF OFF-SITE TO NONRESIDENTS.
                PRVDR_OTHR_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OTHER ACTIVITY SERVICES ARE PROVIDED BY STAFF ON-SITE TO NONRESIDENTS.
                PRVDR_OTHR_PRSNEL_TOT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME EQUIVALENT OTHER SALARIED PERSONNEL EMPLOYED BY A FACILITY .
                PRVDR_PDTRY_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PODIATRY SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_PDTRY_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PODIATRY SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_PED_ICU_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PEDIATRIC ICU SERVICE IS PROVIDED IN HOSPITAL.
                PRVDR_PED_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PEDIATRIC SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_PET_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW POSITRON EMISSIONS TOMOGRAPHY (PET) SCANNER SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_PDTRY_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PODIATRY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_PHRMCY_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHARMACY SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_PHRMCY_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHARMACY SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_PHRMCY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PHARMACY SERVICES ARE PROVIDED.
                PRVDR_PHRMCY_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHARMACY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_PHYSN_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICIAN SERVICES ARE PROVIDED OFF-SITE TO RESIDENTS.
                PRVDR_PHYSN_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICIAN SERVICES ARE PROVIDED ON-SITE TO NONRESIDENTS.
                PRVDR_PHYSN_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PHYSICIAN SERVICE IS PROVIDED BY A COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY (CORF).
                PRVDR_PHYSN_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PHYSICIAN SERVICE IS PROVIDED BY A COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY (CORF).
                PRVDR_PHYSN_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PHYSICIAN SERVICES ARE PROVIDED.
                PRVDR_PHYSN_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICIAN SERVICES ARE PROVIDED ON-SITE TO RESIDENTS.
                PRVDR_PHYSNEXT_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICIAN EXTENDER SERVICES - (NURSE PRACTITIONERS (NPS), PHYSICIAN ASSISTANTS (PAS), OR CLINICAL NURSE SPECIALISTS (CNSS)) -ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_PHYSNEXT_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICIAN EXTENDER SERVICES - (NURSE PRACTITIONERS (NPS), PHYSICIAN ASSISTANTS (PAS), OR CLINICAL NURSE SPECIALISTS (CNSS)) -ARE PROVIDED ONSITE TO NON-RESIDENTS.
                PRVDR_PRIOR_SUSPNSN_BGN_DT, -- DATE | NOT NULL | THE EFFECTIVE DATE OF A PREVIOUS SUSPENSION OF ADMISSIONS TO A LONG TERM CARE (LTC) FACILITY.
                PRVDR_PRIOR_SUSPNSN_END_DT, -- DATE | NOT NULL | THE PRIOR RESCIND DATE OF THE SUSPENSION OF PAYMENTS FOR NEW ADMISSIONS TO A LONG TERM CARE (LTC) FACILITY.
                PRVDR_PSTOPRTV_RCVRY_ROOM_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW POSTOPERATIVE RECOVERY ROOM SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_PSYCH_ADLT_IP_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PSYCHIATRIC SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_PSYCH_EMER_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW EMERGENCY PSYCHIATRIC SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_PSYCH_FRNSC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW FORENSIC PSYCHIATRIC SERVICE IS PROVIDED BY A HOSPITAL.
                PRVDR_PSYCH_GRTRC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW GERIATRIC PSYCHIATRIC SERVICE IS PROVIDED BY A HOSPITAL.
                PRVDR_PSYCH_OP_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OUTPATIENT PSYCHIATRIC SERVICE IS PROVIDED IN A HOSPITAL.
                PRVDR_PHYSNEXT_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICIAN EXTENDER SERVICES - (NURSE PRACTITIONERS (NPS), PHYSICIAN ASSISTANTS (PAS), OR CLINICAL NURSE SPECIALISTS (CNSS)) -ARE PROVIDED ON-SITE TO RESIDENTS.
                PRVDR_PSYCH_UNIT_BED_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A PPS-EXEMPT (PROSPECTIVE PAYMENT SYSTEM) PSYCHIATRIC UNIT OF A HOSPITAL.
                PRVDR_PSYCH_UNIT_EXMPT_END_DT, -- DATE | NOT NULL | THE DATE THAT A PSYCHIATRIC UNIT IS NO LONGER EXEMPT FROM THE PROSPECTIVE PAYMENT SYSTEM (PPS).
                PRVDR_PSYCH_UNIT_PPS_EXMPT_DT, -- DATE | NULL | THE DATE A PSYCHIATRIC UNIT BECAME EXEMPT FROM THE PROSPECTIVE PAYMENT SYSTEM (PPS).
                PRVDR_PSYCH_UNIT_TRMNTN_CD, -- TEXT(2) | NOT NULL | A CODE TO INDICATE THE REASON THAT A PSYCHIATRIC UNIT IS NO LONGER EXEMPT FROM PPS (PROSPECTIVE PAYMENT SYSTEM).
                PRVDR_PSYCH_UNIT_PPS_EXMPT_SW, -- TEXT(1) | NULL | INDICATES IF A HOSPITAL HAS A PPS-EXEMPT (PROSPECTIVE PAYMENT SYSTEM) PSYCHIATRIC UNIT.
                PRVDR_PT_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICAL THERAPY SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_PT_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICAL THERAPY SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_PT_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PHYSICAL THERAPY SERVICES ARE PROVIDED.
                PRVDR_PT_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PHYSICAL THERAPY SERVICES ARE PROVIDED.
                PRVDR_PT_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PHYSICAL THERAPY SERVICES ARE PROVIDED.
                PRVDR_PT_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PHYSICAL THERAPY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_PYSCHLGCL_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PSYCHOLOGICAL SERVICES ARE PROVIDED.
                PRVDR_PYSCHLGCL_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PSYCHOLOGICAL SERVICES ARE PROVIDED.
                PRVDR_PYSCHLGCL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW PSYCHOLOGICAL SERVICES ARE PROVIDED.
                PRVDR_PTNT_ROOM_SIZE_WVR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A WAIVER OF PATIENT ROOM SIZE HAS BEEN RECOMMENDED FOR A FACILITY.
                PRVDR_RCRTNL_HRS_CNTRCT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF CONTRACT STAFF HOURS PROVIDED BY THERAPEUTIC RECREATION SPECIALISTS.
                PRVDR_RCRTNL_HRS_EMPLEE_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME STAFF HOURS PROVIDED BY THERAPEUTIC RECREATION SPECIALISTS.
                PRVDR_RCRTNL_HRS_PTP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF PART-TIME STAFF HOURS PROVIDED BY THERAPEUTIC RECREATION SPECIALISTS.
                PRVDR_RCRTNL_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THERAPEUTIC RECREATION SPECIALIST SERVICES ARE PROVIDED OFF-SITE TO RESIDENTS.
                PRVDR_RCRTNL_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THERAPEUTIC RECREATION SPECIALIST SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_RDLGY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW RADIOLOGY SERVICES ARE PROVIDED.
                PRVDR_REHAB_OP_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OUTPATIENT REHABILITATION SERVICE IS PROVIDED IN A HOSPITAL.
                PRVDR_RCRTNL_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THERAPEUTIC RECREATION SPECIALIST SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_REHAB_UNIT_BED_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A PPS-EXEMPT REHABILITATION UNIT OF A HOSPITAL.
                PRVDR_REHAB_UNIT_EXMPT_END_DT, -- DATE | NOT NULL | THE DATETHAT THE HOSPITALS PSYCHIATRIC UNIT IS NO LONGER EXCLUDED FROM PROSPECTIVE PAYMENT SYSTEM (PPS).
                PRVDR_REHAB_UNIT_PPS_EXMPT_DT, -- DATE | NULL | THE DATE A REHABILITATION UNIT BECAME EXEMPT FROM THE PROSPECTIVE PAYMENT SYSTEM (PPS).
                PRVDR_REHAB_UNIT_TRMNTN_CD, -- TEXT(2) | NOT NULL | THIS ELEMENT INDICATES THE REASON FOR A HOSPITAL REHABILITATION UNITS TERMINATION OF ITS EXCLUSION STATUS UNDER PROSPECTIVE PAYMENT SYSTEM (PPS).
                PRVDR_REHAB_UNIT_PPS_EXMPT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A HOSPITAL HAS A PPS-EXEMPT REHABILITATION UNIT (PROSPECTIVE PAYMENT SYSTEM).
                PRVDR_RHC_PGM_NAME, -- TEXT(26) | NULL | THE NAME OF A FEDERAL PROGRAM THAT PROVIDES SUPPORT TO A RURAL HEALTH CLINIC TO PROVIDE SERVICES IN A MEDICALLY UNDERSERVED AREA OR AN AREA WITH A SHORTAGE OF PRIMARY CARE HEALTH MANPOWER.
                PRVDR_RN_24_HR_WVR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A WAIVER OF THE 24-HOUR REGISTERED NURSE REQUIREMENT HAS BEEN RECOMMENDED FOR A FACILITY.
                PRVDR_RN_7_DAY_WVR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A WAIVER OF THE 7-DAY REGISTERED NURSE REQUIREMENTS HAS BEEN RECOMMENDED FOR A SKILLED NURSING FACILITY (SNF) OR NURSING FACILITY (NF).
                PRVDR_RO_OVRRD_NRS_TO_BED_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE REGIONAL OFFICE HAS TO APPROVE A PENDING RECORD (PERTAINING TO NURSE TO BED DATA) IN THE DATA ENTRY SYSTEM .
                PRVDR_RO_OVRRD_BED_CNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE REGIONAL OFFICE HAS TO APPROVE A PENDING RECORD (PERTAINING TO THE NUMBER OF BEDS IN A FACILITY) IN THE DATA ENTRY SYSTEM .
                PRVDR_RO_OVRRD_STF_CNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE REGIONAL OFFICE HAS TO APPROVE A PENDING RECORD(PERTAINING TO STAFFING DATA) IN THE DATA ENTRY SYSTEM .
                PRVDR_RSDNT_PGM_APRVD_ADA_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE RESIDENT PROGRAM AT A HOSPITAL IS APPROVED BY THE AMERICAN DENTAL ASSOCIATION (ADA).
                PRVDR_RSDNT_PGM_APRVD_AMA_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE RESIDENT PROGRAM AT A HOSPITAL IS APPROVED BY THE AMERICAN MEDICAL ASSOCIATION (AMA).
                PRVDR_RSDNT_PGM_APRVD_AOA_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE RESIDENT PROGRAM AT A HOSPITAL IS APPROVED BY THE AMERICAN OSTEOPATHIC ASSOCIATION (AOA).
                PRVDR_RSPRTRY_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW RESPIRATORY CARE SERVICE IS PROVIDED.
                PRVDR_RSPRTRY_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW RESPIRATORY CARE SERVICE IS PROVIDED.
                PRVDR_RSPRTRY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW RESPIRATORY CARE SERVICES ARE PROVIDED.
                PRVDR_SB_SIZE_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE THE SIZE OF A HOSPITAL PROVIDING SWING BED SERVICES (BEDS CAN BE USED FOR EITHER HOSPITAL OR LONG TERM CARE SERVICES).
                PRVDR_RSDNT_PGM_APRVD_OTHR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE RESIDENT PROGRAM AT A HOSPITAL IS APPROVED BY NON-CLIA PROFESSIONAL ORGANIZATIONS.
                PRVDR_SB_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A HOSPITAL PROVIDES SWING BED SERVICES -BEDS CAN BE USED FOR EITHER HOSPITAL OR LONG TERM CARE SERVICES.
                PRVDR_SBUNIT_OPRTN_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF SUBUNITS OPERATED BY THE AGENCY.
                PRVDR_SCL_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW RESPIRATORY CARE SERVICE IS PROVIDED.
                PRVDR_SCL_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW RESPIRATORY CARE SERVICE IS PROVIDED.
                PRVDR_SCL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SOCIAL SERVICES ARE PROVIDED.
                PRVDR_SBUNIT_OPRTN_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THE AGENCY OPERATES ANY SUBUNITS.
                PRVDR_SCL_SRVC_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER SERVICES ARE PROVIDED BY OTHER SOCIAL SERVICES STAFF OFFSITE TO RESIDENTS.
                PRVDR_SCL_SRVCS_CNTRCT_HRS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF CONTRACT STAFF HOURS PROVIDED BY NON-CLIA SOCIAL SERVICES STAFF.
                PRVDR_SCL_SRVCS_FLTM_HRS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF FULL-TIME STAFF HOURS PROVIDED BY NON-CLIA SOCIAL SERVICES STAFF.
                PRVDR_SCL_SRVCS_PTP_HRS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF PART-TIME STAFF HOURS PROVIDED BY NON-CLIA SOCIAL SERVICES STAFF.
                PRVDR_SCL_WORK_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHERF SOCIAL WORK SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_SHCK_TRMA_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW SHOCK TRAUMA SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_SCOPE_OF_SRVC_WVR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A WAIVER OF THE SCOPE OF SERVICES REQUIREMENT HAS BEEN RECOMMENDED FOR A HOSPITAL.
                PRVDR_SPCH_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER SPEECH/LANGUAGE PATHOLOGY SERVICES ARE PROVIDED OFFSITE TO RESIDENTS.
                PRVDR_SPCH_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER SPEECH/LANGUAGE PATHOLOGY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_SPCH_PTHLGST_SRVC_2_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SPEECH PATHOLOGY SERVICE IS PROVIDED.
                PRVDR_SPCH_PTHLGST_SRVC_3_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SPEECH PATHOLOGY SERVICE IS PROVIDED.
                PRVDR_SPCH_PTHLGST_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SPEECH PATHOLOGY SERVICES ARE PROVIDED.
                PRVDR_SPCH_THRPY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SPEECH THERAPY SERVICES ARE PROVIDED.
                PRVDR_SPCH_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER SPEECH/LANGUAGE PATHOLOGY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_SPCL_BED_ALZHMR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILITY FOR RESIDENTS WITH ALZHEIMERS DISEASE.
                PRVDR_SPCL_BED_DSBLD_CHLD_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILITY FOR DISABLED CHILDREN.
                PRVDR_SPCL_BED_HEAD_TRMA_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILTY FOR RESIDENTS WITH HEAD TRAUMA.
                PRVDR_SPCL_BED_SPCL_REHAB_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS WITH SPECIALIZED REHAB NEEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILITY FOR RESIDENTS .
                PRVDR_SPCL_BED_VNTLTR_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILITY FOR RESIDENTS WITH VENTILATOR/RESIPIRATORY CARE NEEDS.
                PRVDR_SPCL_CARE_BED_AIDS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILITY FOR RESIDENTS WITH AIDS.
                PRVDR_SPCL_CARE_BED_DLYS_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILITY FOR RESIDENTS NEEDING DIALYSIS.
                PRVDR_SPCL_CARE_BED_HD_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY THE FACILITY FOR RESIDENTS WITH HUNTINGTONS DISEASE.
                PRVDR_SRGCL_CRDC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OPEN HEART SURGERY FACILITY SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_SRGCL_ICU_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SURGICAL ICU SERVICES ARE PROVIDED IN A HOSPITAL.
                PRVDR_SRGCL_NRLGCL_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW NEUROSURGICAL SERVICES ARE PROVIDED IN A HOSPITA.
                PRVDR_SRGCL_OP_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OUTPATIENT SURGERY UNIT SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_SRGCL_OPTHMLGY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW OPHTHALMIC SURGERY SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_SRGCL_ORTHO_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW ORTHOPEDIC SURGERY SERVICE IS PROVIDED IN A HOSPITAL.
                PRVDR_SRGCL_RCNSTRV_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW RECONSTRUCTION SURGERY SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_SPCL_CARE_BED_HOSP_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF BEDS IN A UNIT IDENTIFIED AND DEDICATED BY A FACILITY FOR RESIDENTS NEEDING HOSPICE SERVICES.
                PRVDR_SRGRY_CRDVSCLR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER CARDIOVASCULAR SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER (ASC).
                PRVDR_SRGRY_FT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER FOOT SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_GNRL_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER GENERAL SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_NRLGCL_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER NEUROLOGICAL SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_OB_GYN_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OBSTETRICS/GYNECOLOGY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_OPTHMLGY_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OPTHAMOLOGY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_ORAL_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ORAL SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_ORTHO_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER ORTHOPEDIC SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_OTLNGY_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER OTOLARYNGOLOGY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_PLSTC_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER PLASTIC SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_THORC_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THORACIC SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRGRY_URLGY_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER UROLOGY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_SRTY_BOND_STUS_IND, -- TEXT(1) | NULL | AN INDICATION OF WHETHER OR NOT THE PROVIDER HAS A SURETY BOND OR IF THE BOND REQUIREMENT HAS BEEN WAIVED. A SURETY BOND IS A CONTRACT AMONG AT LEAST THREE PARTIES: THE OBLIGEE - THE PARTY WHO IS THE RECIPIENT OF AN OBLIGATION, THE PRINCIPAL - THE PRIMARY PARTY WHO WILL BE PERFORMING THE CONTRACTUAL OBLIGATION, THE SURETY - WHO ASSURES THE OBLIGEE THAT THE PRINCIPAL CAN PERFORM THE TASK
                PRVDR_SRVC_BGN_DT, -- DATE | NULL | THE SUPPLIER ACCREDITATION DATE
                PRVDR_SRVC_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER SERVICES ARE PROVIDED BY OTHER SOCIAL SERVICES STAFF ONSITE TO NONRESIDENTS.
                PRVDR_SRVC_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER SERVICES ARE PROVIDED BY OTHER SOCIAL SERVICES STAFF ONSITE TO RESIDENTS.
                PRVDR_SRVY_ACRDTD_HOSP_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THIS PROVIDER WAS AN ACCREDITED HOSPITAL ANYTIME DURING THE CURRENT SURVEY.
                PRVDR_SRVY_NACRDTD_HOSP_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THIS PROVIDER WAS A NON-ACCREDITED HOSPITAL ANYTIME DURING THE CURRENT SURVEY.
                PRVDR_SS_IP_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW SHORT TERM INPATIENT CARE SERVICES ARE PROVIDED BY A HOSPICE.
                PRVDR_SRVY_SB_HOSP_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER THIS PROVIDER WAS A SWING BED HOSPITAL ANYTIME DURING THE CURRENT SURVEY.
                PRVDR_THRPTC_RDLGY_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW THERAPEUTIC RADIOLOGY SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_TCHNCL_PRSNL_WVR_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER A WAIVER OF THE TECHNICAL PERSONNEL REQUIREMENT HAS BEEN RECOMMENDED FOR A HOSPITAL.
                PRVDR_TOT_BED_CNT, -- NUMBER(7,2) | NULL | THE TOTAL NUMBER OF BEDS IN A FACILITY, INCLUDING THOSE IN NON-PARTICIPATING OR NON-LICENSED AREAS.
                PRVDR_URGNT_CARE_CNTR_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW URGENT CARE CENTER SERVICES ARE PROVIDED BY A HOSPITAL.
                PRVDR_VCTNL_GDNC_SRVC_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE HOW VOCATIONAL GUIDANCE SERVICES ARE PROVIDED.
                PRVDR_TUE_4TH_SHIFT_PTNT_CNT, -- NUMBER(7,2) | NULL | THE NUMBER OF PATIENTS ON THE TUESDAY, FOURTH SHIFT. THE FOURTH SHIFT MAY REFER TO THE 48-HOUR SHIFTS THAT SOME INDUSTRIES UTILIZE. IN THIS ARRANGEMENT, TWO SHIFTS OF WORKERS WORK ALTERNATING 12 HOUR WORKDAYS FOR 48 HOURS. AFTER THIS, A THIRD AND FOURTH SHIFT TAKE OVER FOR ANOTHER 48 HOURS.
                PRVDR_VCTNL_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER VOCATIONAL SERVICES ARE PROVIDED OFF-SITE TO RESIDENTS.
                PRVDR_VCTNL_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER VOCATIONAL SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_VCTNL_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER VOCATIONAL SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_WORK_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHERF SOCIAL WORK SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_WORK_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHERF SOCIAL WORK SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                PRVDR_XRAY_OFSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DIAGNOSTIC X-RAY SERVICES ARE PROVIDED OFF-SITE TO RESIDENTS.
                PRVDR_XRAY_ONSTE_NRSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DIAGNOSTIC X-RAY SERVICES ARE PROVIDED ONSITE TO NONRESIDENTS.
                PRVDR_XRAY_ONSTE_RSDNT_SW, -- TEXT(1) | NULL | AN INDICATOR OF WHETHER DIAGNOSTIC X-RAY SERVICES ARE PROVIDED ONSITE TO RESIDENTS.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_FREE_STNDG_SW, -- TEXT(1) | NULL | INDICATES IF THE AMBULATORY SURGICAL CENTER IS FREESTANDING.
                PRVDR_CLIA_ID_1_NUM, -- TEXT(10) | NULL | NUMBER ASSIGNED TO A HOSPITAL LABORATORY LICENSED IN ACCORDANCE WITH THE CLINICAL LABORATORY IMPROVEMENT ACT (CLIA) - 1ST OCCURRENCE.
                PRVDR_CLIA_ID_2_NUM, -- TEXT(10) | NULL | NUMBER ASSIGNED TO A HOSPITAL LABORATORY LICENSED IN ACCORDANCE WITH THE CLINICAL LABORATORY IMPROVEMENT ACT (CLIA) - 2ND OCCURRENCE.
                PRVDR_CLIA_ID_3_NUM, -- TEXT(10) | NULL | NUMBER ASSIGNED TO A HOSPITAL LABORATORY LICENSED IN ACCORDANCE WITH THE CLINICAL LABORATORY IMPROVEMENT ACT (CLIA) - 3RD OCCURRENCE.
                PRVDR_CLIA_ID_4_NUM, -- TEXT(10) | NULL | NUMBER ASSIGNED TO A HOSPITAL LABORATORY LICENSED IN ACCORDANCE WITH THE CLINICAL LABORATORY IMPROVEMENT ACT (CLIA) - 4TH OCCURRENCE.
                PRVDR_CLIA_ID_5_NUM, -- TEXT(10) | NULL | NUMBER ASSIGNED TO A HOSPITAL LABORATORY LICENSED IN ACCORDANCE WITH THE CLINICAL LABORATORY IMPROVEMENT ACT (CLIA) - 5TH OCCURRENCE.
                PRVDR_LTC_XREF_PRVDR_NUM, -- TEXT(10) | NULL | A LONG TERM CARE PROVIDER NUMBER THAT WAS TERMINATED IN 1985 BECAUSE OF POLICY CHANGES WHICH STATES THAT SKILLED NURSING FACILITY (SNF)/INTERMEDIATE CARE FACILITY (ICF) DISTINCT PARTS OR DUALLY CERTIFIED PORTIONS ARE ASSIGNED A SINGLE SNF PROVIDER NUMBER.
                PRVDR_MDCR_HOSPC_PRVDR_NUM, -- TEXT(10) | NULL | IF THE AGENCY ALSO PARTICIPATES IN THE MEDICARE PROGRAM AS A HOSPICE, THE HOSPICE PROVIDER NUMBER.
                PRVDR_MDCR_MDCD_PRVDR_NUM, -- TEXT(10) | NULL | IF THE AGENCY IS BASED IN ANOTHER MEDICARE OR MEDICAID FACILITY, THE PROVIDER NUMBER OF THAT FACILITY.
                PRVDR_MDCR_PRNT_PRVDR_NUM, -- TEXT(10) | NULL | THE IDENTIFICATION NUMBER OF THE PARENT PROVIDER WHEN A PROVIDER IS PART OF AN EXISTING MEDICARE PROVIDER.
                PRVDR_CS_SW, -- TEXT(1) | NULL | A SWITCH TO INDICATE IF A PROVIDER IS A CHRISTIAN SCIENCE FACILITY
                PRVDR_AMBLNC_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW AMBULANCE SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_BLOOD_BANK_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW BLOOD BANK SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_HH_AIDE_HMMKR_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW HOME HEALTH AIDE SERVICES ARE PROVIDED BY A HOME HEALTH AGENCY.
                PRVDR_HOSP_HH_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW HOME HEALTH SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_HOSP_HOSPC_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW HOSPICE SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_ANTMCL_LAB_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW ANATOMICAL LABORATORY SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_LTC_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW LONG TERM CARE SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_ORGN_BANK_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW ORGAN BANK SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_IP_REHAB_SRVC_CD, -- TEXT(1) | NULL | A CODE TO INDICATE HOW INPATIENT REHABILITATION SERVICES ARE PROVIDED BY A HOSPITAL
                PRVDR_AFLTD_PRVDR_CNT, -- NUMBER(2) | NOT NULL | NUMBER OFPROVIDERS AFFLIATED WITH THE PROVIDER OF SERVICE NON CLINICAL LABORATORY.
                PRVDR_CAH_EXCLDD_PSYCH_UNIT_SW, -- TEXT(1) | NOT NULL | INDICATES IF A CRITICAL ACCESS HOSPITAL HAS A PSYCHIATRIC PROSPECTIVE PAYMENT SYSTEM-EXCLUDED DISTINCT PART UNIT.
                PRVDR_CAH_EXCLDD_REHAB_UNIT_SW, -- TEXT(1) | NOT NULL | INDICATES IF A CRITICAL ACCESS HOSPITAL REHABILITATION UNIT HAS A PROSPECTIVE PAYMENT SYSTEM-EXCLUDED DISTINCT PART UNIT.
                PRVDR_CAH_APRVD_SW, -- TEXT(1) | NOT NULL | INDICATES IF A CRITICAL ACCESS HOSPITAL HAS BEEN APPROVED TO PROVIDE NURSING HOME AND/OR HOSPITAL SERVICES.
                PRVDR_COLOCD_STUS_SW, -- TEXT(1) | NOT NULL | INDICATES IF THE FACILITY SHARES A LOCATION WITH ANOTHER HOSPITAL.
                PRVDR_CRDC_CTHRTZTN_ROOM_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF CARDIAC CATHETERIZATION PROCEDURE ROOMS.
                PRVDR_DNTL_SRGRY_SW, -- TEXT(1) | NOT NULL | INDICATES IF DENTAL SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_ENDSCPY_PRCDR_ROOM_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF ENDOSCOPY PROCEDURE ROOMS.
                PRVDR_ENDSCPY_SRGRY_SW, -- TEXT(1) | NOT NULL | INDICATES IF ENDOSCOPY SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_HOSPC_AIDE_EMPLEE_CNT, -- NUMBER(5) | NOT NULL | NUMBER OF FULL-TIME EQUIVALENT AIDES EMPLOYED BY THE HOSPICE.
                PRVDR_HMDYLS_SRVC_SW, -- TEXT(1) | NOT NULL | INDICATES IF HEMODIALYSIS SERVICE IS PROVIDED.
                PRVDR_HOME_TRNG_SPRT_SRVC_SW, -- TEXT(1) | NOT NULL | INDICATES IF HOME TRAINING AND SUPPORT SERVICES ONLY FOR HEMODIALYSIS AND PERITONEAL DIALYSIS ARE PROVIDED.
                PRVDR_INCNTR_NGHT_HMDYLS_SW, -- TEXT(1) | NOT NULL | INDICATES IF IN-CENTER NOCTURNAL HEMODIALYSIS SERVICES ARE PROVIDED.
                PRVDR_LAB_TCHNCN_CNT, -- NUMBER(5) | NOT NULL | NUMBER OF FULL-TIME EQUIVALENT LABORATORY TECHNICIANS EMPLOYED BY A PROVIDER.
                PRVDR_LPN_CNT, -- NUMBER(5) | NOT NULL | NUMBER OF LICENSED PRACTICAL NURSES.
                PRVDR_OFSTE_LCTN_CNT, -- NUMBER(5) | NOT NULL | NUMBER OF OFF-SITE LOCATIONS.
                PRVDR_OTHR_SRGRY_SW, -- TEXT(1) | NOT NULL | INDICATES IF OTHER SURGERY TYPES ARE PERFORMED AT AN AMBULATORY SURGICAL CENTER.
                PRVDR_PAIN_SRGRY_SW, -- TEXT(1) | NOT NULL | INDICATES IF PAIN SURGERY IS OFFERED BY AN AMBULATORY SURGICAL CENTER.
                PRVDR_PRTNL_DLYS_SRVC_SW, -- TEXT(1) | NOT NULL | INDICATES IF PERITONEAL DIALYSIS SERVICE IS PROVIDED.
                PRVDR_PRVNC_CD, -- TEXT(2) | NOT NULL | CANADIAN PROVINCE WHERE A NON-PARTICIPATING EMERGENCY HOSPITAL IS LOCATED.
                PRVDR_PED_RSDNT_PGM_SW, -- TEXT(1) | NOT NULL | INDICATES IF THE PROVIDER HAS AN AFFILIATED PODIATRIC RESIDENT PROGRAM.
                PRVDR_HMDYLS_HOME_TRNG_SPRT_SW, -- TEXT(1) | NOT NULL | INDICATES IF THE FACILITY PROVIDES HOME TRAINING AND SUPPORT FOR HEMODIALYSIS.
                PRVDR_PRTNL_DLYS_HOME_TRNG_SW, -- TEXT(1) | NOT NULL | INDICATES IF THE FACILITY PROVIDES HOME TRAINING AND SUPPORT FOR PERITONEAL DIALYSIS.
                PRVDR_FTE_TCHNCL_EMPLEE_CNT, -- NUMBER(7,2) | NOT NULL | NUMBER OF FULL-TIME EQUIVALENT TECHNICAL STAFF (WATER, MACHINE) EMPLOYED BY A FACILITY.
                PRVDR_FTE_TCHNCN_EMPLEE_CNT, -- NUMBER(7,2) | NOT NULL | NUMBER OF FULL-TIME EQUIVALENT TECHNICIANS EMPLOYED BY A FACILITY.
                PRVDR_AFLTD_AMBLNC_SRVC_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING AMBULANCE SERVICES.
                PRVDR_AFLTD_AMBLTRY_SRGRY_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING AMBULATORY SURGERY CENTERS.
                PRVDR_AFLTD_ESRD_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING END-STAGE RENAL DISEASE UNITS.
                PRVDR_AFLTD_FQHC_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING FEDERALLY QUALIFIED HEALTH CENTERS.
                PRVDR_AFLTD_HOME_HLTH_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING HOME HEALTH AGENCIES.
                PRVDR_AFLTD_HOSPC_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING HOSPICES.
                PRVDR_AFLTD_ORGN_PRCMT_ORG_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING ORGAN PROCUREMENT ORGANIZATIONS.
                PRVDR_AFLTD_PSYCH_RSDNTL_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING PSYCHIATRIC RESIDENTIAL TREATMENT FACILITIES.
                PRVDR_AFLTD_RHC_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING RURAL HEALTH CENTERS.
                PRVDR_AFLTD_SNF_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING SKILLED NURSING FACILITIES.
                PRVDR_COLOCD_HOSP_CNT, -- NUMBER(2) | NOT NULL | NUMBER OF AFFILIATED MEDICARE PARTICIPATING CO-LOCATED HOSPITALS.
                PRVDR_OFSTE_CHLDRNS_HOSP_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFFSITE SATELLITES OF A CHILDRENS HOSPITAL.
                PRVDR_OFSTE_CNCR_HOSP_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE SATELLITES OF A CANCER HOSPITAL.
                PRVDR_OFSTE_EMER_DEPT_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE EMERGENCY DEPARTMENTS.
                PRVDR_OFSTE_IP_LCTN_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF INPATIENT REMOTE LOCATIONS.
                PRVDR_OFSTE_LTC_HOSP_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE SATELLITES OF A LONG TERM CARE HOSPITAL.
                PRVDR_OFSTE_OPTHMLGY_SRGRY_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE OPHTHAMOLOGY SURGERY UNITS.
                PRVDR_OFSTE_OTHR_LCTN_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OTHER OFF-SITE LOCATIONS.
                PRVDR_OFSTE_PSYCH_HOSP_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE PSYCHIATRIC HOSPITALS.
                PRVDR_OFSTE_PSYCH_UNIT_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE PSYCHIATRIC UNITS.
                PRVDR_OFSTE_REHAB_HOSP_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE REHABILITATION HOSPITALS.
                PRVDR_OFSTE_REHAB_UNIT_CNT, -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE REHABILITATION UNITS.
                PRVDR_OFSTE_URGNT_CARE_CNT -- NUMBER(4) | NOT NULL | NUMBER OF OFF-SITE URGENT CARE CENTERS.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_NON_CLIA"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrOfSrvcNonCliaExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
