"""
==========
V2_MDCR_PRVDR_HSTRY IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HSTRY

Table Type: VIEW
Columns: 45
Source Pattern: %mdcr_prvdr%
Table Comment: A COMPILATION OF HISTORICAL PROVIDER DATA, SUCH AS NAME, ADDRESS, AND PROVIDER IDENTIFIER, FOR SERVICES RENDERED TO MEDICARE BENEFICIARIES, AND USED TO SUPPORT

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrHstryExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrHstryExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_HSTRY data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HSTRY (VIEW)
    Columns: 45
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_hstry_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_HSTRY export.
        
        Includes all 45 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_SK, -- NUMBER(18) | NOT NULL | AN IDR ASSIGNED SURROGATE KEY USED TO IDENTIFY A PARTY ENGAGED IN ACTIVITY RELATED TO CMS.
                PRVDR_HSTRY_EFCTV_DT, -- DATE | NOT NULL | A DATE IDENTIFYING WHEN A PROVIDER RECORD BECAME EFFECTIVE.
                PRVDR_HSTRY_OBSLT_DT, -- DATE | NOT NULL | A DATE IDENTIFYING WHEN A PROVIDER RECORD BECAME OBSOLETE.
                PRVDR_GNRC_ID_NUM, -- TEXT(20) | NULL | A GENERIC IDENTIFIER FOR PARTIES. FOR EXAMPLE, THIS COULD BE A UPIN, PIN, NSC SUPPLIER OR NCPDP NUMBER.
                PRVDR_TYPE_CD, -- TEXT(2) | NOT NULL | IDENTIFIES THE TYPE OF LEGACY PROVIDER IDENTIFIER.
                PRVDR_ID_QLFYR_CD, -- TEXT(2) | NOT NULL | THE TYPE OF DATA USED TO IDENTIFY THE SERVICE PROVIDER OF THE CLAIM: 01 = NPI 07 = NCPDP NUMBER 08 = STATE LICENSE NUMBER 11 = FEDERAL TAX NUMBER 12 = DEA
                PRVDR_BIRTH_DT, -- DATE | NOT NULL | A DATE OF BIRTH OF A PROVIDER.
                PRVDR_1ST_NAME, -- TEXT(35) | NULL | A FIRST NAME OF A PROVIDER.
                PRVDR_MDL_NAME, -- TEXT(25) | NULL | A MIDDLE NAME OF A PROVIDER.
                PRVDR_LAST_NAME, -- TEXT(35) | NULL | A LAST NAME OF A PROVIDER.
                PRVDR_NAME, -- TEXT(70) | NULL | THE NAME OF THE PROVIDER.
                PRVDR_LGL_NAME, -- TEXT(100) | NULL | THE SELF DESIGNATED LEGAL NAME OF THE ENTITY.
                PRVDR_NPI_NUM, -- TEXT(10) | NULL | NPI NUMBER FOR MEDICAID PROVIDERS.
                PRVDR_DMEPOS_NUM, -- TEXT(13) | NOT NULL
                PRVDR_EMPLR_ID_NUM, -- TEXT(10) | NULL | THE PROVIDERS EMPLOYER ID NUMBER (EMPLOYER IDENTIFICATION NUMBER (EIN), SOCIAL SECURITY NUMBER (SSN) OR INDIVIDUAL TAX IDENTIFICATION NUMBER (ITIN))
                PRVDR_STATE_LCNS_NUM, -- TEXT(20) | NULL | UNIQUE NUMBER THAT IDENTIFIES A DMEPOS SUPPLIER LICENSE. (IF FROM PECOS- DMEPOS LICENSE NUMBER IN ENTITY DMEPOS LICENSE)
                PRVDR_NCPDP_ID, -- TEXT(7) | NOT NULL | THE PROVIDERS NCPDP NUMBER.
                PRVDR_OSCAR_NUM, -- TEXT(13) | NOT NULL
                PRVDR_PIN_NUM, -- TEXT(14) | NOT NULL
                PRVDR_PIN_GRP_NUM, -- TEXT(14) | NOT NULL
                PRVDR_UPIN_NUM, -- TEXT(6) | NOT NULL | A UNIQUE PROVIDER IDENTIFICATION NUMBER (UPIN) ASSIGNED TO A PROVIDER ELIGIBLE TO ORDER OR REFER SERVICES.
                PRVDR_UPIN_GRP_NUM, -- TEXT(6) | NOT NULL | A UNIQUE PROVIDER IDENTIFICATION NUMBER (UPIN) ASSIGNED TO A PROVIDER ELIGIBLE TO ORDER OR REFER SERVICES.
                PRVDR_OTHR_ID, -- TEXT(20) | NULL | A UNIQUE HEALTHCARE PROVIDER OTHER IDENTIFICATION NUMBER.
                PRVDR_MLG_LINE_1_ADR, -- TEXT(100) | NULL | THE FIRST LINE OF A PARTY ADDRESS.
                PRVDR_MLG_LINE_2_ADR, -- TEXT(100) | NULL | THE SECOND LINE OF A PARTY ADDRESS.
                PRVDR_INVLD_MLG_PLC_NAME, -- TEXT(40) | NULL | INVALID MAILING PLACE NAME. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_INVLD_MLG_ZIP_CD, -- TEXT(9) | NULL | INVALID MAILING ZIP CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_INVLD_MLG_STATE_CD, -- TEXT(2) | NULL | INVALID MAILING STATE CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                GEO_PRVDR_MLG_SK, -- NUMBER(38) | NOT NULL | IDENTIFIER OF THE GEOGRAPHICAL AREA ASSOCIATED WITH THE PROVIDER.
                GEO_PRVDR_MLG_ZIP4_CD, -- TEXT(4) | NOT NULL | A FOUR DIGIT EXTENSION TO A ZIP CODE THAT REPRESENTS A SUBDIVISION FOR MAILING PURPOSES OF THE ZIP CODE.
                PRVDR_MLG_TEL_NUM, -- TEXT(20) | NULL | TELEPHONE NUMBER
                PRVDR_PRCTC_LINE_1_ADR, -- TEXT(100) | NULL | THE FIRST LINE OF A PARTY ADDRESS.
                PRVDR_PRCTC_LINE_2_ADR, -- TEXT(100) | NULL | THE SECOND LINE OF A PARTY ADDRESS.
                PRVDR_INVLD_PRCTC_PLC_NAME, -- TEXT(40) | NULL | INVALID PRACTICE PLACE NAME. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_INVLD_PRCTC_ZIP_CD, -- TEXT(9) | NULL | INVALID PRACTICE ZIP CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_INVLD_PRCTC_STATE_CD, -- TEXT(2) | NULL | INVALID PRACTICE STATE CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                GEO_PRVDR_PRCTC_SK, -- NUMBER(38) | NOT NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_PRVDR_PRCTC_ZIP4_CD, -- TEXT(4) | NOT NULL | A FOUR DIGIT EXTENSION TO A ZIP CODE THAT REPRESENTS A SUBDIVISION FOR MAILING PURPOSES OF THE ZIP CODE.
                PRVDR_PRCTC_TEL_NUM, -- TEXT(20) | NULL | TELEPHONE NUMBER FOR THE PROVIDERÒ² PRACTICE LOCATION.
                PRVDR_SRC_ID, -- TEXT(5) | NOT NULL | UNIQUE IDENTIFIER OF A SOURCE.
                PRVDR_TXNMY_CMPST_CD, -- TEXT(150) | NULL | A COMBINATION OF MULTIPLE NATIONAL PROVIDER PLAN ENUMERATION SYSTEM (NPPES) TAXONOMY CODES NOTE: UP TO 15 COMBINATIONS MAY EXIST. THE DATA FROM SOURCE WILL BE STORED AS IT IS.
                META_LST_UPDT_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT UPDATED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_LTST_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_LST_UPDT_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS UPDATED IN THE IDR.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_HSTRY"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrHstryExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
