"""
==========
V2_MDCR_PRVDR_OF_SRVC_CLIA IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_CLIA

Table Type: VIEW
Columns: 81
Source Pattern: %mdcr_prvdr%
Table Comment: AN INSTITUTIONAL PROVIDER THAT IS A MEDICARE-APPROVED CLINICAL LABORATORY PROVIDER.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrOfSrvcCliaExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrOfSrvcCliaExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_OF_SRVC_CLIA data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_CLIA (VIEW)
    Columns: 81
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_of_srvc_clia_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_OF_SRVC_CLIA export.
        
        Includes all 81 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_OSCAR_NUM, -- TEXT(10) | NOT NULL | AN ONLINE SURVEY CERTIFICATION AND REPORT (OSCAR) NUMBER ASSIGNED TO A PROVIDER BY A MEDICARE ADMINISTRATIVE CONTRACTOR (MAC).
                PRVDR_OF_SRVC_EFCTV_DT, -- DATE | NOT NULL | THE DATE THAT THE PROVIDER DATA BECAME EFFECTIVE
                PRVDR_AABB_ACRDTN_DT, -- DATE | NULL | THE DATE THE AMERICAN ASSOCIATION OF BLOOD BANKS NOTIFIES CMS THAT LAB IS ACCREDITED WITH AABB. THE EARLIEST Y MATCH DATE INITIATES THE BILLING OF THE CERTIFICATE OF ACCREDITATION FEES.
                PRVDR_AABB_ACRDTN_SW, -- TEXT(1) | NULL | A CODE TO INDICATE WHETHER OR NOT A LAB IS ACCREDITED BY THE AMERCIAN ASSOCIATION OF BLOOD BANKS (AABB) - AN INTERNATIONAL, NOT-FOR-PROFIT ASSOCIATION REPRESENTING INDIVIDUALS AND INSTITUTIONS INVOLVED IN THE FIELD OF TRANSFUSION MEDICINE AND CELLULAR THERAPIES.
                PRVDR_AABB_ACRDTN_VLDTN_SW, -- TEXT(1) | NULL | INDICATES IF THE LAB IS ACCREDITED BY THE AMERICAN ASSOCIATION OF BLOOD BANKS. THIS INFORMATION IS SUPPLIED BY THE ACCREDITING ORGANIZATION.
                PRVDR_AFLTD_PRVDR_1_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 1
                PRVDR_AFLTD_PRVDR_2_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 2
                PRVDR_AFLTD_PRVDR_3_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 3
                PRVDR_AFLTD_PRVDR_4_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 4
                PRVDR_AFLTD_PRVDR_5_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 5
                PRVDR_AFLTD_PRVDR_6_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 6
                PRVDR_AFLTD_PRVDR_7_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 7
                PRVDR_AFLTD_PRVDR_8_NUM, -- TEXT(10) | NULL | AFFILIATED PROVIDER NUMBER 8
                PRVDR_AOA_ACRDTN_DT, -- DATE | NULL | THE DATE OF ACCREDITATION NOTIFICATION TO THE LAB FROM AMERICAN OSTEOPATHIC ASSOCIATION.
                PRVDR_AOA_ACRDTN_SW, -- TEXT(1) | NULL | A CODE TO INDICATE WHETHER OR NOT A LAB IS ACCREDITED BY THE AMERICAN OSTEOPATHIC ASSOCIATION (AOA) THROUGH THE HEALTHCARE FACILITIES ACCREDITATION PROGRAM - A NATIONALLY RECOGNIZED ACCREDITATION ORGANIZATION WITH DEEMING AUTHORITY FROM CMS.
                PRVDR_AOA_ACRDTN_VLDTN_SW, -- TEXT(1) | NULL | INDICATES IF THE LAB IS ACCREDITED BY THE AMERICAN OSTEOPATHIC ASSOCIATION. THIS INFORMATION IS SUPPLIED BY THE ACCREDITING ORGANIZATION.
                PRVDR_ASHI_ACRDTN_DT, -- DATE | NULL | THE DATE OF ACCREDITATION NOTIFICATION TO THE LAB FROM THE AMERICAN SOCIETY FOR HISTOCOMPATIBILITY AND IMMUNOGENETICS (ASHI).
                PRVDR_ASHI_ACRDTN_SW, -- TEXT(1) | NULL | A CODE TO INDICATE WHETHER OR NOT A LAB IS ACCREDITED BY THE AMERICAN SOCIETY FOR HISTOCOMPATABILITY (ASHI) THROUGH THE ASHI ACCREDITATION PROGRAM.
                PRVDR_ASHI_ACRDTN_VLDTN_SW, -- TEXT(1) | NULL | INDICATES IF THE LAB IS ACCREDITED BY THE AMERICAN SOCIETY FOR HISTOCOMPATIBILITY AND IMMUNOGENETICS (ASHI). THIS INFORMATION IS SUPPLIED BY THE ACCREDITING ORGANIZATION.
                PRVDR_CAP_ACRDTN_DT, -- DATE | NULL | THE DATE OF ACCREDITATION NOTIFICATION TO THE LAB FROM THE COLLEGE OF AMERICAN PATHOLOGISTS (CAP). THE EARLIEST Y MATCH DATE INITIATES THE BILLING FOR THE CERTIFICATE OF ACCREDITATION FEES.
                PRVDR_CAP_ACRDTN_SW, -- TEXT(1) | NULL | A CODE TO INDICATE WHETHER OR NOT A LAB IS ACCREDITED BY THE COLLEGE OF AMERICAN PATHOLOGISTS (CAP) THROUGH THE CAP ACCREDITATION PROGRAM.
                PRVDR_CAP_ACRDTN_VLDTN_SW, -- TEXT(1) | NULL | INDICATES IF THE LAB IS ACCREDITED BY COLLEGE OF AMERICAN PATHOLOGISTS (CAP). THIS INFORMATION IS SUPPLIED BY THE ACCREDITING ORGANIZATION.
                PRVDR_CLIA_67_LCNSD_SW, -- TEXT(1) | NULL | INDICATES IF THE LABORATORY WAS LICENSED UNDER CLIA 67 OR PARTICIPATED IN THE MEDICARE/MEDICAID PROGRAMS.
                PRVDR_CLIA_ACRDTN_SCHDL_CD, -- TEXT(1) | NOT NULL | A CODE FOR PROVIDER CLINICAL LABORATORY IMPROVEMENT ACT ACCREDITATION SCHEDULE
                PRVDR_CLIA_ACRDTN_TEST_VOL_CNT, -- NUMBER(13) | NULL | THE NUMBER OF ACCREDITED TESTING OCCURRENCES WITHIN A YEAR - RECORDED FOR SUBMISSION ON THE LABORATORYS CMS 116 APPLICATION FORM.
                PRVDR_CLIA_APLCTN_DT, -- DATE | NULL | THE DATE OF RECEIPT OF THE CLIA APPLICATION FORM - EITHER NEW OR UPDATED..
                PRVDR_CLIA_APLCTN_TYPE_CD, -- TEXT(1) | NOT NULL | A CODE TO SPECIFY THE TYPE OF CLIA CERTIFICATE REQUESTED BY A LABORTORY ON THE CMS-116 APPLICATION FORM.
                PRVDR_CLIA_APLCTN_TEST_VOL_CNT, -- NUMBER(13) | NULL | THE TOTAL NUMBER OF TESTING OCCURRENCES WITHIN A YEAR - RECORDED FOR SUBMISSION ON THE LABORATORYS CMS -116 APPLICATION FORM.
                PRVDR_CLIA_CLSFCTN_1_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 1
                PRVDR_CLIA_CLSFCTN_2_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 2
                PRVDR_CLIA_CLSFCTN_3_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 3
                PRVDR_CLIA_CLSFCTN_4_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 4
                PRVDR_CLIA_CLSFCTN_5_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 5
                PRVDR_CLIA_CLSFCTN_6_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 6
                PRVDR_CLIA_CLSFCTN_7_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 7
                PRVDR_CLIA_CLSFCTN_8_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 8
                PRVDR_CLIA_CLSFCTN_9_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 9
                PRVDR_CLIA_CLSFCTN_10_CD, -- TEXT(2) | NOT NULL | LABORATORY CLASSIFICATION 10
                PRVDR_CLIA_CRNT_LAB_CLSFCTN_CD, -- TEXT(2) | NOT NULL | CURRENT LAB CLASSIFICATION
                PRVDR_CLIA_CMPLNT_SCHDL_CD, -- TEXT(1) | NOT NULL | 1557 COMPLIANCE SCHEDULE CODE. THIS CODE IS SYSTEM-GENERATED AND IS BASED ON THE NUMBER OF TESTS AND SPECIALTIES ENTERED INTO ODIE FOLLOWING THE SURVEY.
                PRVDR_CLIA_CRTFCT_EFCTV_DT, -- DATE | NULL | DATE THE CURRENT LABORATORY CERTIFICATE IS EFFECTIVE, DETERMINED BY THE APPROVAL DATE OF THE CERTIFICATE APPLICATION UNLESS OVERRIDDEN.
                PRVDR_CLIA_CRTFCT_LAB_CNT, -- NUMBER(38) | NULL | THE TOTAL NUMBER OF LAB SITES FOR WHICH A LAB HAS APPLIED FOR A SINGLE CERTIFICATE.
                PRVDR_CLIA_CRTFCT_SCHDL_CD, -- TEXT(1) | NOT NULL | 1557 CERTIFICATE SCHEDULE CODE. THIS CODE IS SYSTEM-GENERATED AND IS BASED ON THE TEST VOLUME AND SPECIAL TIES ENTERED INTO ODIE FOLLOWING THE SURVEY. CLIA FEES ARE BASED ON THE SCHEDULE CODES.
                PRVDR_CLIA_CRTFCT_TYPE_CD, -- TEXT(1) | NOT NULL | A CODE THAT IDENTIFIES THE TYPE OF LABORATORY CERTIFICATE CURRENTLY IN EFFECT.
                PRVDR_CLIA_CRTFCT_MAILED_DT, -- DATE | NULL | THE DATE THE CERTIFICATE WAS MAILED.
                PRVDR_CLIA_MDCR_NUM, -- TEXT(12) | NULL | CLIA MEDICARE NUMBER
                PRVDR_CLIA_PGM_TRMNTN_RSN_CD, -- TEXT(2) | NOT NULL | A CODE FOR THE REASON A FACILITY HAS BEEN TERMINATED FROM THE CLIA, MEDICARE AND/OR MEDICAID PROGRAMS.
                PRVDR_CLIA_SRVY_TEST_VOL_CNT, -- NUMBER(13) | NULL | SURVEY TEST VOLUME TOTAL. THE NUMBER OF TESTS PERFORMED ANNUALLY IN A LABORATORY. THIS INFORMATION IS COLLECTED AT THE TIME OF THE STATE SURVEY AGENCY INSPECTION.
                PRVDR_COOLA_ACRDTN_DT, -- DATE | NULL | THE DATE OF ACCREDITATION NOTIFICATION TO THE LAB FROM THE COMMISSION OF OFFICE LABORATORY ACCREDITATION (COLA). THE EARLIEST Y MATCH DATE INITIATES THE BILLING OF THE CERTIFICATE OF ACCREDITATION FEES.
                PRVDR_COOLA_ACRDTN_SW, -- TEXT(1) | NULL | A CODE TO INDICATE WHETHER OR NOT A LAB IS ACCREDITED BY THE COMMISSION ON OFFICE LABORATORY ACCREDITATION (COLA) IN THE AREAS OF CHEMISTRY, HEMATOLOGY, MICROBIOLOGY. IMMUNOLOGY, AND IMMUNOHEMATOLOGY/TRANSFUSION SERVICES
                PRVDR_COOLA_ACRDTN_VLDTN_SW, -- TEXT(1) | NULL | INDICATES IF THE LAB IS ACCREDITED BY THE COMMISSION ON OFFICE LABORATORY ACCREDITATION (COLA). THIS INFORMATION IS SUPPLIED BY THE ACCREDITING ORGANIZATION.
                PRVDR_DRCTLY_AFLTD_LAB_CNT, -- NUMBER(3) | NULL | NUMBER OF LABORATORIES DIRECTLY AFFILIATED
                PRVDR_FAC_TYPE_CD, -- TEXT(2) | NOT NULL | A CODE FOR PROVIDER FACILITY TYPE
                PRVDR_JCAHO_ACRDTN_CD, -- TEXT(1) | NOT NULL | A CODE TO INDICATE WHETHER OR NOT A LAB IS ACCREDITED BY THE JOINT COMMISSION ON ACCREDITATION OF HEALTH CARE ORGANIZATIONS (JCAHO) IN THE AREAS OF AMBULATORY/BEHAVIORAL HEALTHCARE, CRITICAL ACCESS HOSPITALS, HOME CARE HOSPITAL, LABORATORY SERVICES, NURSING AND REHABILITATION CENTER, OFFICE-BASED SURGERY, PRIMARY CARE MEDICAL HOME CERTIFICATION.
                PRVDR_JCAHO_ACRDTN_DT, -- DATE | NULL | THE DATE OF ACCREDITATION NOTIFICATION TO THE LAB FROM THE JOINT COMMISSION ON ACCREDITATION OF HEALTH CARE ORGANIZATIONS (JCAHO). THE EARLIEST Y MATCH DATE INITIATES BILLING.
                PRVDR_JCAHO_VLDTN_SW, -- TEXT(1) | NULL | INDICATES THAT A LABORATORY RECORD IS UPDATED WITH A CHANGE THAT DIRECTLY AFFECTS THE CLIA CERTIFICATE DATA. WHEN CHANGED, THE INFORMATION IS THEN MADE AVAILABLE TO THE MEDICAID STATE AGENCIES.
                PRVDR_MLTPL_SITE_APLCTN_SW, -- TEXT(1) | NULL | INDICATES IF A LAB HAS APPLIED FOR ONE CERTIFICATE FOR MULTIPLE SITES.
                PRVDR_NPRFT_SW, -- TEXT(1) | NULL | NON-PROFIT CODE INDICATOR.
                PRVDR_PPMP_TEST_CNT, -- NUMBER(13) | NULL | THE VOLUME OF TESTS PERFORMED BY THE PPMP
                PRVDR_SHRD_LAB_SW, -- TEXT(1) | NULL | INDICATES WHETHER THE LABORATORY IS SHARED.
                PRVDR_SHRD_LAB_XREF_NUM, -- TEXT(10) | NULL | SHARED LAB XREF NUMBER
                PRVDR_TOT_WVD_TEST_CNT, -- NUMBER(13) | NULL | THE TOTAL WAIVED VOLUME AMOUNT OF THE SUBSTANCE BEING TESTED (E.G., URINE, BLOOD).
                PRVDR_GNRL_SPRVSR_CNT, -- NUMBER(4) | NULL | NUMBER OF GENERAL SUPERVISORS AS REPORTED ON THE LABORATORY APPLICATION FORM HCFA-116 THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_CLNCL_CNSLTNT_CNT, -- NUMBER(4) | NULL | NUMBER OF CLINICAL CONSULTANTS AS REPORTED ON THE LABORATORY APPLICATION FORM HCFA-116. THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_DRCTR_CNT, -- NUMBER(4) | NULL | NUMBER OF DIRECTORS AS REPORTED ON THE LABORATORY APPLICATION FORM HCFA-116. THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_TCHNCL_CNSLTNT_CNT, -- NUMBER(4) | NULL | NUMBER OF TECHNICAL CONSULTANTS AS REPORTED ON THE LABORATORY APPLICATION FORM HCFA-116 THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_TCHNCL_SPRVSR_CNT, -- NUMBER(4) | NULL | NUMBER OF TECHNICAL SUPERVISORS AS REPORTED ON THE LABORATORY APPLICATION FORM HCFA-116 THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_APLCTN_TEST_PRSNEL_CNT, -- NUMBER(4) | NULL | NUMBER OF TEST PERSONNEL AS REPORTED ON THE LABORATORY APPLICATION FORM HCFA-116. THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_WVD_LAB_TEST_PRSNEL_CNT, -- NUMBER(6) | NULL | TOTAL NUMBER OF INDIVIDUALS INVOLVED IN WAIVED LABORATORY TESTING AS REPORTED ON THE LABORATORY APPLICATION FORM HCFA 116 THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_PENDG_LAB_CLSFCTN_CD, -- TEXT(2) | NOT NULL | A CODE FOR CLINICAL LABORATORY IMPROVEMENT ACT (CLIA) LABORATORY CLASSIFICATION THAT INDICATES IF THE LAB IS CLIA EXEMPT, VA LABORATORY OR STANDARD LABORATORY.
                PRVDR_NON_WVD_PRSNEL_CNT, -- NUMBER(9) | NULL | TOTAL NUMBER NON-WAIVED INDIVIDUALS LISTED ON PAGE 4 OF THE HCFA-116. THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_APLCTN_AALA_ACRDTN_SW, -- TEXT(1) | NULL | A SWITCH TO INDICATE IF THE LAB IS ACCREDITED BY THE AMERICAN ASSOCIATION OF LABORATORY ACCREDITATION. THIS FIELD PERTAINS TO HISTORICAL POS DATA DATED 2006-2007. IT WAS REMOVED IN 2008.
                PRVDR_A2LA_ACRDTN_DT, -- DATE | NULL | THE DATE THE AMERICAN ASSOCIATION OF LABORATORY ACCREDITATION (A2LA) NOTIFIES CMS THAT THE LAB IS ACCREDITED BY A2LA. THE EARLIEST Y MATCH DATE (THE DATE WHEN CMS WAS NOTIFIED THAT THE LAB WAS ACCREDITED) INITIATES THE BILLING OF THE CERTIFICATE OF ACCREDITATION FEES.
                PRVDR_A2LA_ACRDTN_SW, -- TEXT(1) | NULL | A SWITCH TO INDICATE IF THE LAB IS ACCREDITED BY THE AMERICAN ASSOCIATION OF LABORATORY ACCREDITATION. THIS INFORMATION IS SUPPLIED BY THE ACCREDITING ORGANIZATION.
                PRVDR_A2LA_ACRDTN_VLDTN_SW, -- TEXT(1) | NOT NULL | INDICATES IF THE LAB IS CONFIRMED AS ACCREDITED BY THE AMERICAN ASSOCIATION FOR LABORATORY ACCREDITATION.
                PRVDR_ADDTNL_FAC_NAME, -- TEXT(50) | NULL | SECOND LINE OF A LABORATORY NAME.
                PRVDR_ADDTNL_ST_ADR, -- TEXT(50) | NULL | SECOND LINE OF A LABORATORYS STREET ADDRESS.
                PRVDR_HOSP_LAB_EXCPTN_SW, -- TEXT(1) | NOT NULL | INDICATES IF THE SINGLE SITE CLIA CERTIFICATE IS FOR A HOSPITAL WITH SEVERAL LABS ON A SINGLE HOSPITAL CAMPUS AND UNDER COMMON DIRECTION.
                PRVDR_LAB_TEMP_TSTNG_STE_SW, -- TEXT(1) | NOT NULL | INDICATES IF THE SINGLE SITE CLIA CERTIFICATE IS FOR A LAB WITH MULTIPLE TEMPORARY TESTING SITES.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_OF_SRVC_CLIA"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrOfSrvcCliaExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
