"""
==========
V2_MDCR_PRVDR_PRCTC_LCTN IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN

Table Type: VIEW
Columns: 40
Source Pattern: %mdcr_prvdr%
Table Comment: THE PRACTICE LOCATION CHILD RECORD IS CREATED TO INCLUDE THE PROVIDERS PRACTICE LOCATION INFORMATION. PECOS WILL SEND BOTH HISTORIC AND CURRENT PRACTICE LOCATION INFORMATION. THE PRACTICE LOCATION INFORMATION IS LINKED TO THE SPECIAL PAYMENT INFORMATION.  PECOS: EACH INSTANCE CONTAINS INFORMATION ABOUT THE PHYSICAL  LOCATION WHERE THIS PROVIDER CURRENTLY RENDERS HEALTH CARE SERVICES.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrPrctcLctnExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrPrctcLctnExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_PRCTC_LCTN data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN (VIEW)
    Columns: 40
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_prctc_lctn_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_PRCTC_LCTN export.
        
        Includes all 40 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_PRCTC_BGN_DT, -- DATE | NOT NULL | THE EFFECTIVE DATE OF A PRACTICE LOCATION.
                PRVDR_PRCTC_END_DT, -- DATE | NULL | THE TERMINATION DATE OF A PRACTICE LOCATION
                PRVDR_PRCTC_NAME, -- TEXT(70) | NOT NULL | THE NAME OF THE PRACTICE LOCATION. ALSO REFERRED TO AS THE DOING BUSINESS AS (DBA) NAME.
                PRVDR_PRCTC_LINE_1_ADR, -- TEXT(55) | NOT NULL | THE FIRST ADDRESS LINE OF A PRACTICE LOCATION.
                PRVDR_PRCTC_LINE_2_ADR, -- TEXT(55) | NULL | THE SECOND ADDRESS LINE OF A PRACTICE LOCATION.
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_INVLD_PLC_NAME, -- TEXT(30) | NULL | CITY WHERE PRACTICE LOCATION, STORAGE LOCATION OR PAY TO ADDRESS IS LOCATED. THE INVALID PLACE NAME OF A PRACTICE LOCATION. POPULATED WHEN THE PLACE NAME SUPPLIED BY THE SOURCE FOR A GIVEN ZIP CODE DOES NOT MATCH THE PLACE NAME FOR THE ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA.
                PRVDR_INVLD_STATE_CD, -- TEXT(2) | NULL | UNIQUE VALUE THAT IDENTIFIES A STATE. THE INVALID STATE CODE OF A PRACTICE LOCATION. POPULATED WHEN THE STATE CODE SUPPLIED BY THE SOURCE FOR A GIVEN ZIP CODE DOES NOT MATCH THE STATE CODE FOR THE ZIP CODE IN THE AUTHORITATIVE SOURCE FOR ZIP CODE DATA.
                PRVDR_INVLD_ZIP_CD, -- TEXT(9) | NULL | ZIP CODE FOR A PRACTICE LOCATION, STORAGE ADDRESS OR A PAY TO ADDRESS. INVALID ZIP CODE OF PRACTICE LOCATION. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_PRCTC_PHNE_NUM, -- TEXT(20) | NOT NULL | THE TELEPHONE NUMBER OF A PRACTICE LOCATION
                PRVDR_PRCTC_FAX_NUM, -- TEXT(20) | NULL | THE FAX NUMBER OF A PRACTICE LOCATION.
                PRVDR_PRCTC_EMAIL_ADR, -- TEXT(80) | NULL | THE EMAIL ADDRESS OF A PRACTICE LOCATION.
                PRVDR_PRCTC_LCTN_KEY, -- TEXT(20) | NOT NULL | UNIQUE KEY USED TO IDENTIFY A PRACTICE LOCATION.
                PRVDR_SK, -- NUMBER(18) | NULL | AN IDR ASSIGNED SURROGATE KEY USED TO IDENTIFY A PARTY ENGAGED IN ACTIVITY RELATED TO CMS.
                META_SK, -- NUMBER(38) | NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_PECOS_SK, -- NUMBER(38) | NOT NULL | A UNIQUE IDENTIFIER ASSIGNED BY IDR
                PRVDR_RPT_SW, -- TEXT(1) | NULL | AN INDICATION THAT THERE IS A UNIQUENESS PROBLEM IN THE SOURCE DATA
                PRVDR_DRVD_END_DT, -- DATE | NOT NULL | END DATE OF INPUT FILE
                PRVDR_CLIA_NUM, -- TEXT(15) | NOT NULL | CLIA NUMBER ASSOCIATED WITH THAT PRACTICE LOCATION. (CLINICAL LABORATORY IMPROVEMENT ACT)
                PRVDR_PRCTC_CLM_PIN_NUM, -- TEXT(10) | NULL | THIS NUMBER UNIQUELY IDENTIFIES THE APPLICANT AS A MEDICARE PROVIDER AND/OR SUPPLIER AND IS THE NUMBER USED ON CLAIM FORMS. - CLAIMS SYSTEM PIN
                PRVDR_PRCTC_CREAT_DT, -- DATE | NOT NULL | SYSTEM GENERATED NUMBER THAT IDENTIFIES A PRACTICE LOCATION RECORD.
                PRVDR_PRCTC_EXTNSN_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THE PRACTICE LOCATION IS AN OUTPATIENT PHYSICAL THERAPY EXTENSION SITE.
                PRVDR_PRCTC_HHA_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS AN HHA BRANCH. (ONLY APPLICABLE FOR HOSPITALS AND HHAS)
                PRVDR_PRCTC_LCTN_TYPE_CD, -- TEXT(1) | NULL | UNIQUE VALUE THAT IDENTIFIES WHETHER THE ORGANIZATION FURNISHES HEALTH CARE SERVICES FROM A PORTABLE UNIT OR MOBILE FACILITY. USES P, O, B, AND NULL TO REPRESENT PRACTICE LOCATION, BASE OF OPERATIONS, AND BOTH RESPECTIVELY.
                PRVDR_PRCTC_NPI_SW, -- TEXT(1) | NULL | NPI INDICATOR
                PRVDR_PRCTC_OTHR_DESC, -- TEXT(60) | NULL | TYPE OF HEALTH CARE FACILITY THAT USES THIS PRACTICE LOCATION.
                PRVDR_PRCTC_OTHR_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS A HEALTH CARE FACILITY OTHER THAN WHAT IS LISTED ON THE FORM.
                PRVDR_PRCTC_PRMRY_LCTN_SW, -- TEXT(1) | NULL | PRIMARY PRACTICE LOCATION CHECKBOX HAS BEEN ADDED TO THE PRACTICE LOCATION SUB SCREEN. THIS COLUMN WILL STORE THE SELECTED VALUE, Y IF CHECKED AND N IF IT IS NOT CHECKED. ADDED AS PART OF CML 742.
                PRVDR_PRCTC_PSYCH_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS A HOSPITAL PSYCHIATRIC UNIT. (ONLY APPLICABLE FOR HOSPITALS AND HHAS)
                PRVDR_PRCTC_REHAB_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THIS PRACTICE LOCATION IS A HOSPITAL REHABILITATION UNIT. (ONLY APPLICABLE FOR HOSPITALS AND HHAS)
                PRVDR_PRCTC_RRB_PIN_NUM, -- TEXT(10) | NULL | IT STORES RAILROAD RETIREMENT BOARD PIN INFORMATION OF A PECOS ASSOCIATE.
                PRVDR_PRCTC_RRB_SW, -- TEXT(1) | NULL | RAILROAD BOARD INDICATOR
                PRVDR_PRCTC_SB_SW, -- TEXT(1) | NOT NULL | INDICATES WHETHER THE PRACTICE LOCATION HAS A SWING BED UNIT.
                PRVDR_ENRLMT_CNTRCTR_ID, -- TEXT(5) | NOT NULL | UNIQUE NUMBER THAT IDENTIFIES A MEDICARE CONTRACTOR.
                PRVDR_ENRLMT_CREAT_DT, -- DATE | NOT NULL | DATE THE RECORD WAS CREATED (MM/DD/YYYY)
                PRVDR_PAC_ID, -- TEXT(10) | NOT NULL | THE SYSTEM GENERATED PECOS ASSOCIATE CONTROL ID.
                PRVDR_ENRLMT_ID, -- TEXT(15) | NOT NULL | PECOS SYSTEM GENERATED ENROLLMENT IDENTIFIER.
                PRVDR_INVLD_NPI_NUM -- TEXT(15) | NULL | AN PROVIDER NPI NUMBER THAT CANNOT BE MATCHED IN THE CURRENT PROVIDER TABLE.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_PRCTC_LCTN"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrPrctcLctnExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
