"""
==========
V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC IDR Export (Auto-Generated)
==========

Auto-generated IDROutputter implementation for IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC

Table Type: VIEW
Columns: 35
Source Pattern: %mdcr_prvdr%
Table Comment: THE NATIONAL COUNCIL FOR PRESCRIPTION DRUG PROGRAMS (NCPDP)  MAINTAINED INFORMATION CLASSIFYING THE TYPE OF ENTITY.

This script provides a complete IDROutputter subclass that exports all columns
from the table in their original Snowflake order. You can customize the
getSelectQuery() method to add WHERE clauses, JOINs, or modify column selection.

Usage:
    # In a Snowflake notebook environment:
    exporter = V2MdcrPrvdrNcpdpRltnDmgrphcExporter()
    exporter.do_idr_output()
"""

# Import python packages
import pandas as pd
from datetime import datetime

# Import the IDROutputter base class
try:
    from IDROutputter import IDROutputter
except ImportError:
    print("Loading IDROutputter from previous cell or add proper import path")


class V2MdcrPrvdrNcpdpRltnDmgrphcExporter(IDROutputter):
    """
    Exports V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC data using IDROutputter base class.
    
    Auto-generated from table metadata. Customize as needed for your specific requirements.
    
    Table: IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC (VIEW)
    Columns: 35
    """
    
    # Class properties
    version_number: str = "v01"
    file_name_stub: str = "v2_mdcr_prvdr_ncpdp_rltn_dmgrphc_idr_export"
    
    def getSelectQuery(self) -> str:
        """
        Returns the SELECT query for V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC export.
        
        Includes all 35 columns in their original Snowflake order.
        Customize this method to add WHERE clauses, JOINs, or modify column selection.
        """
        return """SELECT
                PRVDR_NCPDP_RLTN_ID, -- TEXT(3) | NOT NULL | THE IDENTIFIER ASSIGNED TO REPRESENT THE RELATIONSHIP ASSOCIATED WITH THE PROVIDER.
                PRVDR_NCPDP_RLTNSHP_TYPE_CD, -- TEXT(2) | NOT NULL | TYPE OF RELATIONSHIP. 01=CHAIN 02=FRANCHISE 03=PURCHASING BUYING GROUP 04=THIRD PARTY RECONCILIATION ENTITY 05=THIRD PARTY CONTRACTING GROUP
                PRVDR_NCPDP_RLTN_NAME, -- TEXT(35) | NULL | THE NAME OF THE RELATIONSHIP ENTITY.
                PRVDR_NCPDP_RLTN_LINE_1_ADR, -- TEXT(55) | NULL | THE FIRST ADDRESS LINE.
                PRVDR_NCPDP_RLTN_LINE_2_ADR, -- TEXT(55) | NULL | THE SECOND ADDRESS LINE.
                PRVDR_NCPDP_INVLD_RLN_PLC_NAME, -- TEXT(30) | NULL | INVALID RELATIONSHIP DEMOGRAPHIC PLACE NAME. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_INVLD_STATE_CD, -- TEXT(2) | NULL | INVALID RELATIONSHIP DEMOGRAPHIC STATE CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                PRVDR_NCPDP_RLTN_INVLD_ZIP_CD, -- TEXT(9) | NULL | INVALID RELATIONSHIP DEMOGRAPHIC ZIP CODE. POPULATED FROM THE SOURCE WHEN INCONSISTENT WITH THE GEOGRAPHY DATA FOR THE ZIP CODE.
                GEO_SK, -- NUMBER(38) | NULL | AN INTEGRATED DATA REPOSITORY (IDR) ASSIGNED NUMERIC SURROGATE KEY IDENTIFYING A PARTICULAR GEOGRAPHICAL LOCATION BY ITS FIVE-DIGIT ZIP CODE.
                GEO_ZIP4_CD, -- TEXT(4) | NULL | A FOUR-DIGIT ZIP CODE EXTENSION DEFINED BY THE UNITED STATES POSTAL SERVICE (USPS) THAT REPRESENTS A SPECIFIC DELIVERY ROUTE WITHIN A DELIVERY AREA ASSOCIATED WITH A BENEFICIARY, PROVIDER, OR CLAIM ADDRESS AND USED IN THE GEOCODING PROCESS. REFERENCE TABLE: GEO_ZIP9_CD
                PRVDR_NCPDP_RLTN_TEL_NUM, -- TEXT(10) | NULL | THE TELEPHONE NUMBER.
                PRVDR_NCPDP_RLTN_EXTNSN_NUM, -- TEXT(5) | NULL | THE TELEPHONE NUMBER EXTENSION.
                PRVDR_NCPDP_RLTN_FAX_NUM, -- TEXT(10) | NULL | THE FACSIMILE MACHINE TELEPHONE LINE NUMBER.
                PRVDR_NCPDP_RLTN_CNTCT_NAME, -- TEXT(30) | NULL | THE NAME OF THE PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_RLTN_TITLE_NAME, -- TEXT(30) | NULL | TITLE OF THE PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_RLTN_EMAIL_ADR, -- TEXT(50) | NULL | THE EMAIL ADDRESS OF THE PRIMARY CONTACT PERSON.
                PRVDR_NCPDP_PRNT_ORG_ID, -- TEXT(6) | NULL | HEADQUARTER ADDRESS INFORMATION FOR CHAINS, BUYING GROUPS OR THIRD PARTY CONTRACTING ORGANIZATIONS WHERE MULTIPLE RELATIONSHIP ENTITIES EXIST AND NEED TO BE LINKED TO A COMMON ORGANIZATION SUCH AS COMMON OWNERSHIP FOR SEVERAL CHAINS.
                PRVDR_NCPDP_RLTN_DLT_DT, -- DATE | NULL | THE DATE STAMPED BY NCPDP THAT THIS DEMOGRAPHIC RELATIONSHIP INFORMATION IS NO LONGER ACTIVE.
                META_SK, -- NUMBER(38) | NOT NULL | A UNIQUE LEGACY NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR), FORMULATED WITH A DATE AND A 3-DIGIT SEQUENCE NUMBER, WHICH IDENTIFIES THE BATCH PROCESS THAT INITIALLY LOADED A ROW IN THE IDR. DUE TO THE LIMITATION OF A 3-DIGIT VALUE, THIS IS BEING REPLACED BY META_SRC_PRCSG_ID ON NEW IDR TABLES AS THE SOURCE DATA TRACKING STANDARD.
                META_SRC_SK, -- NUMBER(38) | NOT NULL | A UNIQUE NUMERIC VALUE ASSIGNED BY THE INTEGRATED DATA REPOSITORY (IDR) USED TO IDENTIFY THE SPECIFIC SOURCE OF THE DATA WHEN A ROW IS LOADED INTO THE IDR. REFERENCE TABLE: V2_MDCR_META_DCTNRY_SRC
                PRVDR_NCPDP_RLTNSHP_NPI_NUM, -- TEXT(10) | NULL | THE UNIQUE NUMBER GENERATED BY THE NATIONAL PROVIDER SYSTEM FOR THE REQUESTING PROVIDER. (NPS 03/30/02) THE STANDARD UNIQUE HEALTH IDENTIFIER FOR HEALTH CARE PROVIDERS TO USE IN FILING AND PROCESSING HEALTH CARE CLAIMS AND OTHER TRANSACTIONS. AN ORGANIZATIONAL, TYPE 2, NPI ASSIGNED TO THE RELATIONSHIP ENTITY.
                PRVDR_NCPDP_FED_TAX_NUM, -- TEXT(15) | NULL | THE FEDERAL TAX ID, ALSO KNOWN AS EIN OR TIN, ASSIGNED TO THE RELATIONSHIP ENTITY.
                PRVDR_NCPDP_CNTRCTL_NAME, -- TEXT(30) | NULL | THE NAME OF THE CONTACT IN CHARGE OF CONTRACTS.
                PRVDR_NCPDP_CNTRCTL_TITLE_NAME, -- TEXT(30) | NULL | THE TITLE OF THE CONTACT IN CHARGE OF CONTRACTS.
                PRVDR_NCPDP_CNTRCTL_EMAIL_ADR, -- TEXT(50) | NULL | THE E-MAIL ADDRESS OF THE CONTACT IN CHARGE OF CONTRACTS.
                PRVDR_NCPDP_OPRTNL_NAME, -- TEXT(30) | NULL | THE NAME OF THE CONTACT IN CHARGE OF OPERATIONS.
                PRVDR_NCPDP_OPRTNL_TITLE_NAME, -- TEXT(30) | NULL | THE TITLE OF THE CONTACT IN CHARGE OF OPERATIONS.
                PRVDR_NCPDP_OPRTNL_EMAIL_ADR, -- TEXT(50) | NULL | THE E-MAIL ADDRESS OF THE CONTACT IN CHARGE OF OPERATIONS.
                PRVDR_NCPDP_TCHNCL_NAME, -- TEXT(30) | NULL | THE NAME OF THE CONTACT IN CHARGE OF TECHNICAL SUPPORT.
                PRVDR_NCPDP_TCHNCL_TITLE_NAME, -- TEXT(30) | NULL | THE TITLE OF THE CONTACT IN CHARGE OF TECHNICAL SUPPORT.
                PRVDR_NCPDP_TCHNCL_EMAIL_ADR, -- TEXT(50) | NULL | THE E-MAIL ADDRESS OF THE CONTACT IN CHARGE OF TECHNICAL SUPPORT.
                PRVDR_NCPDP_AUDT_NAME, -- TEXT(30) | NULL | THE NAME OF THE CONTACT IN CHARGE OF AUDITS.
                PRVDR_NCPDP_AUDT_TITLE_NAME, -- TEXT(30) | NULL | THE TITLE OF THE CONTACT IN CHARGE OF AUDITS.
                PRVDR_NCPDP_AUDT_EMAIL_ADR, -- TEXT(50) | NULL | THE E-MAIL OF THE CONTACT IN CHARGE OF AUDITS.
                PRVDR_NCPDP_RLTNSHP_BGN_DT -- DATE | NULL | THE DATE THAT THE RELATIONSHIP BECOMES ACTIVE. IF INFORMATION IS UNKNOWN, THIS FIELD WILL CONTAIN ZEROES.
            FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP_RLTN_DMGRPHC"""


if __name__ == '__main__':
    # Execute the export using the IDROutputter framework
    exporter = V2MdcrPrvdrNcpdpRltnDmgrphcExporter()
    exporter.do_idr_output()

# To download use: 
# snowsql -c cms_idr -q "GET @~/ file://. PATTERN='.*.csv';"
# Or look in ../misc_scripts/ for download_and_merge_all_snowflake_csv.sh
